import os, json, pathlib

BASE   = os.path.join(os.path.dirname(__file__), "blog")
DOMAIN = "https://produtovivo.com.br"
PIXEL  = "4520253334926563"

TMPL = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)}};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init','{pixel}');fbq('track','PageView');
</script>
<style>
body{{font-family:sans-serif;margin:0;padding:0;color:#222}}
header{{background:#0a7c4e;padding:16px 24px}}
header a{{color:#fff;text-decoration:none;font-size:1.3rem;font-weight:700}}
main{{max-width:860px;margin:40px auto;padding:0 20px}}
h1{{font-size:2rem;color:#0a7c4e}}
h2{{font-size:1.3rem;color:#065f3a;margin-top:32px}}
p{{line-height:1.7}}
.lead{{font-size:1.1rem;color:#444}}
.faq{{background:#f4faf7;border-left:4px solid #0a7c4e;padding:20px 24px;margin-top:40px}}
.faq h2{{margin-top:0}}
.faq-item{{margin-bottom:20px}}
.faq-item h3{{margin-bottom:4px;color:#065f3a}}
footer{{text-align:center;padding:32px;color:#777;font-size:.9rem;margin-top:60px}}
</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<header><a href="/">ProdutoVivo</a></header>
<main>
<h1>{h1}</h1>
<p class="lead">{lead}</p>
{body}
<div class="faq">
<h2>Perguntas Frequentes</h2>
{faqs}
</div>
</main>
<footer>© 2025 ProdutoVivo · Conteúdo informativo sobre gestão e tecnologia</footer>
</body>
</html>"""

def art(slug, title, desc, h1, lead, sections, faq_list):
    url = f"{DOMAIN}/blog/{slug}/"
    body_html = ""
    for sec_title, sec_body in sections:
        body_html += f"<h2>{sec_title}</h2>\n<p>{sec_body}</p>\n"
    faqs_html = ""
    schema_faqs = []
    for q, a in faq_list:
        faqs_html += f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>\n'
        schema_faqs.append({"@type": "Question", "name": q,
                             "acceptedAnswer": {"@type": "Answer", "text": a}})
    schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage",
                         "mainEntity": schema_faqs}, ensure_ascii=False)
    html = TMPL.format(title=title, desc=desc, url=url, pixel=PIXEL,
                       h1=h1, lead=lead, body=body_html, faqs=faqs_html, schema=schema)
    out_dir = os.path.join(BASE, slug)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

# Article 4735 — B2B SaaS: Events and corporate event management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-eventos-e-gestao-de-eventos-corporativos",
    title="Gestão de Negócios de Empresa de B2B SaaS de Eventos e Gestão de Eventos Corporativos",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para eventos e gestão de eventos corporativos: modelo de negócio, plataformas de credenciamento, go-to-market e métricas do setor.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Eventos e Gestão de Eventos Corporativos",
    lead="O mercado de eventos no Brasil movimenta R$200 bilhões por ano, com mais de 590 mil eventos corporativos realizados anualmente. Plataformas SaaS para gestão de eventos — cobrindo inscrições, credenciamento, agenda, networking e análise de dados — têm oportunidade crescente num setor que emergiu da pandemia transformado digitalmente.",
    sections=[
        ("O Mercado de EventTech SaaS",
         "O mercado de SaaS para eventos é segmentado por tipo de evento: eventos corporativos (conferências, congressos, treinamentos, kick-offs — B2B com foco em networking e aprendizado), eventos de entretenimento e cultura (shows, festivais, exposições — B2C com foco em experiência e ticketing), feiras e exposições comerciais (eventos de negócios com expositores — gestão de estandes, credenciamento e matchmaking), e eventos virtuais e híbridos (plataformas de streaming com interação — boom durante a pandemia, com consolidação pós-pandemia no modelo híbrido). As funcionalidades cobertas incluem: inscrição e pagamento online (landing page do evento, formulário de inscrição, processamento de pagamento, emissão de nota fiscal), credenciamento digital (check-in por QR code ou biometria na entrada), agenda e programação (app do evento com grade de palestras, mapa do local, palestrantes), matchmaking e networking (algoritmo que sugere conexões relevantes entre participantes com base no perfil), e analytics pós-evento (taxa de presença, engajamento, sessões mais acessadas, NPS dos participantes)."),
        ("Inscrição e Pagamento: O Módulo de Entrada",
         "A plataforma de inscrição de eventos é frequentemente o primeiro ponto de contato do organizador com a tecnologia de eventos. Funcionalidades críticas incluem: formulários de inscrição personalizáveis (campos obrigatórios e opcionais, validação de CNPJ para inscrições corporativas, upload de comprovante de pagamento), múltiplas categorias de ingresso (lote 1, lote 2, VIP, grupo, cortesia — com controle de quantidade disponível por categoria), pagamento por múltiplos meios (Pix, cartão de crédito parcelado, boleto, transferência bancária para eventos grandes), emissão automática de NF-e de serviço (a nota fiscal eletrônica é obrigatória e frequentemente exigida pelo participante para reembolso corporativo), e integração com CRM para nutrição de leads pré-evento. Plataformas como Sympla, Eventbrite e Even3 dominam o mercado brasileiro de inscrição de eventos — a diferenciação ocorre em funcionalidades verticais (eventos acadêmicos, eventos corporativos enterprise)."),
        ("Credenciamento Digital: A Primeira Impressão do Evento",
         "O credenciamento — o processo de identificar e receber os participantes na entrada do evento — é onde a experiência do participante começa e onde a primeira impressão é formada. Uma fila de 200 pessoas esperando 45 minutos para pegar um crachá já destrói a experiência antes do evento começar. Plataformas de credenciamento digital permitem: check-in por QR code do ingresso (o participante apresenta o celular e o crachá é impresso em segundos), credenciamento facial (câmera reconhece o participante cadastrado e libera acesso sem precisar tirar o celular do bolso), credenciamento descentralizado (múltiplos pontos de check-in simultâneos com sincronização em nuvem em tempo real — sem fila), e relatório de presença em tempo real para o organizador (saber quantas pessoas chegaram, quais ainda não vieram, qual a taxa de presença por categoria). Para eventos de 500+ participantes, o credenciamento digital se paga pelo tempo economizado na operação e pela experiência positiva gerada."),
        ("Eventos Híbridos: O Novo Normal Pós-Pandemia",
         "O evento híbrido — que combina participantes presenciais com participantes online em tempo real — emergiu da pandemia como formato estabelecido que veio para ficar. A plateia online pode ser de colaboradores de filiais remotas, de participantes internacionais que não viajam, ou de pessoas que preferem o formato digital. Os desafios técnicos do evento híbrido incluem: qualidade de áudio e vídeo para a plateia online (câmera dedicada ao palco, microfone de qualidade, link de internet redundante), engajamento da plateia online (polling, Q&A ao vivo, chat moderado — a plateia online que só assiste sem interagir desengaja em 20 minutos), e sincronização das experiências presencial e online (o apresentador precisa fazer contato visual com as câmeras para a plateia online, não apenas com o auditório). Plataformas como Hopin, Zoom Events e StreamYard — e nacionais como Sympla Online e Streabox — supriram essa demanda. O organizador que oferece opção híbrida de forma natural aumenta o alcance do evento sem o custo adicional de um evento separado online."),
        ("Métricas de Saúde do EventTech SaaS",
         "As métricas de produto incluem: eventos ativos gerenciados na plataforma por mês, participantes credenciados (o volume que valida a escala), e NPS dos organizadores. As métricas de negócio incluem: MRR com modelo de assinatura por organizador (R$200 a R$2.000/mês para acesso à plataforma) mais take rate por ingresso vendido (R$1 a R$5 por ingresso ou 1-3% do valor), GMV de ingressos processados (métrica de escala), churn sazonal (organizadores que fazem eventos pontuais podem cancelar entre eventos — modelo de assinatura annual reduz esse churn), e NRR via expansão de participantes (organizações que crescem seus eventos expandem naturalmente o volume e o gasto na plataforma).")
    ],
    faq_list=[
        ("Qual a diferença entre Sympla, Eventbrite e Even3?",
         "As três plataformas têm posicionamentos distintos no mercado brasileiro. Sympla é a maior plataforma de eventos do Brasil, com foco em eventos culturais, shows, teatro e eventos corporativos de médio porte — tem alta base de usuários consumidores finais e boa distribuição. Eventbrite é a plataforma americana com presença global, forte em eventos internacionais e em profissionais que organizam eventos em múltiplos países — interface em inglês com suporte a múltiplas moedas. Even3 é especializada em eventos acadêmicos e científicos — com funcionalidades específicas para submissão e revisão de artigos, emissão de certificados acadêmicos, e integração com sistemas universitários. Para um congresso médico ou científico, Even3 tem vantagem clara. Para um festival cultural ou show, Sympla é o padrão. Para uma conferência corporativa internacional, Eventbrite ou plataformas enterprise como Cvent são mais adequadas."),
        ("Quanto custa organizar um evento corporativo com plataforma de gestão?",
         "O custo da plataforma de gestão de eventos corporativos varia pelo modelo de negócio: plataformas de inscrição cobram taxa por ingresso (R$1,50 a R$5 por participante + taxa de processamento de pagamento de 2% a 5% do valor do ingresso). Para eventos gratuitos, algumas plataformas cobram mensalidade pelo acesso. Plataformas completas de gestão de eventos (inscrição + credenciamento + app + analytics) para eventos corporativos cobram de R$500 a R$5.000 por evento ou assinatura mensal de R$500 a R$3.000. O retorno sobre o investimento na plataforma é calculado pelo tempo economizado (operação de inscrição manual, planilha de participantes, crachás impressos um a um) e pela qualidade da experiência que gera NPS alto. Para eventos acima de 100 participantes, a plataforma se paga operacionalmente. Para eventos enterprise acima de 500 participantes, a plataforma é indispensável."),
        ("Evento online tem o mesmo engajamento que presencial?",
         "Não — eventos online têm sistematicamente menor engajamento do que presenciais, especialmente para networking e conexões informais. A razão é que o valor dos eventos vai além do conteúdo das palestras — está nas conversas de corredor, nos almoços entre sessões, no encontro fortuito com um cliente potencial. Plataformas de networking online (que simulam os lounges virtuais, as mesas redondas e o matchmaking) melhoraram o engajamento, mas ainda não replicam a densidade de interação humana do presencial. Eventos online têm vantagens importantes: custo muito menor (sem venue, sem catering, sem viagem), alcance global (participantes de qualquer lugar do mundo), e dados ricos de engajamento (quem assistiu o quê, por quanto tempo, clicou em quais links). A estratégia ideal é usar o online para alcance e escala, e o presencial para profundidade de relacionamento — daí o crescimento do modelo híbrido.")
    ]
)

# Article 4736 — Clinic: Psychiatry and adult mental health
art(
    slug="gestao-de-clinicas-de-psiquiatria-e-saude-mental-adulto",
    title="Gestão de Clínicas de Psiquiatria e Saúde Mental Adulto",
    desc="Guia de gestão para clínicas de psiquiatria: fluxo de atendimento, manejo de transtornos do humor e ansiedade, prescrição segura de psicotrópicos e indicadores de qualidade.",
    h1="Gestão de Clínicas de Psiquiatria e Saúde Mental Adulto",
    lead="A saúde mental é a segunda maior causa de incapacidade no mundo. No Brasil, mais de 23 milhões de pessoas sofrem de depressão e 18 milhões de transtorno de ansiedade. Clínicas de psiquiatria atendem uma demanda crescente e subatendida — com apenas 3 psiquiatras por 100 mil habitantes no Brasil, muito abaixo da média mundial.",
    sections=[
        ("O Escopo da Psiquiatria Clínica",
         "A psiquiatria clínica abrange: transtornos do humor (depressão maior, transtorno bipolar — diagnóstico, farmacoterapia, psicoeducação), transtornos de ansiedade (transtorno de ansiedade generalizada, pânico, fobia social, TOC, PTSD), transtornos psicóticos (esquizofrenia, transtorno esquizoafetivo — estabilização e prevenção de recaídas), transtornos de personalidade (especialmente TPB — terapia dialético-comportamental em parceria com psicólogo), TDAH no adulto (diagnóstico tardio frequente, farmacoterapia com metilfenidato e lisdexanfetamina), transtornos relacionados ao uso de substâncias (álcool, crack, benzodiazepínicos — tratamento da dependência e da comorbidade psiquiátrica), e psiquiatria do sono (insônia crônica, hipersonia, parassonias). O psiquiatra é o único profissional que pode prescrever medicamentos psicotrópicos — o que torna a consulta psiquiátrica indispensável para o tratamento medicamentoso dos transtornos mentais."),
        ("Prescrição de Psicotrópicos: Regulação e Receituário Especial",
         "A prescrição de medicamentos psicotrópicos no Brasil é regulada pela Portaria SVS/MS 344/1998 e suas atualizações — que classifica os psicotrópicos em listas (A1, A2, A3, B1, B2, C1, C2, C3, C4, C5) com requisitos específicos de receituário. Antidepressivos (fluoxetina, sertralina, escitalopram) e antipsicóticos de segunda geração (quetiapina, olanzapina, aripiprazol) requerem receituário de controle especial azul (dois vias). Benzodiazepínicos (clonazepam, alprazolam, diazepam) requerem receituário de controle especial amarelo (notificação de receita — com prazo máximo de 30 dias). Estimulantes (metilfenidato, lisdexanfetamina para TDAH) requerem receituário de controle especial amarelo com validade de 30 dias. A gestão correta do receituário especial — com registro do receituário no SNGPC e cópia retida na clínica por 3 anos — é obrigação legal que o sistema de prontuário eletrônico deve suportar."),
        ("Integração Psiquiatria e Psicologia: Modelo de Maior Eficácia",
         "O modelo de tratamento de maior eficácia em saúde mental combina farmacoterapia (psiquiatra) e psicoterapia (psicólogo) — especialmente para depressão, ansiedade e transtorno bipolar. A integração real — não apenas o encaminhamento — exige: comunicação regular entre psiquiatra e psicólogo sobre o mesmo paciente (reuniões de caso, prontuário compartilhado), alinhamento do plano de tratamento (a medicação suporta a psicoterapia — reduzindo a sintomatologia suficientemente para o paciente conseguir engajar no processo terapêutico), e educação do paciente sobre o papel de cada intervenção. Clínicas de saúde mental que têm psiquiatra e psicólogo no mesmo espaço — com prontuário integrado e reuniões de equipe — entregam qualidade assistencial superior e têm maior retenção de pacientes do que modelos de encaminhamento sem integração. O modelo colaborativo também permite capturar o paciente complexo que precisaria de dois consultórios em locais diferentes."),
        ("Telepsiquiatria: Ampliando o Alcance em Mercado Escasso",
         "A telepsiquiatria — consultas psiquiátricas por videoconferência — é uma das aplicações de maior impacto da telemedicina no Brasil: a distribuição de psiquiatras é concentrada em capitais (São Paulo e Rio de Janeiro têm mais de 40% dos psiquiatras do país), enquanto a demanda por saúde mental é distribuída por todo o território. A telepsiquiatria permite que um psiquiatra em São Paulo atenda pacientes em cidades do interior sem psiquiatra na rede pública ou privada. O CFM regulamentou a telemedicina pelo CFM 2.314/2022 — que permite consultas online desde que o paciente não seja visto pela primeira vez em teleconsulta (para estabelecimento do vínculo terapêutico). Na prática, a maioria das clínicas de psiquiatria usa o modelo híbrido: primeira consulta presencial e retornos online — com excelente aceitação pelos pacientes. A telepsiquiatria aumenta a capacidade de atendimento do psiquiatra sem custo adicional de espaço físico."),
        ("Indicadores de Qualidade em Psiquiatria",
         "As métricas clínicas incluem: taxa de remissão de depressão na carteira de pacientes (usando escala PHQ-9 — meta de redução de 50% do escore em 8 semanas de tratamento), taxa de hospitalização psiquiátrica de pacientes em acompanhamento ambulatorial (indicador de efetividade do manejo ambulatorial — hospitalização deve ser evento de exceção, não de rotina), taxa de adesão à medicação (paciente que não toma a medicação não melhora — o follow-up ativo da adesão é intervenção clínica relevante), e NPS dos pacientes. As métricas de negócio incluem: taxa de retorno no intervalo correto (paciente com depressão deve retornar em 2-4 semanas no início do tratamento — retorno em dia indica manejo ativo), tempo de espera para primeira consulta (a demanda por psiquiatria supera amplamente a oferta — tempo de espera longo é gargalo de acesso), e mix de atendimento presencial vs. teleconsulta (indicador de eficiência operacional do psiquiatra).")
    ],
    faq_list=[
        ("Como saber se preciso de psiquiatra ou psicólogo?",
         "A regra prática mais simples: se os sintomas são intensos, limitam significativamente a vida diária ou o trabalho, ou se você suspeita que pode ser beneficiado por medicação — procure um psiquiatra. Se os sintomas são mais leves, relacionados a conflitos relacionais, autoconhecimento ou dificuldades de adaptação — o psicólogo é o ponto de entrada mais adequado. Na prática, os dois profissionais se complementam: para depressão moderada a grave, o tratamento mais eficaz combina medicação (psiquiatra) e psicoterapia (psicólogo). Para ansiedade leve a moderada, a TCC com psicólogo frequentemente é suficiente sem medicação. Para transtornos como esquizofrenia, transtorno bipolar e TDAH, o psiquiatra é indispensável para o diagnóstico e a farmacoterapia. O caminho prático é: se em dúvida, comece pelo psicólogo — que pode avaliar se há necessidade de encaminhamento ao psiquiatra."),
        ("Antidepressivos causam dependência?",
         "Não — antidepressivos não causam dependência no sentido farmacológico (não há tolerância crescente que exija doses cada vez maiores, nem comportamento de busca compulsiva pelo medicamento). O que pode ocorrer é síndrome de descontinuação ao suspender abruptamente alguns antidepressivos (especialmente paroxetina e venlafaxina) — com sintomas como tontura, náusea, sensação de choque elétrico, irritabilidade. Esses sintomas não são abstinência de dependência, mas sim reajuste do sistema serotoninérgico à retirada do medicamento. A suspensão gradual orientada pelo psiquiatra (desmame lento ao longo de semanas) previne a síndrome de descontinuação. A confusão com dependência vem parcialmente do fato de que muitos pacientes precisam tomar antidepressivos por períodos longos (1 a 3 anos, ou indefinidamente em casos recorrentes) — mas isso reflete a cronicidade da doença, não a dependência do medicamento."),
        ("TDAH no adulto: como é o diagnóstico e tratamento?",
         "O TDAH no adulto é frequentemente subdiagnosticado — muitos adultos chegam ao psiquiatra na faixa dos 30-40 anos com histórico de 'desorganização', dificuldade de terminar tarefas, procrastinação e problemas de relacionamento sem saber que têm TDAH. O diagnóstico é clínico: entrevista detalhada sobre sintomas na infância e na vida adulta, escalas de autorrelato (ASRS — Adult ADHD Self-Report Scale), e quando possível relato de familiar ou parceiro. A avaliação neuropsicológica complementa o diagnóstico em casos complexos. O tratamento inclui farmacoterapia (metilfenidato — Ritalina, Concerta; ou lisdexanfetamina — Vyvanse — que são estimulantes do SNC; ou atomoxetina para casos com contraindicação a estimulantes) e intervenção comportamental (psicoterapia focada em organização, manejo do tempo e estratégias de compensação). No adulto, o TDAH raramente apresenta a hiperatividade motora da infância — predominam desatenção, impulsividade e disfunção executiva.")
    ]
)

# Article 4737 — SaaS sales: Food industry and food tech
art(
    slug="vendas-para-o-setor-de-saas-de-industria-alimenticia-e-food-tech",
    title="Vendas para o Setor de SaaS de Indústria Alimentícia e Food Tech",
    desc="Estratégias de vendas B2B para plataformas SaaS voltadas à indústria alimentícia e food tech: como abordar fábricas de alimentos, cooperativas e startups de food tech.",
    h1="Vendas para o Setor de SaaS de Indústria Alimentícia e Food Tech",
    lead="A indústria alimentícia brasileira fatura R$800 bilhões por ano e é a maior do hemisfério sul. Plataformas SaaS para esse setor cobrem gestão de produção, rastreabilidade de lote, controle de qualidade e conformidade com ANVISA — um mercado de alta regulação, cadeia complexa e digitalização crescente.",
    sections=[
        ("O Mercado de FoodTech SaaS B2B",
         "O mercado de SaaS para a cadeia alimentícia inclui: MES (Manufacturing Execution System — controle de produção em tempo real na fábrica de alimentos), rastreabilidade de lote (da matéria-prima ao produto final no varejo — exigência crescente de varejistas e reguladores), controle de qualidade e APPCC (Análise de Perigos e Pontos Críticos de Controle — obrigatório para indústrias que exportam e recomendado para todas), gestão de fornecedores de insumos alimentícios (qualificação, auditorias, laudos de qualidade), rotulagem e conformidade com ANVISA (cálculo nutricional, lista de ingredientes, alergênicos — que mudaram pela RDC ANVISA 429/2020 com os novos padrões de rotulagem), e food delivery e gestão de cozinha industrial (dark kitchens, catering e food service em escala). O setor de alimentos tem particularidades que diferenciam o SaaS alimentício do industrial genérico: perecibilidade (gestão de FEFO — First Expired First Out), sazonalidade de insumos (preço de grãos e proteínas varia significativamente), e alta regulação sanitária."),
        ("O Decisor na Indústria Alimentícia",
         "O decisor em fábricas de alimentos de médio porte é o diretor industrial ou de operações — com influência do gestor de qualidade (que tem veto técnico em qualquer sistema que toque no controle de qualidade e rastreabilidade). Em cooperativas agroindustriais (Frimesa, Coamo, Castrolanda), o decisor é o gerente de tecnologia ou o gerente industrial — com ciclo de decisão mais longo e processo de aprovação coletivo. Em startups de food tech (que geralmente escalam rapidamente), o decisor é o CEO ou o head de operações — com maior agilidade de decisão. O gestor de qualidade e segurança dos alimentos (GQSA) é o influenciador mais crítico: qualquer sistema que toque em APPCC, rastreabilidade ou controle microbiológico passa pela sua avaliação técnica. A certificação do sistema (FSSC 22000, ISO 22000, BRC — que os grandes varejistas exigem de fornecedores) é argumento técnico de alto peso."),
        ("Rastreabilidade Alimentar: Requisito de Acesso ao Mercado",
         "A rastreabilidade de lote — capacidade de rastrear cada lote de produto acabado até suas matérias-primas de origem, e de identificar onde cada lote foi distribuído — é um requisito crescente de acesso a mercados relevantes. O GS1 Brasil (organização responsável pelos padrões de código de barras e rastreabilidade) define os padrões de rastreabilidade para a cadeia alimentícia. Para exportação à União Europeia, o regulamento EU 178/2002 obriga rastreabilidade um passo para frente (onde foi o produto) e um passo para trás (de onde vieram os insumos). Grandes varejistas como Carrefour, Walmart e Pão de Açúcar exigem rastreabilidade de seus fornecedores como condição de cadastro. Para proteínas animais (carne, leite, ovos), a rastreabilidade é obrigatória para exportação e altamente recomendada no mercado interno. Plataformas SaaS que geram o GS1 Digital Link e a documentação de rastreabilidade automaticamente a partir do MES têm argumento regulatório e comercial concreto."),
        ("APPCC e Controle de Qualidade: Conformidade como Diferencial",
         "O APPCC (Análise de Perigos e Pontos Críticos de Controle — ou HACCP em inglês) é o sistema de controle de qualidade e segurança dos alimentos que identifica os pontos da cadeia de produção onde um perigo (biológico, químico ou físico) pode ocorrer e define as medidas de controle. É obrigatório para estabelecimentos que exportam e recomendado pela ANVISA para todos os estabelecimentos de produção de alimentos. Plataformas de gestão de qualidade alimentar digitalizam o APPCC: planos de controle com pontos críticos registrados em sistema, monitoramento em tempo real (temperatura de pasteurização, pH de conservas, atividade de água — com alerta quando parâmetros saem da faixa), registros de verificação e validação, e gestão de não conformidades com rastreabilidade até o lote afetado. A auditoria de clientes corporativos e de certificadoras (BVQI, Bureau Veritas, SGS) que exigem evidência do APPCC em operação se torna muito mais ágil quando os registros estão digitalizados e acessíveis em tempo real."),
        ("Métricas de Saúde do FoodTech SaaS",
         "As métricas de produto incluem: lotes de produção rastreados por mês (volume que cresce com a escala da operação), registros de controle de qualidade digitalizados (indicador de adoção real do sistema vs. papel paralelo), e NPS do gestor industrial e do gestor de qualidade. As métricas de negócio incluem: MRR por porte de fábrica (micro e pequenas indústrias de alimentos têm ticket de R$300 a R$800/mês; médias e grandes têm ticket de R$2.000 a R$20.000/mês para soluções MES e rastreabilidade completas), churn por perda de cliente devido a fechamento de fábrica ou aquisição por grupo maior com sistema próprio, e CAC por canal (ABIA — Associação Brasileira da Indústria de Alimentos, ABIC, feiras como FISPAL Tecnologia e Anuga são canais de acesso ao decisor do setor).")
    ],
    faq_list=[
        ("O que é APPCC e por que é importante para a indústria alimentícia?",
         "APPCC (Análise de Perigos e Pontos Críticos de Controle) é um sistema preventivo de gestão de segurança dos alimentos — que identifica, avalia e controla os perigos significativos à segurança do alimento ao longo da cadeia produtiva. Os sete princípios do APPCC incluem: identificação dos perigos potenciais (biológicos — bactérias, vírus, parasitas; químicos — pesticidas, metais pesados, alérgenos; físicos — fragmentos de metal, vidro, osso), determinação dos Pontos Críticos de Controle (PCC — pontos onde o perigo pode ser prevenido, eliminado ou reduzido a níveis aceitáveis), estabelecimento de limites críticos (temperatura mínima de pasteurização, pH máximo de conservas), monitoramento contínuo dos PCCs, ações corretivas quando um PCC estiver fora do limite, verificação do sistema, e documentação e registro. O APPCC é exigido pela ANVISA para exportação e por grandes varejistas como condição de fornecimento — sendo fundamento para certificações internacionais como FSSC 22000 e BRC."),
        ("Rotulagem de alimentos mudou com a nova resolução ANVISA?",
         "Sim — a ANVISA publicou a RDC 429/2020 (informação nutricional frontal) e a IN 75/2020 (atualização dos critérios de rotulagem) que introduziram mudanças significativas na rotulagem de alimentos industrializados. As principais mudanças incluem: lupa frontal obrigatória para alimentos com altos teores de açúcar adicionado, gordura saturada ou sódio — facilitando a identificação pelo consumidor de produtos ultraprocessados; lista de ingredientes com tamanho mínimo de fonte e destaque dos alérgenos (negrito obrigatório para 17 alérgenos prioritários — glúten, amendoim, leite, ovo, nozes, entre outros); e nova tabela de informação nutricional com porções baseadas em medidas caseiras. As empresas de alimentos tiveram prazo de adequação até 2023-2024 conforme o porte. Plataformas de gestão de rotulagem que automatizam o cálculo nutricional e verificam a conformidade com a RDC 429/2020 e a IN 75/2020 reduziram significativamente o trabalho manual e o risco de não conformidade."),
        ("Dark kitchen é um bom modelo de negócio para food tech?",
         "Dark kitchen (cozinha fantasma — que produz exclusivamente para delivery, sem salão de atendimento ao público) é um modelo de negócio com vantagens e riscos específicos. As vantagens incluem: custo de instalação muito menor que um restaurante tradicional (sem salão, sem fachada em localização premium), capacidade de operar múltiplas marcas de uma mesma cozinha (o mesmo espaço produz hambúrgueres, pizzas e saladas para diferentes marcas no iFood), e escalabilidade mais fácil (abrir uma nova unidade em um galpão é mais rápido que abrir um restaurante). Os riscos incluem: alta dependência das plataformas de delivery (iFood, Rappi — que cobram de 12% a 30% de comissão sobre o pedido), ausência de marca física (o cliente nunca vê a cozinha — construir lealdade de marca é mais difícil), e ambiente altamente competitivo (qualquer um pode abrir uma dark kitchen, com barreira de entrada baixa). Plataformas SaaS para dark kitchens que integram múltiplos marketplaces de delivery, gerenciam o estoque de múltiplas marcas e otimizam a sequência de preparo dos pedidos são infraestrutura crítica para esse modelo.")
    ]
)

# Article 4738 — Consulting: Sales management and sales force
art(
    slug="consultoria-de-gestao-de-vendas-e-forca-de-vendas",
    title="Consultoria de Gestão de Vendas e Força de Vendas",
    desc="Como funciona a consultoria de gestão de vendas: estruturação da força de vendas, metodologias de venda, gestão de pipeline, incentivos e métricas de desempenho comercial.",
    h1="Consultoria de Gestão de Vendas e Força de Vendas",
    lead="Vendas é a função de negócio que mais diretamente converte esforço em receita. Consultoria de gestão de vendas ajuda empresas a estruturar processos que transformam bons produtos em crescimento consistente — desde a definição do ICP e do processo de vendas até a gestão de pipeline, o recrutamento de vendedores e os incentivos que sustentam a performance.",
    sections=[
        ("O que é Consultoria de Gestão de Vendas",
         "A consultoria de gestão de vendas atua em: estratégia de go-to-market (quais segmentos atacar, qual o perfil de cliente ideal — ICP, qual o modelo de vendas — inside sales, field sales, channel, self-serve), estruturação do processo de vendas (funil de vendas com etapas e critérios de avanço claros — do primeiro contato ao fechamento e ao onboarding), criação de playbook de vendas (scripts, objeções e respostas, perguntas de qualificação — BANT, MEDDIC, SPIN — materiais de suporte para cada etapa), gestão de pipeline e forecast (metodologia de previsão de receita a partir do pipeline — que o CEO e o board esperam), estrutura de compensação e incentivos (salário, comissão, acelerador, MBO — que a estrutura de incentivos certa atrai os vendedores certos e mantém a performance), e recrutamento e desenvolvimento de equipe de vendas (perfil ideal por papel — SDR, AE, CSM, Sales Manager)."),
        ("ICP e Segmentação: Onde Concentrar o Esforço Comercial",
         "O ICP (Ideal Customer Profile — Perfil de Cliente Ideal) é a definição das características que tornam um cliente o melhor cliente possível: aquele que tem o problema que o produto resolve, a capacidade de pagar, a urgência de comprar, e o potencial de expansão e referência. A consultoria de vendas que começa pelo ICP evita um erro clássico: vender para todo mundo e não vender bem para ninguém. Os atributos do ICP incluem dimensões firmográficas (tamanho de empresa, setor, faturamento, localização, número de funcionários), dimensões de comportamento (adota tecnologia early, tem orçamento alocado para a solução, tem um responsável designado para o problema que o produto resolve), e dimensões de situação (está em crescimento acelerado, passou por um evento trigger — expansão, contratação de novo líder, problema recente). Uma vez definido o ICP, o time de marketing pode gerar leads qualificados e o time de vendas pode priorizar o tempo nos prospects de maior probabilidade de conversão."),
        ("Processo de Vendas: Do Caos ao Método",
         "Empresas sem processo de vendas documentado têm resultados que dependem do talento individual de cada vendedor — o que cria inconsistência e torna impossível escalar. Um processo de vendas bem estruturado define: as etapas do funil (Prospect → Qualificado → Demo → Proposta → Negociação → Fechado Ganho/Perdido), os critérios de avanço de etapa (o que precisa acontecer para o prospect avançar de Demo para Proposta?), as atividades esperadas em cada etapa (quantas ligações, qual o conteúdo do e-mail de follow-up, quando escalar para o gerente), o tempo máximo em cada etapa antes de escalar ou perder (uma oportunidade que fica 60 dias em 'Proposta Enviada' sem resposta é provavelmente perdida — o CRM deve alertar), e as métricas de conversão por etapa (taxas de conversão de etapa que revelam onde o funil está vazando). Um processo bem documentado permite que o VP de Vendas identifique onde treinar, onde contratar e onde remover obstáculos."),
        ("Compensação de Vendas: Desenhando o Plano que Gera Performance",
         "O plano de compensação de vendas é o mecanismo mais poderoso de alinhamento de comportamento da equipe comercial. Os componentes incluem: salário fixo (base — que atrai o perfil e cobre o mínimo de subsistência), comissão variável (percentual da receita fechada — que alinha o vendedor com o resultado), acelerador (taxa de comissão mais alta para receita acima da cota — que incentiva superar a meta), quota de recuperação (a comissão começa a pagar apenas após atingir X% da cota — que evita que vendedores acomodem em metas fáceis), e MBO (Management by Objectives — bônus por objetivos além da receita — adoção de novos produtos, expansão de contas, indicadores de qualidade). Os erros mais comuns em planos de compensação incluem: comissão sobre receita bruta sem desconto de custo de aquisição (incentiva fechamentos caros que destroem margem), cota não alcançável (desmotiva o time inteiro quando apenas 20% batem a meta), e plano que muda frequentemente (destrói a confiança do time de vendas na empresa)."),
        ("Métricas de Vendas: O Dashboard que o CEO Precisa Ver",
         "As métricas de vendas são divididas em: métricas de atividade (ligações realizadas, e-mails enviados, demos agendadas — indicadores leading que preveem o resultado futuro), métricas de pipeline (número e valor de oportunidades por etapa, velocidade de avanço, taxa de conversão por etapa — que identifica gargalos), métricas de resultado (ARR adicionado, novos logotipos, ACV — Average Contract Value, win rate, quota attainment — os indicadores lagging que medem o resultado), e métricas de eficiência (CAC, CAC payback, receita por vendedor, ciclo de venda médio). O forecast de receita — a previsão de quanto vai fechar no trimestre — é o número mais crítico para o CEO e o board: é calculado multiplicando o valor de cada oportunidade no pipeline pela probabilidade de fechamento estimada em cada etapa. Uma cultura de forecast rigoroso — onde os vendedores são responsáveis por suas previsões — é construída ao longo do tempo com disciplina de pipeline review semanal.")
    ],
    faq_list=[
        ("Inside sales vs. field sales: qual modelo escolher?",
         "A escolha depende do ticket médio, da complexidade da venda e do mercado-alvo. Field sales (vendas presenciais — o vendedor visita o cliente) é adequado para tickets altos (acima de R$50 mil/ano), vendas consultivas de alta complexidade (ERP enterprise, plataformas industriais), e setores onde o relacionamento presencial é cultural (agronegócio, saúde, construção). O custo é alto — vendedor de field sales com despesas de viagem custa de R$180 mil a R$400 mil/ano fully loaded. Inside sales (vendas remotas por telefone, videoconferência — o vendedor nunca visita o cliente) é adequado para tickets médios (R$5 mil a R$100 mil/ano), produtos SaaS B2B, e compradores tech-friendly que aceitam fazer negócio remotamente. O custo é muito menor — SDR + AE (Account Executive) de inside sales custa de R$80 mil a R$200 mil/ano. A tendência pós-pandemia é de inside sales como padrão mesmo para tickets médios-altos — com visita presencial reservada para os deals mais complexos e para o relacionamento de contas estratégicas."),
        ("O que é SPIN Selling e como aplicar?",
         "SPIN Selling é uma metodologia de vendas desenvolvida por Neil Rackham com base em pesquisa de 12 anos analisando 35 mil chamadas de venda. O SPIN é um acrônimo para os quatro tipos de perguntas que os vendedores de sucesso fazem: Situação (entender o contexto do cliente — 'Como você gerencia hoje o processo de X?'), Problema (identificar as dores — 'Quais são os maiores desafios que você enfrenta com X?'), Implicação (expandir o impacto do problema — 'Quando X falha, qual é o impacto no seu negócio? Quanto isso custa?'), e Necessidade de solução (fazer o cliente articular o que ele precisa — 'O que seria ideal para resolver X?'). A lógica do SPIN é que o vendedor não vende a solução — ele faz o comprador chegar à conclusão de que precisa da solução por conta própria, o que gera muito mais comprometimento com a compra. É especialmente poderoso em vendas complexas B2B onde o cliente pode não perceber a extensão do problema até ser questionado adequadamente."),
        ("Como estruturar a gestão de pipeline de vendas?",
         "A gestão eficaz de pipeline começa pela qualidade das oportunidades que entram — não pelo acompanhamento das que já estão lá. O processo inclui: definição clara das etapas do funil com critérios objetivos de avanço (não 'parece promissor' mas 'o comprador confirmou budget e prazo'), atualização disciplinada no CRM (o vendedor atualiza o status e as próximas ações de cada oportunidade após cada contato — não na véspera da reunião de pipeline review), pipeline review semanal com o gestor (revisão de cada oportunidade acima de determinado valor — com foco em 'o que precisa acontecer para avançar ou fechar?', não apenas 'como está?'), limpeza periódica do pipeline (oportunidades estagnadas por mais de 2x o ciclo médio de venda são provavelmente perdidas — tirar do pipeline ativo clarifica o forecast), e análise de cohort de oportunidades perdidas (por que perdemos? qual foi a objeção mais frequente? qual concorrente ganhou? — dados que alimentam melhoria de produto e de processo de vendas).")
    ]
)

# Article 4739 — B2B SaaS: Restaurant and food service management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-restaurantes-e-food-service",
    title="Gestão de Negócios de Empresa de B2B SaaS de Restaurantes e Food Service",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para restaurantes e food service: modelo de negócio, PDV, delivery, gestão de cardápio e métricas do setor gastronômico.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Restaurantes e Food Service",
    lead="O setor de food service brasileiro fatura R$250 bilhões por ano, com mais de 1 milhão de estabelecimentos entre restaurantes, bares, lanchonetes e cozinhas industriais. Plataformas SaaS para esse setor — PDV, gestão de cardápio, delivery e controle de custos — são infraestrutura operacional crítica para um mercado que emergiu da pandemia ainda mais dependente de tecnologia.",
    sections=[
        ("O Mercado de RestaurantTech SaaS",
         "O mercado de SaaS para restaurantes é segmentado por tipo de operação: restaurantes à la carte (full service — garçom, cardápio impresso ou digital, comanda eletrônica), fast food e quick service (QSR — pedido no balcão ou totem, velocidade como prioridade), dark kitchens (exclusivamente delivery), cafeterias e padarias (alta rotatividade, mix de produtos alimentícios e bebidas), e redes e franquias de food service (McDonald's, Outback, Subway — com ERP próprio ou plataformas enterprise). As funcionalidades cobertas incluem: PDV (Ponto de Venda — caixa, gestão de mesas, comanda eletrônica, integração com impressoras de cozinha), cardápio digital (QR code na mesa, atualização em tempo real, fotos e descrições), delivery integrado (integração com iFood, Rappi, Uber Eats — recebimento e confirmação de pedidos em um único tablet), controle de estoque e CMV (Custo de Mercadoria Vendida — o indicador financeiro mais crítico em restaurante), e financeiro (caixa, DRE, gestão de fornecedores). O ticket médio varia de R$100 a R$800/mês dependendo do porte e dos módulos."),
        ("PDV e Comanda Eletrônica: A Espinha Dorsal da Operação",
         "O PDV (Ponto de Venda) integrado com comanda eletrônica é a funcionalidade mais crítica para a operação do restaurante: o garçom ou atendente registra o pedido no tablet ou celular, a comanda é enviada automaticamente para a impressora da cozinha (elimina o risco de perda de comanda de papel e a corrida do garçom à cozinha), o caixa vê os pedidos de todas as mesas em tempo real, e o cliente pede a conta a qualquer momento sem esperar o garçom. A integração com a balança de pesagem (para restaurantes por quilo), com o sistema de senhas (fast food — o cliente recebe um número e é chamado quando o pedido fica pronto), e com o SAT fiscal ou NFC-e (emissão do cupom fiscal obrigatório) completa o fluxo operacional do PDV. Restaurantes que usam comanda eletrônica reportam redução de erros de pedido acima de 80% e aumento da rotatividade de mesa em 15 a 25% pela agilidade no processo."),
        ("Integração com iFood e Delivery: Gestão Multichannel",
         "O delivery representa de 30% a 60% do faturamento de muitos restaurantes urbanos — e gerenciar pedidos de múltiplas plataformas (iFood, Rappi, Uber Eats, delivery próprio) simultaneamente é um dos maiores desafios operacionais. Cada plataforma tem seu próprio tablet, que toca separadamente quando chega um pedido — a cozinha fica inundada de tablets. Plataformas de integração de delivery (como Goomer, Anota AI, e módulos de delivery dos principais PDVs de restaurante) centralizam os pedidos de todos os canais em um único sistema: um pedido no iFood aparece na mesma tela do pedido no balcão, com envio automático para a impressora de cozinha, gestão de tempo de preparo e confirmação de aceite automático. A integração com delivery reduz o tempo de resposta ao pedido (aceitação manual levava de 2 a 10 minutos — automática é instantânea) e elimina os pedidos esquecidos em tablet desligado."),
        ("Controle de CMV: O Número que Define a Rentabilidade",
         "O CMV (Custo de Mercadoria Vendida) é o indicador financeiro mais crítico em restaurante: representa o percentual da receita gasto com insumos (alimentos, bebidas, embalagens). O CMV saudável varia por tipo de operação: restaurante à la carte (25% a 35%), pizzaria (30% a 40%), lanchonete e fast food (25% a 35%), bar (20% a 30%). Restaurantes com CMV acima de 40% geralmente não têm margem para cobrir os outros custos (mão de obra, aluguel, energia) — e fecham. O controle do CMV exige: ficha técnica de cada prato (a receita com ingredientes, quantidades e custo por porção), controle de estoque de insumos (entradas, saídas, saldo físico vs. saldo teórico — a diferença é o desperdício e o desvio), e comparação do CMV realizado vs. teórico (se a ficha técnica diz que o hambúrguer custa R$8 mas o CMV real do hambúrguer é R$12, há desperdício, desvio ou erro de ficha). Plataformas que calculam o CMV automaticamente a partir das vendas e do estoque são as de maior ROI financeiro para o restauranteiro."),
        ("Métricas de Saúde do RestaurantTech SaaS",
         "As métricas de produto incluem: pedidos processados por mês na plataforma (o volume que cresce com o movimento do restaurante), integração de delivery ativa (percentual de pedidos de delivery chegando pelo sistema integrado vs. pelos tablets das plataformas), e NPS do gerente e do operador de caixa. As métricas de negócio incluem: MRR por tipo de estabelecimento (restaurante full service tem ticket maior que lanchonete — pela complexidade operacional), churn por fechamento de restaurante (o setor de food service tem alto turnover — 40% dos restaurantes fecham no primeiro ano — churn bruto estruturalmente alto), NRR via expansão de módulos (restaurante que começa com PDV básico e adiciona delivery integrado, controle de estoque e financeiro), e CAC por canal (distribuidores de insumos alimentícios — Makro, distribuidor regional — que visitam todos os restaurantes são canal de alto ROI).")
    ],
    faq_list=[
        ("Qual a diferença entre PDV para restaurante e PDV para varejo?",
         "PDV para restaurante tem especificidades que o PDV de varejo genérico não resolve: gestão de mesas (o produto não é vendido no balcão mas numa mesa — com número de mesa, abertura de comanda, adição de itens ao longo do tempo, divisão da conta entre os clientes), ficha técnica e CMV (o restaurante produz o produto — precisa controlar o custo dos ingredientes, não apenas o preço de venda do produto acabado), integração com impressora de cozinha (o pedido vai para a cozinha, não para o estoque), gestão de delivery com múltiplos canais, controle de balança (restaurante por quilo), e emissão de NF-e de serviço ou NFC-e (dependendo do regime tributário). PDV de varejo gerencia produtos prontos em estoque — entrada, saída, código de barras. As funcionalidades são sobrepostas mas as especificidades de restaurante exigem um sistema desenhado para o setor — PDV de varejo adaptado geralmente frustra na operação diária."),
        ("Como funciona o SAT fiscal em restaurantes?",
         "O SAT-CF-e (Sistema Autenticador e Transmissor de Cupons Fiscais Eletrônicos) é o equipamento fiscal obrigatório em São Paulo para emissão de cupom fiscal eletrônico no varejo e food service — substitui a ECF (Emissora de Cupom Fiscal — a antiga impressora fiscal). O SAT é um hardware com certificado digital que assina digitalmente cada cupom fiscal e transmite para a SEFAZ-SP. O PDV deve estar integrado com o SAT para emitir o cupom automaticamente a cada venda. Estados que não adotaram o SAT usam o NFC-e (Nota Fiscal do Consumidor Eletrônica) — sistema similar mas sem o hardware dedicado, emitido diretamente pelo sistema pelo certificado digital do CNPJ. Restaurantes que não emitem o documento fiscal estão em infração — com risco de multa e interdição pela fiscalização. O PDV para restaurante deve ter homologação para SAT (SP) e NFC-e nos demais estados."),
        ("iFood cobra quanto de comissão dos restaurantes?",
         "A comissão do iFood para restaurantes parceiros varia por plano e por modalidade de entrega: no Plano Básico (entregador do próprio restaurante), a comissão do iFood é de 12% sobre o pedido. No Plano Entrega (entregador do iFood), a comissão sobe para 23% a 27%. No Plano Entrega com destaque na plataforma, pode chegar a 27% a 30%. Além da comissão, o iFood cobra taxa de serviço ao cliente (cobrada do consumidor final, não do restaurante). Para delivery delivery próprio (com o sistema do próprio restaurante), não há comissão — mas o restaurante precisa gerenciar os entregadores e a plataforma de pedidos. A pressão das comissões do iFood levou muitos restaurantes a investir em cardápio digital próprio e delivery direto — mas a base de usuários do iFood é tão grande que abandonar a plataforma completamente resulta em perda de volume relevante. A estratégia mais comum é usar o iFood para captação de novos clientes e incentivar a fidelização via canal próprio (WhatsApp, app do restaurante).")
    ]
)

# Article 4740 — Clinic: Pulmonology and respiratory diseases
art(
    slug="gestao-de-clinicas-de-pneumologia-e-doencas-respiratorias",
    title="Gestão de Clínicas de Pneumologia e Doenças Respiratórias",
    desc="Guia de gestão para clínicas de pneumologia: fluxo de atendimento, asma e DPOC, espirometria, tabagismo e indicadores de qualidade assistencial.",
    h1="Gestão de Clínicas de Pneumologia e Doenças Respiratórias",
    lead="As doenças respiratórias são a terceira maior causa de morte no Brasil. Asma, DPOC, pneumonias, câncer de pulmão e apneia do sono afetam dezenas de milhões de brasileiros. Clínicas de pneumologia têm alta demanda e baixa oferta de especialistas — com apenas 1 pneumologista para cada 40 mil habitantes no país.",
    sections=[
        ("O Escopo da Pneumologia Clínica",
         "A pneumologia clínica abrange: asma brônquica (doença inflamatória crônica das vias aéreas — alta prevalência, 20 milhões de brasileiros; tratamento com broncodilatadores e corticoides inalatórios), DPOC (Doença Pulmonar Obstrutiva Crônica — causada principalmente pelo tabagismo; diagnóstico por espirometria; manejo de exacerbações), pneumonias (diagnóstico e tratamento — especialmente pneumonias atípicas e em imunodeprimidos que exigem avaliação especializada), doenças pulmonares intersticiais (fibrose pulmonar idiopática, sarcoidose — doenças raras de alta complexidade diagnóstica), câncer de pulmão (rastreamento em tabagistas de alto risco, diagnóstico, estadiamento — em parceria com oncologia), tabagismo (cessação do tabagismo — abordagem farmacológica e comportamental), e apneia obstrutiva do sono (diagnóstico por polissonografia, tratamento com CPAP). A espirometria — exame que avalia a função pulmonar — é o exame diagnóstico mais realizado em pneumologia e deve estar disponível na clínica."),
        ("Espirometria: O Exame Central da Pneumologia",
         "A espirometria é o exame de função pulmonar que mede os volumes e fluxos de ar nos pulmões — é ao pulmão o que o eletrocardiograma é ao coração. É essencial para: diagnóstico e estadiamento de DPOC (obstrução ao fluxo de ar irreversível — classificação GOLD), diagnóstico e monitoramento de asma (obstrução reversível com broncodilatador), avaliação de aptidão para cirurgia (em cirurgias de ressecção pulmonar), avaliação de doenças ocupacionais respiratórias, e monitoramento da progressão de doenças pulmonares crônicas. Clínicas de pneumologia com espirometria própria realizam o diagnóstico imediatamente na consulta — aumentando a eficiência clínica e o ticket por consulta. O espirômetro deve ser calibrado diariamente e os técnicos devem ser treinados para realizar o exame com qualidade adequada (o resultado depende da cooperação e do esforço do paciente — uma espirometria mal realizada é pior do que nenhuma)."),
        ("DPOC e Asma: Manejo Ambulatorial de Alto Volume",
         "Asma e DPOC são as duas condições de maior volume ambulatorial em pneumologia — e as que mais se beneficiam de acompanhamento especializado continuado. O manejo da asma inclui: classificação da gravidade (intermitente, leve persistente, moderada, grave), ajuste da farmacoterapia inalatória conforme controle (GINA guidelines), avaliação da técnica inalatória (o paciente sabe usar o inalador corretamente? — erros de técnica são comuns e comprometem o tratamento), monitoramento com pico de fluxo (PFE — avaliação domiciliar da função pulmonar), e educação do paciente (identificação e evitação de gatilhos, plano de ação para crises). O manejo do DPOC inclui: espirometria anual para monitoramento da progressão, vacinas (influenza e pneumocócica — que reduzem exacerbações), broncodilatadores de longa ação (LABA + LAMA), reabilitação pulmonar (exercício supervisionado que melhora a qualidade de vida mesmo sem mudar a espirometria), e cessação do tabagismo (a única intervenção que muda o curso natural da doença)."),
        ("Apneia do Sono: Segmento de Alta Demanda",
         "A apneia obstrutiva do sono (AOS) é altamente prevalente e subdiagnosticada — estima-se que afete 30% dos adultos brasileiros, com apenas 10% diagnosticados. Os sintomas são insidiosos: ronco alto, sonolência diurna excessiva, episódios presenciados de apneia durante o sono, cefaleia matinal. As consequências incluem: hipertensão arterial resistente (a apneia não tratada é uma das causas de hipertensão difícil de controlar), risco aumentado de infarto e AVC, síndrome metabólica, e prejuízo cognitivo e de qualidade de vida. O diagnóstico é feito pela polissonografia — exame realizado durante uma noite de sono monitorada (presencialmente em laboratório do sono ou por oximetria domiciliar para casos de menor complexidade). O tratamento padrão para AOS moderada e grave é o CPAP (aparelho que mantém pressão positiva nas vias aéreas durante o sono). Clínicas de pneumologia com laboratório do sono ou parceria com laboratório próximo capturam um volume crescente de pacientes referenciados por cardiologistas, neurologistas e clínicos gerais."),
        ("Indicadores de Qualidade em Pneumologia",
         "As métricas clínicas incluem: taxa de controle de asma na carteira de pacientes (percentual com asma bem controlada — sem crises frequentes, sem limitação de atividades — meta acima de 60% da carteira), taxa de cessação do tabagismo em pacientes participantes do programa (cessação sustentada em 12 meses — taxa média de 20% a 30% com intervenção farmacológica + comportamental), e NPS. As métricas de negócio incluem: receita por espirometria (exame de alto volume e boa margem — equipamento com baixo custo operacional após aquisição), taxa de retorno de crônicos (DPOC e asma grave retornam a cada 3 a 6 meses — receita recorrente previsível), taxa de conversão de screening de apneia para polissonografia (triagem positiva com questionário Epworth deve resultar em agendamento de polissonografia — indicador de qualidade do fluxo clínico), e tempo de espera para primeira consulta (alta demanda reprimida — pneumologistas têm agenda cheia em qualquer cidade).")
    ],
    faq_list=[
        ("Asma tem cura ou é para vida toda?",
         "A asma não tem cura no sentido de erradicação definitiva da doença — mas pode entrar em remissão completa, especialmente em crianças. Cerca de 30% a 50% das crianças com asma ficam assintomáticas na adolescência e não precisam mais de medicação. Em adultos, a asma tende a ser uma condição crônica que requer tratamento contínuo — mas com tratamento adequado, a maioria dos pacientes consegue controle completo: sem sintomas, sem crises, sem limitação de atividades. O objetivo do tratamento não é curar, mas controlar — o paciente bem controlado tem qualidade de vida igual à de quem não tem asma. O abandono do tratamento porque 'não sinto nada' é o erro mais comum — a ausência de sintomas é consequência do tratamento, não indicação para suspendê-lo."),
        ("CPAP para apneia do sono: como funciona e quem precisa?",
         "CPAP (Continuous Positive Airway Pressure) é um aparelho que sopra ar com pressão constante através de uma máscara nasal ou oronasal durante o sono — mantendo as vias aéreas superiores abertas e evitando os episódios de apneia. É o tratamento padrão para apneia obstrutiva do sono moderada (IAH — Índice de Apneia-Hipopneia entre 15 e 30 por hora) e grave (IAH acima de 30/hora), e também para casos leves com sintomas significativos (sonolência intensa, hipertensão). A adaptação ao CPAP pode levar algumas semanas — a escolha da máscara certa (nasal, oronasal, full face) e o ajuste da pressão (feito pela polissonografia de titulação ou por CPAP auto-ajustável) são fundamentais para a adesão. Pacientes que aderem ao CPAP reportam melhora dramática na qualidade de vida, na sonolência diurna, e muitas vezes na hipertensão e no perfil metabólico. A adesão ao CPAP é o maior desafio clínico do tratamento — follow-up próximo nas primeiras semanas aumenta a taxa de adesão de longo prazo."),
        ("Cigarro eletrônico (vape) causa danos pulmonares?",
         "Sim — evidências crescentes demonstram que o cigarro eletrônico (vape, pod) causa danos pulmonares reais, embora possivelmente diferentes dos do cigarro convencional. A EVALI (E-cigarette or Vaping product use-Associated Lung Injury) — lesão pulmonar aguda associada ao uso de vape — causou surtos nos EUA em 2019 com centenas de hospitalizações. O vapor gerado pelos cigarros eletrônicos contém: nicotina (altamente aditiva, com efeitos cardiovasculares), compostos orgânicos voláteis (aldeídos como acroleína e formaldeído — inflamatórios para as vias aéreas), metais pesados (cromo, níquel — dependendo do aquecedor), e glicerina e propilenoglicol (que em altas temperaturas geram compostos tóxicos). Estudos de longo prazo ainda estão em andamento, mas os dados disponíveis mostram inflamação das vias aéreas, comprometimento da função ciliar e aumento do risco de infecções respiratórias. A Anvisa proibiu a comercialização de cigarros eletrônicos no Brasil — mas a fiscalização é limitada e o uso, especialmente entre jovens, cresceu significativamente.")
    ]
)

# Article 4741 — SaaS sales: Retail and trade marketing
art(
    slug="vendas-para-o-setor-de-saas-de-varejo-e-trade-marketing",
    title="Vendas para o Setor de SaaS de Varejo e Trade Marketing",
    desc="Estratégias de vendas B2B para plataformas SaaS de varejo e trade marketing: como abordar varejistas, distribuidoras e times de campo para fechar contratos de gestão de PDV.",
    h1="Vendas para o Setor de SaaS de Varejo e Trade Marketing",
    lead="O varejo brasileiro fatura R$1,7 trilhão por ano, com mais de 1,4 milhão de pontos de venda. Plataformas SaaS para varejo e trade marketing cobrem gestão de promotores de campo, inteligência de PDV, precificação dinâmica e sell-out analytics — um mercado onde a execução no ponto de venda é a principal alavanca de crescimento.",
    sections=[
        ("O Ecossistema de RetailTech SaaS",
         "O mercado de SaaS para varejo e trade marketing inclui: plataformas de gestão de promotores de campo (agendamento de visitas, roteiro otimizado, checklist de execução — ruptura, share de gôndola, presença de preço, materiais de PDV), inteligência de PDV com visão computacional (câmeras ou foto no celular que identificam automaticamente os produtos na gôndola — share of shelf, ruptura, planograma), sistemas de precificação dinâmica (price intelligence — monitoramento de preços de concorrentes online e offline para ajuste rápido), plataformas de sell-out analytics (dados de saída real nos pontos de venda — para indústria que quer saber o que está vendendo no varejo, não apenas o que saiu do seu depósito), e sistemas de gestão de distribuidoras (pedidos, rotas de entrega, crédito, devoluções). O decisor varia por segmento: gerente de trade marketing na indústria de bens de consumo, gerente de operações na distribuidora, e diretor de expansão e operações no varejo."),
        ("Gestão de Promotores de Campo: O Maior Gargalo do Trade",
         "O promotor de campo — que visita os pontos de venda para executar o trade marketing (reposição de produto, montagem de materiais, verificação de preço, ativação de promoção) — é a força de execução do trade marketing. Gerenciar dezenas ou centenas de promotores distribuídos por um território grande é o maior desafio operacional do gerente de trade. Plataformas de força de campo digitalizam: o roteiro de visitas (definição de quais PDVs cada promotor visita em que frequência, com otimização de rota geográfica), o checklist de execução (o promotor usa o celular para registrar o que encontrou no PDV — foto de gôndola, ruptura de produto, preço praticado, material exposto), o relatório em tempo real para o gestor (ver em tempo real quais PDVs foram visitados hoje, qual a cobertura do roteiro, quais os principais problemas encontrados), e o histórico de evolução por PDV (tendências de ruptura, share de gôndola ao longo do tempo). A visibilidade em tempo real da execução de campo transforma a gestão de trade marketing de reativa para proativa."),
        ("Inteligência de PDV com IA: Visão Computacional no Varejo",
         "A visão computacional aplicada ao varejo é uma das fronteiras mais avançadas do RetailTech: câmeras fixas nas gôndolas ou fotos tiradas pelo promotor são analisadas por IA que identifica automaticamente: quais produtos estão na gôndola e em qual posição (planograma cumprido?), share of shelf de cada marca (percentual de espaço ocupado vs. concorrentes), ruptura de estoque (produto ausente na gôndola — a principal causa de perda de vendas no varejo), preço correto exposto, e materiais de PDV corretos e em boa condição. Soluções como Trigo, Daivid, e plataformas de fabricantes como Unilever e P&G internamente usam esse tipo de tecnologia para escalar a visibilidade de execução sem aumentar o número de promotores. A IA reduz o tempo de análise de foto de 5 minutos (manual) para 3 segundos (automático) — multiplicando a capacidade do gestor de trade."),
        ("Sell-Out Analytics: Do Depósito ao Consumidor Final",
         "O sell-out (venda real ao consumidor final) é a métrica mais importante para a indústria de bens de consumo — mas historicamente a mais difícil de medir. A indústria sabe quantas caixas saíram do seu depósito (sell-in), mas não sabe quantas caixas foram vendidas ao consumidor final (sell-out). O sell-out é obtido de: dados de ECF/NF-e do varejo (fornecidos por grandes redes varejistas diretamente), painéis de consumo da Nielsen e Kantar (pesquisa amostral), dados de loyalty programs dos varejistas (quando o cliente usa o cartão fidelidade — rastreamento individual), e dados de distribuidoras que compartilham o sell-out dos PDVs atendidos. Plataformas de sell-out analytics que integram essas fontes permitem à indústria: identificar regiões com baixo sell-out que indicam problema de execução (e não de demanda), correlacionar ações de trade marketing com resultado de sell-out, e tomar decisões de abastecimento baseadas em demanda real vs. estimada."),
        ("Métricas de Saúde do RetailTech SaaS",
         "As métricas de produto incluem: PDVs visitados por mês pela plataforma (a métrica de cobertura de campo), checklists de execução completados (indicador de adoção real pelo promotor), e NPS do gerente de trade marketing. As métricas de negócio incluem: MRR por número de promotores gerenciados ou PDVs monitorados, NRR via expansão de território (o cliente que cobre o Sudeste e expande para o Sul aumenta o número de PDVs e o ticket), churn por reorganização de force de campo (a indústria que terceiriza o time de promotores muda de fornecedor de serviço — impacto no SaaS atrelado), e CAC por canal (ABEVAR, eventos de trade marketing como NRF Brasil e Retail Summit são os canais de acesso ao decision-maker do setor).")
    ],
    faq_list=[
        ("O que é trade marketing e como se diferencia do marketing tradicional?",
         "Trade marketing é o conjunto de ações de marketing voltadas ao canal de distribuição (varejistas, distribuidoras, atacadistas) — em vez de ao consumidor final. O objetivo é garantir que o produto está disponível, bem posicionado, com preço correto e ativado no ponto de venda onde o consumidor decide a compra. As atividades de trade marketing incluem: gestão de espaço em gôndola (share of shelf, planograma, posição privilegiada), ativação de PDV (materiais de comunicação — stopper, wobbler, display, ponta de gôndola), promoções ao canal (bonificações por volume para varejistas e distribuidores), treinamento de equipe de vendas do varejo sobre o produto, e gestão de ruptura (garantir que o produto nunca falta na gôndola). O marketing tradicional foca em awareness e desejo do consumidor final (publicidade, redes sociais). O trade marketing garante que quando o consumidor vai ao ponto de venda para comprar, o produto está lá, visível e com o preço certo."),
        ("O que é ruptura de estoque e qual o impacto no varejo?",
         "Ruptura de estoque (out-of-stock ou OOS) ocorre quando um produto está esgotado no ponto de venda — o cliente vai à gôndola e não encontra o produto. O impacto é significativo: estudos do ECR Brasil e da Nielsen mostram que a taxa média de ruptura no varejo brasileiro é de 8% a 12% dos SKUs em qualquer momento (uma em cada 10 referências está em falta em qualquer dia). As consequências incluem: venda perdida (o consumidor não compra aquele produto naquele dia), troca de marca (38% dos consumidores compram a marca concorrente disponível — permanentemente em muitos casos), frustração do consumidor (que pode associar a falta à loja, não à indústria). Para a indústria, cada ponto percentual de redução de ruptura representa ganho direto de sell-out. Plataformas de trade marketing que identificam ruptura em tempo real (por foto do promotor ou por câmera) permitem reposição imediata — transformando ruptura de problema crônico em incidente gerenciado."),
        ("Como funciona o canal indireto (distribuidor) no varejo brasileiro?",
         "O canal indireto é a forma como a maioria das indústrias de bens de consumo acessa o varejo no Brasil: a indústria vende para distribuidoras regionais (que têm cobertura de PDVs de um determinado território), e as distribuidoras vendem para os varejistas (supermercados, mercearias, farmácias, bares). As vantagens do canal indireto são: capilaridade (a distribuidora tem força de vendas e logística para PDVs que a indústria não consegue acessar diretamente com eficiência), crédito (a distribuidora financia o varejo — comprando à vista da indústria e vendendo a prazo para os PDVs), e serviço (a distribuidora gerencia a reposição, devoluções e relacionamento com o PDV). Os desafios do canal indireto incluem: visibilidade de sell-out (a indústria não sabe o que está sendo vendido ao consumidor final — sabe apenas o que saiu para a distribuidora), controle de precificação ao consumidor final (a distribuidora pode praticar preços diferentes dos planejados), e execução de trade marketing nos PDVs (a distribuidora pode priorizar outras marcas mais rentáveis).")
    ]
)

# Article 4742 — Consulting: M&A and due diligence
art(
    slug="consultoria-de-fusoes-aquisicoes-e-due-diligence-empresarial",
    title="Consultoria de Fusões, Aquisições e Due Diligence Empresarial",
    desc="Como funciona a consultoria de fusões e aquisições: processo de M&A, due diligence financeira e jurídica, valuation, negociação e integração pós-fusão.",
    h1="Consultoria de Fusões, Aquisições e Due Diligence Empresarial",
    lead="M&A (Mergers and Acquisitions) é um dos processos de negócio de maior complexidade e maior impacto: uma aquisição mal conduzida pode destruir valor em bilhões de reais, enquanto uma bem executada pode multiplicar o valor de uma empresa em anos. Consultoria de M&A guia compradores e vendedores em cada etapa — do primeiro contato ao fechamento e à integração.",
    sections=[
        ("O Processo de M&A: Do Mandato ao Fechamento",
         "O processo de M&A segue etapas bem definidas: originação (identificar oportunidades — compradores que procuram alvos, ou vendedores que querem liquidez); mandato (a empresa contrata a assessora de M&A com exclusividade — definindo o escopo, o preço-alvo e a estratégia de processo); preparação (elaboração do teaser — documento anonimizado de apresentação, e do CIM — Confidential Information Memorandum — documento detalhado para interessados que assinaram NDA); processo estruturado (envio do teaser para potenciais compradores, seleção dos interessados, distribuição do CIM, recebimento de ofertas não vinculantes — IOI, Indication of Interest); due diligence (os compradores finalistas realizam auditoria detalhada — financeira, jurídica, tributária, operacional, tecnológica); oferta vinculante (carta de intenções vinculante — LOI — com preço e condições); negociação e fechamento (SPA — Share Purchase Agreement, ajustes de preço, declarações e garantias, condições suspensivas); e integração (pós-fechamento — onde o valor da transação é efetivamente criado ou destruído)."),
        ("Due Diligence: A Auditoria que Protege o Comprador",
         "Due diligence é a investigação sistemática que o comprador realiza sobre a empresa-alvo antes de finalizar a aquisição — para confirmar as representações do vendedor, identificar riscos ocultos e calibrar o preço final. As dimensões cobertas incluem: DD financeira (qualidade dos resultados históricos — EBITDA recorrente vs. não recorrente, capital de giro normalizado, dívida líquida e suas nuances, passivos contingentes), DD jurídica (contratos relevantes, litígios, estrutura societária, propriedade intelectual), DD tributária (passivos fiscais, contingências de IRPJ/CSLL/PIS/COFINS/ICMS, planejamento tributário agressivo), DD trabalhista (passivos com ex-funcionários, ação trabalhista em andamento, compliance com CLT e acordos coletivos), DD tecnológica (qualidade do código, arquitetura, dívida técnica, segurança de dados), e DD comercial (concentração de clientes, taxa de churn, pipeline, saúde das métricas de negócio). Cada área de risco identificada na DD pode resultar em: ajuste de preço, garantias contratuais do vendedor, ou abandono da transação."),
        ("Valuation: Como Precificar uma Empresa",
         "O valuation (avaliação econômica) de uma empresa é o processo de estimar seu valor justo de mercado. Os métodos mais usados em M&A incluem: múltiplo de EBITDA (o mais comum em empresas não listadas — empresas do setor são vendidas a X vezes o EBITDA anual; o múltiplo varia por setor, crescimento, margem e risco), DCF (Discounted Cash Flow — fluxo de caixa projetado descontado a uma taxa que reflete o risco do negócio — mais rigoroso mas dependente de premissas de crescimento), múltiplo de receita (comum em SaaS e empresas de alto crescimento com EBITDA baixo ou negativo — X vezes o ARR), e comparáveis de transações recentes (quanto pagaram por empresas similares em transações recentes no setor). Em startups e scale-ups, o valuation é negociado com base em métricas de negócio (ARR, crescimento, NRR, CAC payback) e em comparáveis de rodadas recentes do setor. A consultoria de M&A que conhece os múltiplos praticados no mercado específico (não os múltiplos médios de mercado) entrega valuation mais preciso e mais defensável."),
        ("Integração Pós-Fusão: Onde o Valor é Criado ou Destruído",
         "A integração pós-fusão é a etapa mais crítica e mais subestimada do M&A: pesquisas mostram que 50% a 75% das fusões não entregam o valor esperado — e a razão principal é a integração mal executada. Os fatores de sucesso incluem: day one readiness (o plano de ação para os primeiros 100 dias pós-fechamento deve ser definido durante o processo de DD — não depois do fechamento), liderança clara (quem é responsável pela integração — o IMO, Integration Management Office), comunicação com colaboradores (a incerteza sobre cargos e futuro é a maior causa de turnover de talentos-chave no pós-fusão — comunicação rápida e honesta retém as pessoas certas), integração de sistemas (ERP, CRM, HR — que é o processo mais longo e mais custoso tecnicamente), e captura de sinergias (as sinergias que justificaram o prêmio pago devem ser rastreadas e realizadas — com responsável e prazo). A consultoria de integração pós-fusão é um serviço crescente no mercado — separado da assessoria de M&A da transação."),
        ("Métricas de Sucesso em Consultoria de M&A",
         "As métricas de entrega em assessoria de M&A incluem: transações fechadas (a métrica mais direta — a assessoria cobrou sucesso fee e a transação fechou?), valor médio das transações (ticket da transação — que define o sucesso fee da assessora), múltiplo médio obtido em processos sell-side (comparado ao benchmark do setor — o assessor conseguiu prêmio acima do mercado?), e prazo médio de fechamento (transações que fecham mais rápido têm menor custo para o cliente e maior giro para a assessora). As métricas de negócio da consultoria incluem: receita de sucesso fee (geralmente 2% a 5% do valor da transação para middle market), pipeline de transações em desenvolvimento (base de retainer mensal + futuros sucessos fees), e retenção de mandatos (clientes que usam a assessora para múltiplas transações — indicador de satisfação e de relacionamento de longo prazo).")
    ],
    faq_list=[
        ("Quanto tempo dura um processo de M&A?",
         "Um processo de M&A estruturado para uma empresa de médio porte (revenue de R$30 a R$500 milhões) dura tipicamente de 6 a 12 meses do início do mandato ao fechamento. A distribuição do tempo inclui: preparação dos materiais de marketing (teaser, CIM, modelo financeiro) — de 4 a 8 semanas; processo de marketing e seleção de compradores — de 6 a 10 semanas; due diligence — de 6 a 12 semanas; negociação e documentação jurídica (SPA) — de 4 a 8 semanas; e aprovações regulatórias quando necessárias (CADE para transações acima dos thresholds de notificação obrigatória) — de 30 dias a 6 meses adicionais. Transações mais simples (aquisição de empresa pequena por um comprador estratégico com DD reduzida) podem fechar em 3 a 4 meses. Transações complexas (grupos empresariais com múltiplas subsidiárias, passivos relevantes, múltiplos compradores) podem levar mais de 12 meses. A expectativa realista do vendedor deve incluir que o processo de M&A consome de 20% a 30% do tempo do CEO e do CFO ao longo de 6 a 9 meses."),
        ("O que é EBITDA e por que é usado como base de valuation?",
         "EBITDA (Earnings Before Interest, Taxes, Depreciation and Amortization — Lucro Antes de Juros, Impostos, Depreciação e Amortização) é uma métrica financeira que aproxima o caixa operacional gerado pelo negócio — eliminando os efeitos de estrutura de capital (juros), regime tributário (impostos), e política contábil de depreciação. É usado como base de valuation porque: permite comparar empresas de diferentes países (com regimes tributários diferentes) e com diferentes estruturas de capital (alavancadas vs. não alavancadas); é mais difícil de manipular contabilmente do que o lucro líquido; e é a proxy mais comum do 'poder de geração de caixa' do negócio operacional. O múltiplo de EBITDA varia por setor: negócios de tecnologia/SaaS (10x a 20x EBITDA para empresas de crescimento), negócios industriais maduros (4x a 7x), varejistas (5x a 8x), serviços profissionais (5x a 9x). Ajustes ao EBITDA são frequentes na due diligence — para normalizar itens não recorrentes e refletir o EBITDA 'real' da operação continuada."),
        ("O CADE precisa aprovar todas as fusões e aquisições?",
         "Não — o CADE (Conselho Administrativo de Defesa Econômica) exige notificação prévia apenas para transações que atendam simultaneamente dois critérios de faturamento: um dos grupos envolvidos teve faturamento bruto anual acima de R$750 milhões no Brasil no último exercício, e outro grupo teve faturamento acima de R$75 milhões no Brasil no mesmo período. Transações que não atingem esses thresholds não precisam de aprovação do CADE. Para transações notificáveis, o CADE tem prazo de 240 dias para análise (prorrogável por mais 90 dias em casos complexos). A maioria das transações é aprovada sem restrições (aprovação simples) ou com remédios menores (desinvestimento de determinados ativos para preservar a concorrência em mercados específicos). Transações em setores concentrados (saúde, combustíveis, alimentos) ou com alto market share combinado recebem análise mais criteriosa. A notificação ao CADE é uma condição suspensiva do fechamento — a transação não pode ser implementada antes da aprovação.")
    ]
)

# ── Sitemap & trilha update ──────────────────────────────────────────────────
sitemap_path = pathlib.Path(__file__).parent / "sitemap.xml"
trilha_path  = pathlib.Path(__file__).parent / "trilha.html"

new_slugs = [
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-eventos-e-gestao-de-eventos-corporativos",
     "Gestão de Negócios de Empresa de B2B SaaS de Eventos e Gestão de Eventos Corporativos"),
    ("gestao-de-clinicas-de-psiquiatria-e-saude-mental-adulto",
     "Gestão de Clínicas de Psiquiatria e Saúde Mental Adulto"),
    ("vendas-para-o-setor-de-saas-de-industria-alimenticia-e-food-tech",
     "Vendas para o Setor de SaaS de Indústria Alimentícia e Food Tech"),
    ("consultoria-de-gestao-de-vendas-e-forca-de-vendas",
     "Consultoria de Gestão de Vendas e Força de Vendas"),
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-restaurantes-e-food-service",
     "Gestão de Negócios de Empresa de B2B SaaS de Restaurantes e Food Service"),
    ("gestao-de-clinicas-de-pneumologia-e-doencas-respiratorias",
     "Gestão de Clínicas de Pneumologia e Doenças Respiratórias"),
    ("vendas-para-o-setor-de-saas-de-varejo-e-trade-marketing",
     "Vendas para o Setor de SaaS de Varejo e Trade Marketing"),
    ("consultoria-de-fusoes-aquisicoes-e-due-diligence-empresarial",
     "Consultoria de Fusões, Aquisições e Due Diligence Empresarial"),
]

sm = sitemap_path.read_text(encoding="utf-8")
new_urls = "".join(
    f"  <url><loc>https://produtovivo.com.br/blog/{s}/</loc></url>\n"
    for s, _ in new_slugs
)
sitemap_path.write_text(sm.replace("</urlset>", new_urls + "</urlset>"), encoding="utf-8")

tr = trilha_path.read_text(encoding="utf-8")
new_items = "".join(
    f'  <li><a href="/blog/{s}/">{t}</a></li>\n'
    for s, t in new_slugs
)
trilha_path.write_text(tr.replace("</ul>", new_items + "\n</ul>", 1), encoding="utf-8")

print("Done — batch 1626")
