import os, json, pathlib

BASE   = os.path.join(os.path.dirname(__file__), "blog")
DOMAIN = "https://produtovivo.com.br"
PIXEL  = "4520253334926563"

TMPL = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)}};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init','{pixel}');fbq('track','PageView');
</script>
<style>
body{{font-family:sans-serif;margin:0;padding:0;color:#222}}
header{{background:#0a7c4e;padding:16px 24px}}
header a{{color:#fff;text-decoration:none;font-size:1.3rem;font-weight:700}}
main{{max-width:860px;margin:40px auto;padding:0 20px}}
h1{{font-size:2rem;color:#0a7c4e}}
h2{{font-size:1.3rem;color:#065f3a;margin-top:32px}}
p{{line-height:1.7}}
.lead{{font-size:1.1rem;color:#444}}
.faq{{background:#f4faf7;border-left:4px solid #0a7c4e;padding:20px 24px;margin-top:40px}}
.faq h2{{margin-top:0}}
.faq-item{{margin-bottom:20px}}
.faq-item h3{{margin-bottom:4px;color:#065f3a}}
footer{{text-align:center;padding:32px;color:#777;font-size:.9rem;margin-top:60px}}
</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<header><a href="/">ProdutoVivo</a></header>
<main>
<h1>{h1}</h1>
<p class="lead">{lead}</p>
{body}
<div class="faq">
<h2>Perguntas Frequentes</h2>
{faqs}
</div>
</main>
<footer>© 2025 ProdutoVivo · Conteúdo informativo sobre gestão e tecnologia</footer>
</body>
</html>"""

def art(slug, title, desc, h1, lead, sections, faq_list):
    url = f"{DOMAIN}/blog/{slug}/"
    body_html = ""
    for sec_title, sec_body in sections:
        body_html += f"<h2>{sec_title}</h2>\n<p>{sec_body}</p>\n"
    faqs_html = ""
    schema_faqs = []
    for q, a in faq_list:
        faqs_html += f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>\n'
        schema_faqs.append({"@type": "Question", "name": q,
                             "acceptedAnswer": {"@type": "Answer", "text": a}})
    schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage",
                         "mainEntity": schema_faqs}, ensure_ascii=False)
    html = TMPL.format(title=title, desc=desc, url=url, pixel=PIXEL,
                       h1=h1, lead=lead, body=body_html, faqs=faqs_html, schema=schema)
    out_dir = os.path.join(BASE, slug)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

# Article 4711 — B2B SaaS: Real estate and property management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-imobiliarias-e-gestao-de-imoveis",
    title="Gestão de Negócios de Empresa de B2B SaaS de Imobiliárias e Gestão de Imóveis",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para imobiliárias e gestão de imóveis: modelo de negócio, funcionalidades, go-to-market e métricas do setor imobiliário.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Imobiliárias e Gestão de Imóveis",
    lead="O mercado imobiliário brasileiro movimenta R$200 bilhões por ano em transações e tem mais de 40 mil imobiliárias cadastradas no CRECI. Plataformas SaaS para imobiliárias cobrem CRM de clientes, portfólio de imóveis, gestão de locação e integração com portais — um mercado com enorme potencial de digitalização e recorrência.",
    sections=[
        ("O Mercado de PropTech SaaS no Brasil",
         "O mercado de SaaS para o setor imobiliário é segmentado por tipo de negócio: imobiliárias de venda e locação (CRM de clientes compradores e locatários, portfólio de imóveis, publicação automática nos portais — OLX, ZAP Imóveis, Viva Real), administradoras de imóveis (gestão de contratos de locação, boletos de aluguel, repasse para proprietários, manutenção e vistorias), incorporadoras (gestão de lançamentos, tabela de vendas, permuta, CRM de compradores na planta, obra), e gestão de condomínios (cotas, assembleias, prestação de contas, comunicação com condôminos). Cada segmento tem necessidades distintas — a plataforma que tenta atender todos com um produto genérico perde profundidade para especializadas. O ticket médio varia de R$200 a R$2.000/mês para imobiliárias de pequeno e médio porte."),
        ("CRM Imobiliário: O Módulo Central",
         "O CRM imobiliário é o coração operacional da imobiliária: registro e qualificação de leads (origem — portal, indicação, orgânico — orçamento, prazo, imóvel ideal), matching inteligente (o sistema sugere imóveis do portfólio que correspondem ao perfil do cliente), gestão de visitas (agendamento, confirmação por WhatsApp, registro de feedback pós-visita), follow-up automatizado (o lead que não foi convertido recebe sequência de e-mails e WhatsApp baseada no estágio do funil), e dashboard de performance por corretor (leads atendidos, visitas realizadas, propostas enviadas, contratos fechados). Imobiliárias sem CRM perdem leads por falta de follow-up sistemático — o comprador de imóvel pesquisa por meses e a imobiliária que mantiver contato consistente é a que fecha o negócio."),
        ("Gestão de Locação: Recorrência e Complexidade",
         "A gestão de locação é o módulo de maior recorrência em PropTech: cada contrato de aluguel gera eventos mensais (emissão de boleto, repasse ao proprietário, reajuste anual pelo IPCA/IGP-M) e eventos eventuais (vistoria de entrada, renovação de contrato, rescisão, vistoria de saída, devolução de caução). As funcionalidades críticas incluem: geração automática de boletos de aluguel (com split entre aluguel, condomínio e IPTU quando aplicável), cálculo automático de reajuste anual (IPCA, IGP-M — com geração do aditivo contratual), gestão de garantias (caução, seguro fiador, seguro garantia — prazos e renovações), e portal do proprietário (extrato de repasses, documentos do imóvel, relatórios de ocupação). Administradoras com 500+ imóveis gerenciados não conseguem operar sem sistema especializado — é o ponto de entrada ideal para venda."),
        ("Integração com Portais: O Diferencial Operacional",
         "A publicação manual de imóveis nos portais (ZAP, OLX, Viva Real, Imovelweb) consome horas por semana da equipe de uma imobiliária ativa. Plataformas de gestão que integram com os portais via API publicam o imóvel em todos os canais simultaneamente, atualizam automaticamente quando o imóvel é vendido ou locado (evitando o 'imóvel fantasma' — anúncio de imóvel indisponível que gera ligações desnecessárias), e centralizam os leads de todos os portais em um único inbox do CRM. A integração com os portais é um diferencial de produtividade concreto e mensurável — a imobiliária que antes levava 3 horas para publicar 20 imóveis passa a publicar em 10 minutos."),
        ("Métricas de Saúde do PropTech SaaS",
         "As métricas de produto incluem: imóveis ativos no portfólio gerenciado (quanto mais imóveis cadastrados, maior o switching cost), contratos de locação ativos gerenciados (receita recorrente mensal de alto valor para o cliente — que não quer perder esse histórico), e NPS do corretor e do gestor. As métricas de negócio incluem: MRR por imobiliária segmentado por módulo (locação tem ticket mais alto que venda pura), churn por encerramento de imobiliária (mercado com alguma sazonalidade e fechamentos — especialmente imobiliárias de 1 a 3 corretores), NRR (imobiliárias que crescem o portfólio expandem o número de imóveis gerenciados — growth natural), e CAC (o CRECI estadual e associações imobiliárias são canais de baixo custo para atingir o decisor).")
    ],
    faq_list=[
        ("O que é administração de imóveis e como funciona?",
         "Administração de imóveis é o serviço prestado por imobiliárias ou administradoras para proprietários que querem alugar seus imóveis sem se envolver com a gestão do dia a dia. A administradora cuida de: encontrar e selecionar inquilinos (análise de crédito, garantias), formalizar o contrato de locação, cobrar o aluguel mensalmente e repassar ao proprietário (descontando a taxa de administração — geralmente 8% a 12% do aluguel), gerenciar manutenções e reparos, aplicar reajustes anuais, e cuidar de vistorias e rescisões. Para o proprietário, a vantagem é delegar toda a burocracia mantendo a renda do imóvel. Para a imobiliária, a carteira de imóveis administrados é receita recorrente previsível — mesmo em períodos de baixa transação de venda e compra."),
        ("Como funciona o reajuste de aluguel no Brasil?",
         "O reajuste anual de aluguel no Brasil é calculado por índice de inflação — o contrato especifica qual índice usar (IPCA, IGP-M ou outro). O IGP-M foi o índice historicamente mais usado, mas passou a ser contestado por inquilinos após a pandemia de 2020-2021, quando chegou a acumular mais de 30% em 12 meses — muito acima da inflação percebida. O IPCA vem ganhando espaço como alternativa mais representativa da inflação ao consumidor. O reajuste é aplicado na data-base do contrato (aniversário do contrato) e formalizado em aditivo contratual. O inquilino tem direito de renegociar ou solicitar revisão judicial se o índice resultar em valor incompatível com o valor de mercado do imóvel — direito garantido pela Lei do Inquilinato (Lei 8.245/1991)."),
        ("PropTech vs. sistema de gestão imobiliária: qual a diferença?",
         "Na prática, os termos se sobrepõem. 'Sistema de gestão imobiliária' é o nome histórico para o software que as imobiliárias usam para controlar carteira, locação e financeiro — geralmente software desktop legado (como SIIG, Imoview, Imobex). 'PropTech' é o termo moderno para startups de tecnologia focadas no mercado imobiliário — que nasceram na nuvem, têm UX moderna e APIs abertas para integração. A geração de PropTech SaaS (QuintoAndar para locação direta, Loft para compra e venda, Kenlo, Jetimob para gestão de imobiliárias) desafia os sistemas legados com modelos mais ágeis e pricing mais acessível. Para imobiliárias tradicionais que ainda usam software desktop dos anos 2000, a migração para PropTech SaaS moderno é a principal oportunidade de modernização operacional.")
    ]
)

# Article 4712 — Clinic: Endocrinology and metabolic diseases
art(
    slug="gestao-de-clinicas-de-endocrinologia-e-doencas-metabolicas",
    title="Gestão de Clínicas de Endocrinologia e Doenças Metabólicas",
    desc="Guia de gestão para clínicas de endocrinologia: fluxo de atendimento, manejo de diabetes e obesidade, gestão de pacientes crônicos e indicadores de qualidade clínica.",
    h1="Gestão de Clínicas de Endocrinologia e Doenças Metabólicas",
    lead="O Brasil tem 17 milhões de diabéticos e mais de 100 milhões de pessoas com sobrepeso ou obesidade. Clínicas de endocrinologia são centros de referência para o manejo dessas condições crônicas de alta prevalência — combinando consultas de alta frequência, exames laboratoriais e acompanhamento multidisciplinar de longo prazo.",
    sections=[
        ("O Escopo da Endocrinologia Clínica",
         "A endocrinologia clínica abrange: diabetes mellitus (tipo 1 e tipo 2 — insulinoterapia, monitoramento glicêmico, manejo de complicações), obesidade e síndrome metabólica (avaliação de risco cardiovascular, farmacoterapia para obesidade, preparo para cirurgia bariátrica), doenças da tireoide (hipotireoidismo, hipertireoidismo, nódulos tireoidianos, câncer de tireoide), distúrbios do metabolismo ósseo (osteoporose — avaliação de risco de fratura, densitometria, tratamento), distúrbios hipofisários e adrenais (acromegalia, hiperprolactinemia, síndrome de Cushing, insuficiência adrenal), e distúrbios do eixo reprodutivo endócrino (síndrome dos ovários policísticos, hipogonadismo masculino). A diabetes e a obesidade representam mais de 70% do volume de consultas na maioria das clínicas de endocrinologia."),
        ("Gestão de Pacientes Diabéticos: Alta Cronicidade e Protocolos",
         "O paciente diabético é o perfil de maior frequência de retorno em endocrinologia: consultas a cada 3 meses para pacientes com controle inadequado (HbA1c acima de 8%), a cada 6 meses para pacientes bem controlados. Os elementos do acompanhamento incluem: avaliação de HbA1c (meta abaixo de 7% para a maioria dos adultos), rastreamento de complicações crônicas (fundo de olho — retinopatia; microalbuminúria — nefropatia; exame dos pés — neuropatia e pé diabético), ajuste de terapia (insulina, análogos de GLP-1, inibidores de SGLT-2), e educação terapêutica do paciente (automonitoramento com glicosímetro ou CGM — sensor de glicose contínuo). O CGM (Continuous Glucose Monitor) — como o Freestyle Libre e o Dexante — revolucionou o acompanhamento do diabetes: o médico acessa o relatório de 14 dias de glicemia do paciente em 5 minutos de consulta."),
        ("Cirurgia Bariátrica e o Papel do Endocrinologista",
         "O endocrinologista tem papel central no preparo e no acompanhamento pós-bariátrico: avaliação pré-operatória (confirmação da indicação — IMC ≥40 ou ≥35 com comorbidades, exclusão de causas endócrinas de obesidade tratáveis como hipotireoidismo e hipercortisolismo), acompanhamento pós-operatório (deficiências nutricionais — ferro, vitamina B12, vitamina D, cálcio — que são universais após o bypass gástrico), remissão do diabetes (monitoramento da remissão do DM2 após a bariátrica — que ocorre em 70-80% dos casos antes mesmo de perder peso significativo), e prevenção de hipoglicemia pós-bariátrica (síndrome de dumping tardio). Clínicas de endocrinologia com programa estruturado de bariátrica — em parceria com cirurgião bariátrico — capturam um volume relevante e diferenciado de pacientes."),
        ("Tecnologia no Consultório de Endocrinologia",
         "As ferramentas tecnológicas que diferenciam clínicas de endocrinologia incluem: integração com dados de CGM (softwares que importam os dados do sensor de glicose do paciente e geram o relatório AGP — Ambulatory Glucose Profile — usado na consulta), densitômetro ósseo próprio (DEXA — padrão ouro para osteoporose; clínica que tem o exame disponível aumenta o ticket por consulta e a conveniência do paciente), ultrassonografia de tireoide (nódulos de tireoide são rastreados por US — clínica que tem o equipamento faz a avaliação imediata na consulta), e plataformas de educação do paciente (apps de diário alimentar e glicêmico que o paciente preenche em casa e o médico monitora). O prontuário eletrônico com campos estruturados para diabetes (HbA1c histórico, doses de insulina, hipoglicemias registradas) é fundamental para a qualidade do acompanhamento."),
        ("Indicadores de Qualidade em Endocrinologia",
         "As métricas clínicas incluem: percentual de pacientes diabéticos com HbA1c abaixo da meta (indica efetividade do manejo clínico — meta da SBD é acima de 50% dos pacientes controlados), taxa de rastreamento de complicações crônicas do diabetes (fundo de olho, microalbuminúria, exame dos pés — feitos anualmente em todos os diabéticos), e NPS. As métricas de negócio incluem: ticket médio por consulta com exames (consulta + HbA1c + microalbuminúria + outros laboratoriais é a visita padrão do diabético — ticket de R$400 a R$800 dependendo do plano), taxa de retorno no intervalo correto (paciente com DM2 descontrolado que não retornou em 3 meses está em risco de complicação e de churn), e tempo médio de espera para primeira consulta (endocrinologia tem alta demanda reprimida — tempo de espera longo é indicador de capacidade e captação).")
    ],
    faq_list=[
        ("Qual a diferença entre diabetes tipo 1 e tipo 2?",
         "Diabetes tipo 1 é uma doença autoimune: o sistema imunológico ataca e destrói as células beta do pâncreas que produzem insulina. O resultado é ausência total (ou quase total) de insulina endógena — o paciente precisa de insulina exógena para sobreviver. O DM1 geralmente se manifesta na infância ou adolescência, mas pode ocorrer em adultos. Diabetes tipo 2 é a forma mais prevalente (90% dos casos): o pâncreas produz insulina, mas as células do corpo desenvolvem resistência à sua ação (resistência insulínica), e o pâncreas progressivamente perde capacidade de compensar essa resistência. O DM2 tem forte associação com obesidade, sedentarismo e histórico familiar, e geralmente se manifesta após os 40 anos. O tratamento do DM2 começa com mudança de estilo de vida e medicações orais, podendo progredir para insulina em estágios avançados."),
        ("GLP-1 e semaglutida: o que são e para que servem?",
         "GLP-1 (Glucagon-Like Peptide-1) é um hormônio intestinal que estimula a secreção de insulina, reduz o glucagon, retarda o esvaziamento gástrico e promove saciedade. Análogos de GLP-1 injetáveis (como a semaglutida — Ozempic para diabetes, Wegovy para obesidade; e liraglutida — Victoza/Saxenda) foram originalmente desenvolvidos para diabetes tipo 2 e demonstraram ação antiobesidade significativa como efeito secundário. A semaglutida em alta dose (Wegovy) foi aprovada especificamente para tratamento da obesidade — com redução média de 15% do peso corporal em 68 semanas, muito superior a qualquer outro medicamento anterior. A popularidade do Ozempic para emagrecimento sem indicação clínica de diabetes criou escassez do medicamento e debate ético sobre uso off-label. O endocrinologista é o especialista indicado para prescrever e acompanhar esses medicamentos."),
        ("Nódulo de tireoide precisa operar?",
         "A grande maioria dos nódulos de tireoide é benigna e não requer cirurgia. O nódulo de tireoide é muito prevalente — encontrado por ultrassonografia em 50-60% das mulheres acima de 50 anos. A avaliação segue o sistema TIRADS (TI-RADS — Thyroid Imaging Reporting and Data System), que classifica os nódulos por características de imagem em uma escala de risco de malignidade. Nódulos com características suspeitas de malignidade (bordas irregulares, microcalcificações, hipovascularização com fluxo central, crescimento rápido) são submetidos à punção aspirativa com agulha fina (PAAF) para avaliação citológica. Apenas 5 a 10% dos nódulos puncionados são malignos — e mesmo o câncer de tireoide diferenciado (papilífero e folicular) tem prognóstico excelente com cirurgia e acompanhamento adequados.")
    ]
)

# Article 4713 — SaaS sales: Mental health and psychology sector
art(
    slug="vendas-para-o-setor-de-saas-de-saude-mental-e-psicologia",
    title="Vendas para o Setor de SaaS de Saúde Mental e Psicologia",
    desc="Estratégias de vendas B2B para plataformas SaaS de saúde mental e psicologia: como abordar psicólogos, clínicas de psicologia e plataformas de telepsicologia para fechar contratos.",
    h1="Vendas para o Setor de SaaS de Saúde Mental e Psicologia",
    lead="A saúde mental é o setor de saúde de maior crescimento pós-pandemia — com aumento de 25% na demanda por psicólogos e expansão acelerada da telepsicologia. Plataformas de gestão para psicólogos e clínicas de saúde mental têm oportunidade única num mercado com alta sensibilidade a compliance, privacidade e ética profissional.",
    sections=[
        ("O Mercado de Mental HealthTech SaaS",
         "O mercado de SaaS para saúde mental inclui: plataformas de gestão para psicólogos independentes (agenda, prontuário, cobrança, teleconsulta — tudo em um), software de gestão de clínicas de psicologia e psiquiatria (multidisciplinar com múltiplos profissionais), plataformas de Employee Assistance Program (EAP) corporativo (benefício de saúde mental para colaboradores — contratado pela empresa para oferecer psicólogos online para seus funcionários), plataformas de telepsicologia (marketplace de psicólogos online — como Zenklub, Vittude, Psicologia Viva), e ferramentas de avaliação psicológica digital (escalas padronizadas, relatórios automáticos — PHQ-9, GAD-7, escalas de apego). O CFP (Conselho Federal de Psicologia) regulamenta a prática da psicologia e a teleconsulta — plataformas devem estar em conformidade com a Resolução CFP 11/2018 e atualizações."),
        ("O Psicólogo como Decisor: Perfil e Sensibilidades",
         "O psicólogo é um decisor com características específicas: alta sensibilidade ética (a plataforma que vende dados dos pacientes ou usa o prontuário para treinar IA sem consentimento é imediatamente rejeitada), forte identidade profissional (resiste a ferramentas que parecem reduzir a prática clínica a processo ou fluxograma), valoriza autonomia (não quer ser gerenciado pelo software — quer que o software sirva a ele), e tende a ser influenciado por colegas de confiança (a recomendação de um psicólogo respeitado na comunidade vale mais do que qualquer campanha de marketing). A abordagem de vendas mais eficaz é baseada em comunidade: fazer a plataforma ser recomendada organicamente por psicólogos que já usam e aprovam."),
        ("Prontuário Psicológico: LGPD e Sigilo Profissional",
         "O prontuário psicológico tem proteção legal especial: o sigilo profissional do psicólogo é um dever ético e legal protegido pelo Código de Ética do CFP — diferente de outras especialidades médicas, o conteúdo das sessões de psicoterapia é absolutamente protegido. A LGPD classifica dados de saúde mental como dados sensíveis, com proteção adicional. Plataformas de gestão psicológica devem: criptografar prontuários em repouso e em trânsito, garantir que apenas o psicólogo responsável acessa as anotações de sessão, obter consentimento específico para uso dos dados, e ter política clara de não uso de conteúdo clínico para treino de IA ou marketing. Comunicar essas garantias de forma clara é pré-requisito para a confiança do psicólogo — e diferencial competitivo em relação a plataformas genéricas de prontuário."),
        ("EAP Corporativo: O Segmento de Maior Crescimento",
         "EAP (Employee Assistance Program) — programas de saúde mental corporativos — cresceram mais de 200% nos últimos 3 anos no Brasil. Empresas com 100+ colaboradores percebem o absenteísmo e a perda de produtividade por saúde mental como custo concreto — e o EAP como solução de ROI mensurável. As plataformas de EAP corporativo (Zenklub for Business, Vittude Corporate, Psicologia Viva Empresas) oferecem: número de sessões de psicologia online por colaborador, plataforma de bem-estar mental (meditação, conteúdos de autoconhecimento), relatórios agregados de clima mental organizacional (sem identificação individual), e suporte a RH para casos críticos. O decisor do EAP é o diretor de RH ou o CHRO — com aprovação do CFO pelo impacto em custo de absenteísmo e turnover."),
        ("Métricas de Saúde em Mental HealthTech SaaS",
         "As métricas de produto incluem: sessões realizadas por mês na plataforma (principal indicador de uso ativo), taxa de adoção de teleconsulta vs. presencial (indica que a plataforma está criando novo comportamento, não apenas digitalizando o existente), e NPS do psicólogo. As métricas de negócio incluem: MRR por psicólogo ativo (R$50 a R$200/mês para plataformas de psicólogo independente), MRR por empresa no EAP corporativo (R$20 a R$80 por colaborador/mês — com contratos de 12 meses), churn de psicólogos (alta se o sistema for percebido como burocrático ou invasivo da prática clínica), e CAC por canal (comunidades de psicólogos e indicação de colega têm CAC muito mais baixo e LTV mais alto do que inbound genérico).")
    ],
    faq_list=[
        ("Teleconsulta de psicologia tem a mesma eficácia que a presencial?",
         "A evidência científica acumulada pós-pandemia indica que a psicoterapia online tem eficácia equivalente à presencial para a maioria das condições e modalidades terapêuticas — especialmente TCC (Terapia Cognitivo-Comportamental), que é a abordagem com mais estudos de eficácia. As metanálises mais recentes (2021-2024) mostram tamanhos de efeito similares para depressão, ansiedade e fobia social. As condições em que o presencial pode ter vantagem incluem: transtornos graves como psicose aguda ou TDM grave com risco de suicídio (onde o presencial facilita avaliação de segurança), crianças pequenas (que têm dificuldade de manter atenção em tela), e abordagens que envolvem expressão corporal (biodança, Gestalt somática). Para a grande maioria dos adultos em psicoterapia, a teleconsulta é uma opção clinicamente válida e muito mais acessível geograficamente."),
        ("CFP permite psicologia online? Quais as regras?",
         "Sim — o CFP regulamentou a psicologia online pela Resolução CFP 11/2018, que permite: psicoterapia, orientação psicológica, avaliação psicológica online (com restrições para alguns instrumentos) e supervisão clínica. As regras principais incluem: a sessão deve usar plataforma segura e criptografada (não pode usar WhatsApp para sessões terapêuticas), o psicólogo deve garantir privacidade no seu local de atendimento, o paciente deve ser informado sobre as especificidades do atendimento online e dar consentimento, e o prontuário online deve seguir as mesmas exigências do presencial. Plataformas de gestão que usam teleconsulta devem usar videochamada criptografada — o zoom sem criptografia end-to-end não é recomendado; soluções como Daily.co, Whereby ou videochamada embedded com criptografia são preferidas."),
        ("Como precificar sessão de psicologia?",
         "A precificação da sessão de psicologia varia enormemente por região (capitais vs. interior), modalidade (presencial vs. online) e nível de experiência do profissional. O CFP e o CRP (Conselho Regional) orientam que o psicólogo deve cobrar valor que respeite a ética profissional e seja compatível com o mercado local. Como referência geral em 2025: psicólogos recém-formados cobram de R$80 a R$150/sessão em cidades de médio porte; psicólogos com 5+ anos de experiência cobram de R$150 a R$300/sessão em capitais; psicólogos renomados com especialização e público premium cobram de R$300 a R$600/sessão. Online tende a ter preço 10-20% menor que presencial pelo mesmo profissional. Plataformas de telepsicologia como Zenklub e Vittude têm planos com sessões a partir de R$150 — com desconto por volume de sessões contratadas.")
    ]
)

# Article 4714 — Consulting: Organizational culture and change management
art(
    slug="consultoria-de-cultura-organizacional-e-gestao-de-mudancas",
    title="Consultoria de Cultura Organizacional e Gestão de Mudanças",
    desc="Como funciona a consultoria de cultura organizacional e gestão de mudanças: diagnóstico cultural, programas de transformação cultural, liderança e métricas de cultura.",
    h1="Consultoria de Cultura Organizacional e Gestão de Mudanças",
    lead="Cultura organizacional é o conjunto de valores, crenças e comportamentos que definem como as pessoas agem numa empresa — é o sistema operacional humano da organização. Consultorias de cultura ajudam empresas a diagnosticar sua cultura atual, definir a cultura aspiracional e gerenciar a mudança de forma que o comportamento real se aproxime dos valores declarados.",
    sections=[
        ("O que é Consultoria de Cultura Organizacional",
         "A consultoria de cultura organizacional atua em: diagnóstico cultural (mapear a cultura atual da empresa por meio de entrevistas, pesquisas e observação — identificando os valores reais em ação, não apenas os valores declarados), design da cultura aspiracional (definir com a liderança qual a cultura que a empresa precisa para executar sua estratégia), programa de transformação cultural (iniciativas concretas para mudar comportamentos — não apenas comunicar valores), desenvolvimento de liderança cultural (os líderes são o principal vetor da cultura — seu comportamento molda o comportamento de toda a organização), e gestão de mudança organizacional (quando a empresa passa por fusão, reestruturação ou mudança de estratégia, o impacto cultural precisa ser gerenciado ativamente). Consultorias especializadas em cultura trabalham com ferramentas como o modelo Competing Values Framework, o OCAI (Organizational Culture Assessment Instrument) e diagnósticos proprietários."),
        ("Diagnóstico Cultural: Como Mapear o que Realmente Existe",
         "O diagnóstico cultural vai além das pesquisas de clima anuais — identifica os pressupostos básicos inconscientes que guiam o comportamento (o que Schein chamou de nível mais profundo da cultura). As metodologias incluem: entrevistas individuais com líderes e colaboradores (explorando como decisões são tomadas, como conflitos são resolvidos, quem é promovido e por quê, quais comportamentos são tolerados mesmo quando contrários aos valores declarados), etnografia organizacional (consultores observam reuniões e interações informais), análise de artefatos culturais (como são as salas de reunião? os líderes têm salas fechadas ou open space? como é o onboarding?), e análise dos sistemas de gestão de pessoas (quem é promovido? quem é demitido? o sistema de reconhecimento recompensa os comportamentos certos?). A diferença entre 'cultura declarada' e 'cultura em ação' é frequentemente maior do que a liderança imagina."),
        ("Transformação Cultural: Por que é Tão Difícil",
         "Transformação cultural tem taxa de insucesso alta — estimativas variam de 50% a 80% de projetos que não produzem mudança sustentável. Os fatores de falha mais comuns incluem: tentativa de mudar cultura por comunicação (campanhas de valores, cartazes com os pilares culturais — sem mudar os sistemas e comportamentos que reforçam a cultura atual), líder que prega valores que não pratica (o colaborador imita o comportamento do gestor, não o cartaz na parede), falta de conexão entre cultura e estratégia (cultura definida sem clareza de qual comportamento é necessário para executar a estratégia), e horizonte de tempo irrealista (mudança cultural real leva de 3 a 7 anos — não acontece em 90 dias de workshop). Cultura é mudada quando os sistemas de gestão (quem é promovido, quem é reconhecido, quais comportamentos são tolerados) mudam de forma consistente com os valores declarados."),
        ("Gestão de Mudança em Fusões e Aquisições",
         "Fusões e aquisições são o contexto de maior urgência para gestão de mudança cultural: dois grupos de pessoas com histórias e culturas distintas precisam operar juntos — com incerteza sobre cargos, lideranças e futuro. As fases de gestão de mudança em M&A incluem: due diligence cultural pré-fusão (identificar diferenças culturais que podem ser fontes de conflito pós-integração), design do modelo de integração cultural (qual cultura prevalece? há uma nova cultura a ser construída?), gestão da ansiedade e incerteza (comunicação frequente, clara e honesta — 'não sabemos ainda' é melhor que silêncio), captura de liderança cultural (identificar os líderes informais em ambas as organizações e engajá-los como agentes de integração), e monitoramento de indicadores de integração (eNPS, turnover de talentos-chave, conflitos de equipe). Pesquisas indicam que 50-75% do valor de M&A é destruído por falha na integração cultural."),
        ("Métricas de Cultura: Como Medir o Intangível",
         "As métricas de cultura organizacional incluem: eNPS (Employee Net Promoter Score — a pergunta 'você recomendaria esta empresa como lugar para trabalhar?' captura lealdade e orgulho que são reflexo da cultura), índice de congruência cultural (percentual de colaboradores que percebem os comportamentos da liderança como alinhados com os valores declarados), turnover de talentos-chave (a saída de top performers é sinal de cultura que não retém ou que tem conflito entre os valores declarados e o que é recompensado na prática), absenteísmo por saúde mental (indicador de cultura tóxica ou de excesso de pressão sem suporte), e velocidade de integração de novos colaboradores (quanto tempo até o novo colaborador estar operando em plena performance — indicador de clareza e inclusão da cultura).")
    ],
    faq_list=[
        ("Cultura organizacional pode ser mudada?",
         "Sim — mas lentamente e com investimento intencional. A crença de que 'cultura não muda' é um mito que frequentemente serve para justificar inação. O que é verdade é que cultura muda lentamente (anos, não meses) e que não muda apenas pela declaração de novos valores. Os catalisadores de mudança cultural mais poderosos são: mudança de liderança (um novo CEO ou gestor que modela consistentemente novos comportamentos tem impacto enorme), crise ou transformação do modelo de negócio (que force a empresa a questionar como faz as coisas), e mudança dos sistemas de gestão de pessoas (promover pessoas que vivem os valores, demitir líderes que entregam resultados mas destroem a cultura — esse é o sinal mais poderoso que a organização pode dar). A consultoria de cultura acelera essa mudança ao torná-la intencional e sistemática."),
        ("Como o RH pode ser responsável pela cultura se a cultura pertence a todos?",
         "Essa é uma tensão real. A cultura pertence a toda a organização — e é modelada principalmente pelos comportamentos dos líderes de negócio, não pelo RH. O papel do RH na cultura é de guardião e facilitador: o RH desenha os processos de recrutamento que buscam pessoas alinhadas com os valores, define critérios de promoção e reconhecimento que reforçam os comportamentos certos, e mede regularmente o alinhamento entre cultura declarada e cultura praticada. Mas o RH não pode criar cultura — apenas apoiar a criação. Quando o RH é o 'dono da cultura' e a liderança de negócio não é corresponsável, a cultura fica no papel (nos cartazes e nas apresentações de onboarding) e não se manifesta nos comportamentos do dia a dia."),
        ("O que é Competing Values Framework?",
         "O Competing Values Framework (CVF) é um modelo de diagnóstico e tipologia cultural desenvolvido por Quinn e Rohrbaugh. Ele organiza as culturas em quatro quadrantes definidos por dois eixos: foco interno (pessoas e processos) vs. externo (mercado e clientes), e controle vs. flexibilidade. Os quatro tipos culturais são: Clã (foco interno + flexibilidade — cultura familiar, colaborativa, desenvolvimento de pessoas), Adhocracy (foco externo + flexibilidade — cultura inovadora, empreendedora, de experimentação), Mercado (foco externo + controle — cultura orientada a resultados, competitiva, baseada em metas), e Hierarquia (foco interno + controle — cultura processual, estável, orientada a eficiência). Nenhum tipo é melhor em abstrato — a cultura ideal depende da estratégia. O instrumento OCAI avalia a cultura atual e aspiracional nos quatro tipos, gerando o gap cultural que a transformação deve endereçar.")
    ]
)

# Article 4715 — B2B SaaS: Veterinary clinic management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-clinicas-veterinarias",
    title="Gestão de Negócios de Empresa de B2B SaaS de Clínicas Veterinárias",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para clínicas veterinárias: modelo de negócio, funcionalidades, go-to-market e métricas do mercado pet.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Clínicas Veterinárias",
    lead="O mercado pet brasileiro é o terceiro maior do mundo, com mais de 160 milhões de animais de estimação e um faturamento acima de R$60 bilhões por ano. Clínicas veterinárias — consultas, exames, cirurgias, internação, banho e tosa — são o coração desse ecossistema e têm demanda crescente por plataformas de gestão profissional.",
    sections=[
        ("O Mercado de VetTech SaaS no Brasil",
         "O mercado de SaaS para veterinária é segmentado por tipo de estabelecimento: clínicas veterinárias de pequeno animal (cães e gatos — o segmento dominante), hospitais veterinários 24h (maior complexidade — internação, UTI animal, cirurgias de emergência), pet shops com serviço veterinário (banho, tosa, consulta e vacinas — lower ticket, maior volume), clínicas de grandes animais (equinos e bovinos — mercado de agronegócio com necessidades muito diferentes), e redes e franquias pet (Pet Center Marginal, PetLove, Cobasi com serviços). A plataforma de gestão veterinária cobre: prontuário do paciente animal (histórico clínico, vacinas, vermifugações, exames), agenda de consultas, internação e cirurgias, gestão de estoque de medicamentos veterinários, e financeiro (caixa, contas a receber, relatórios). O ticket médio varia de R$150 a R$800/mês dependendo do porte da clínica."),
        ("Prontuário Veterinário: Particularidades e Compliance",
         "O prontuário veterinário tem especificidades em relação ao médico: o paciente é o animal, mas o cliente (que paga e toma decisões) é o tutor. O prontuário deve conter: dados do animal (espécie, raça, nome, peso, microchip), dados do tutor (proprietário), histórico de consultas e procedimentos, carteira de vacinação (vacinas obrigatórias — antirrábica, V8/V10 para cães — e opcionais), histórico de vermifugações e antiparasitários, exames realizados e resultados, medicamentos prescritos (a prescrição veterinária é regulamentada pelo MAPA e pelo CFMV — antibióticos exigem receita), e acompanhamento de doenças crônicas (hipotireoidismo, diabetes mellitus veterinária, doença renal crônica felina). Clínicas que têm o histórico completo do animal geram muito mais valor para o tutor — e têm switching cost maior para a troca de clínica."),
        ("Gestão de Internação e Cirurgia Veterinária",
         "Clínicas e hospitais veterinários que realizam internação precisam de funcionalidades adicionais: ficha de internação (diagnóstico de entrada, plano de tratamento, medicações e horários, evolução diária), controle de dieta durante a internação (tipo de alimento, quantidade, horários — especialmente importante em pacientes com insuficiência renal ou diabetes), comunicação com o tutor (a angústia do tutor com o animal internado é grande — sistemas que enviam updates por WhatsApp ou app reduzem chamadas desnecessárias e aumentam a satisfação), estimativa de custos e acompanhamento financeiro da internação (o tutor deve ser informado dos custos progressivos — a surpresa na alta é fonte de conflito), e gestão de UTI (monitoramento de sinais vitais, medicamentos contínuos). O bloqueio de horários cirúrgicos e a gestão de centro cirúrgico (equipamentos, kits cirúrgicos, equipe anestesista) são funcionalidades valorizadas em hospitais veterinários."),
        ("Go-to-Market em VetTech SaaS",
         "O decisor em clínica veterinária de pequeno e médio porte é o próprio veterinário-dono. Em grupos veterinários e redes, o decisor é o gestor de operações ou o CEO. O veterinário é um profissional que valoriza: facilidade de uso (ele não tem tempo para sistemas complexos — a consulta é dinâmica e rápida), prontuário completo do animal (a qualidade clínica depende do acesso ao histórico), e suporte rápido quando algo dá errado. Os canais de venda mais eficientes incluem: parcerias com distribuidores de medicamentos veterinários (a distribuidora que visita clinicamente cada veterinário todo mês é o canal de maior confiança do setor), eventos de medicina veterinária (ANCLIVEPA, WSAVA — congresso mundial), faculdades de veterinária (futuros veterinários que aprendem o sistema na faculdade levam para a clínica), e comunidades online de veterinários."),
        ("Métricas de Saúde do VetTech SaaS",
         "As métricas de produto incluem: animais com prontuário ativo (a métrica de profundidade de uso — clínica que tem 1.000 animais ativos no sistema não troca de plataforma facilmente), consultas registradas por mês, e NPS do veterinário e da equipe de recepção. As métricas de negócio incluem: MRR por tipo de estabelecimento (hospital veterinário tem ticket maior que pet shop com serviço veterinário), churn (clínicas veterinárias têm boa saúde financeira no Brasil — o churn costuma ser baixo quando o sistema é bem adotado), expansão por módulos (clínica que adiciona módulo de internação ou de pet shop ao sistema básico), e CAC (distribuidoras de medicamentos veterinários como JA Saúde Animal e Vetbrands são canais de distribuição de altíssimo ROI — elas chegam em toda clínica do Brasil).")
    ],
    faq_list=[
        ("Software de gestão veterinária exige integração com equipamentos de diagnóstico?",
         "A integração com equipamentos de diagnóstico é um diferencial crescente em veterinária: analisadores hematológicos e bioquímicos que exportam resultados diretamente para o prontuário (eliminando a transcrição manual — fonte de erro), aparelhos de radiografia digital que armazenam as imagens no sistema (DICOM viewer integrado ao prontuário), e equipamentos de ultrassonografia que vinculam as imagens ao prontuário do animal. Essa integração economiza tempo e reduz erros — o laudo chega ao prontuário em segundos após o exame. O sistema que tem integração com as marcas de equipamentos mais usadas no Brasil (Samsung, Mindray, Idexx, Heska) tem vantagem competitiva real. A tendência é de plataformas de PIMS (Practice Information Management System) veterinários que se tornam hubs de integração de todos os dados clínicos do animal."),
        ("Como funciona o controle de medicamentos veterinários no sistema?",
         "O controle de medicamentos veterinários em clínica envolve duas dimensões: estoque físico (quantidade disponível, lote, validade, ponto de pedido) e prescrição (receitas veterinárias com registro no sistema para rastreabilidade). Medicamentos veterinários controlados pelo MAPA (especialmente antimicrobianos e psicotrópicos veterinários) exigem receituário especial e registro na RMCA (Receita de Medicamento Controlado Animal). O sistema deve: alertar quando o estoque cai abaixo do mínimo, controlar a validade (alerta antes do vencimento), vincular o uso de medicamentos ao prontuário do animal (rastreabilidade), e gerar as receitas com os dados obrigatórios. Clínicas que perdem medicamentos por vencimento ou por desvio têm impacto financeiro relevante — o sistema de gestão de estoque bem usado evita esses prejuízos."),
        ("Pet insurance cresce no Brasil? Impacto nas clínicas veterinárias",
         "O seguro pet (plano de saúde para animais) está crescendo rapidamente no Brasil — saindo de uma base muito baixa (menos de 1% de penetração vs. 30-40% em países como Reino Unido e EUA). Os principais players no Brasil são Pet Love Saúde, BetterVet, e algumas seguradoras tradicionais que lançaram produtos pet. Para as clínicas veterinárias, o seguro pet impacta de duas formas: tutores com plano de saúde animal têm mais disposição para procedimentos preventivos e diagnósticos que antes seriam recusados por custo (aumenta o ticket por consulta), e a clínica credenciada no plano recebe fluxo de pacientes adicionais. A gestão de autorizações de planos veterinários — similar ao processo de autorização de planos médicos — começa a aparecer como funcionalidade em sistemas veterinários. O crescimento do seguro pet criará demanda por automação desse processo nas clínicas.")
    ]
)

# Article 4716 — Clinic: Orthopedics and sports medicine
art(
    slug="gestao-de-clinicas-de-ortopedia-e-medicina-esportiva",
    title="Gestão de Clínicas de Ortopedia e Medicina Esportiva",
    desc="Guia de gestão para clínicas de ortopedia e medicina esportiva: fluxo de atendimento, procedimentos cirúrgicos, gestão de convênios e indicadores de qualidade assistencial.",
    h1="Gestão de Clínicas de Ortopedia e Medicina Esportiva",
    lead="A ortopedia é uma das especialidades médicas de maior demanda no Brasil — impulsionada pelo envelhecimento da população, pelos acidentes de trabalho e pelo crescimento das lesões esportivas em praticantes amadores. Clínicas de ortopedia combinam alto volume ambulatorial com procedimentos cirúrgicos de alto valor, gerando complexidade operacional significativa.",
    sections=[
        ("O Escopo da Ortopedia e Medicina Esportiva",
         "A ortopedia clínica e cirúrgica abrange: trauma ortopédico (fraturas, luxações — atendimento de urgência e eletivo), patologias do joelho (lesão de LCA, menisco, condropatia — altíssima prevalência em esportistas amadores e profissionais), patologias do ombro (lesão de manguito rotador, luxação de ombro, instabilidade glenoumeral), artroplastias (prótese de quadril e joelho — principal cirurgia em idosos, com demanda crescente pelo envelhecimento populacional), patologia da coluna vertebral em parceria com neurocirurgia (hérnia de disco, estenose de canal), e medicina esportiva (avaliação de performance, prevenção de lesões, retorno ao esporte após lesão). A ortopedia é uma das especialidades com maior volume de procedimentos cirúrgicos — o que demanda centro cirúrgico próprio ou parcerias com hospitais e clínicas de cirurgia ambulatorial."),
        ("Gestão de Convênios em Ortopedia: A Principal Dor Operacional",
         "A gestão de convênios médicos é a maior dor operacional em clínicas de ortopedia: autorizações de procedimentos cirúrgicos (que exigem laudo médico detalhado, código TUSS, CID — e frequentemente são negadas na primeira solicitação), glosas (recusa de pagamento de procedimentos realizados por erros de código ou documentação insuficiente), tabelas de cobertura diferentes por convênio (o mesmo procedimento tem valor de reembolso completamente distinto entre operadoras), e preenchimento de SADT (solicitação de auxílio diagnóstico e terapêutico) para cada exame solicitado. Clínicas com sistema de gestão que: (1) tem os códigos TUSS atualizados para cada operadora, (2) alerta para documentação incompleta antes de enviar a autorização, e (3) rastreia glosas por tipo e convênio para identificar padrões de inconsistência, reduzem significativamente o índice de glosa e o prazo de recebimento."),
        ("Cirurgia Ambulatorial Ortopédica: Modelo de Alto Volume",
         "A ortopedia tem um dos maiores volumes de cirurgia ambulatorial do mercado médico privado: artroscopia de joelho e ombro, reparo de ligamentos, cirurgias de mão e punho, e procedimentos de coluna minimamente invasivos podem ser realizados em centro cirúrgico ambulatorial (CCA) — sem internação hospitalar, com alta no mesmo dia ou no dia seguinte. O modelo de CCA tem margens melhores que o hospital para o cirurgião e o paciente paga ou é reembolsado mais facilmente pelo convênio em alguns casos. A gestão do CCA exige: escala cirúrgica eficiente (múltiplos cirurgiões x múltiplas salas com turnover rápido), gestão de kit cirúrgico (materiais específicos por tipo de cirurgia — artroscópio, implantes, fios), controle de OPME (Órteses, Próteses e Materiais Especiais — com rastreabilidade de lote exigida pela ANVISA), e gestão de anestesia e de equipe de enfermagem."),
        ("Medicina Esportiva: O Segmento de Maior Crescimento",
         "A medicina esportiva cresceu impulsionada pelo boom das maratonas, triathlons, crossfit e outros esportes amadores: o Brasil tem mais de 5 milhões de corredores ativos e um mercado de medicina preventiva esportiva em expansão. As clínicas de medicina esportiva oferecem: avaliação de aptidão física (ergoespirometria — VO2 máx, limiar anaeróbico), avaliação biomecânica de corrida (análise de pisada, cinética da corrida), nutrição esportiva integrada, fisiologia do exercício (periodização de treino para melhorar performance), e reabilitação esportiva de lesões. O cliente de medicina esportiva tem perfil diferente do ortopédico convencional: é mais jovem, mais digital, paga particular com mais frequência, e valoriza dados e tecnologia (integração com wearables como Garmin, Apple Watch, Whoop é diferencial crescente).")
        ,
        ("Indicadores de Performance em Ortopedia",
         "As métricas clínicas incluem: taxa de complicações cirúrgicas (infecção pós-operatória deve ser abaixo de 1% para cirurgias eletivas de joelho e ombro), taxa de revisão de cirurgia (o paciente precisou de nova cirurgia no mesmo segmento em menos de 2 anos?), e NPS. As métricas de negócio incluem: taxa de autorização de cirurgia no primeiro pedido ao convênio (indicador de qualidade da documentação clínica — alta na primeira tentativa reduz o ciclo de receita), índice de glosa (valor glosado como percentual do faturado — abaixo de 3% é benchmar saudável), receita por sala cirúrgica por dia, e mix de procedimentos (cirurgias de artroplastia têm OPME de alto custo que pode comprimir a margem — o mix cirúrgico impacta diretamente a rentabilidade).")
    ],
    faq_list=[
        ("Artroscopia de joelho tem cobertura pelo plano de saúde?",
         "Sim — a artroscopia de joelho (procedimento minimamente invasivo para diagnóstico e tratamento de lesões de menisco, LCA e cartilagem) está no Rol de Procedimentos da ANS e deve ser coberta por planos com cobertura cirúrgica. A cobertura inclui o procedimento cirúrgico, a anestesia e o OPME básico (implantes e fios necessários para o reparo). Implantes de alta tecnologia (enxertos de ligamento de origem biológica específica, implantes de cartilagem de nova geração) podem ter cobertura parcial ou negada — o paciente paga a diferença ou o cirurgião usa o material coberto. A autorização prévia pelo convênio é obrigatória para procedimentos eletivos — o processo pode levar de 3 a 15 dias úteis dependendo da operadora. Convênios que usam mais frequentemente auditorias prévias (Unimed, Sul América) têm processos mais lentos mas glosa menor pós-procedimento."),
        ("Quando é necessária cirurgia para lesão de LCA?",
         "A lesão de LCA (Ligamento Cruzado Anterior) do joelho é uma das lesões esportivas mais comuns — especialmente em futebol, handball, basquete e esqui. A indicação de cirurgia (reconstrução do LCA com enxerto) depende: do nível de atividade do paciente (atleta jovem que quer voltar a praticar esportes de pivô tem indicação mais clara do que idoso sedentário), da instabilidade funcional (joelho instável no dia a dia — dificuldade para subir escadas, virar o corpo — tem indicação mais forte de cirurgia), e de lesões associadas (menisco ou cartilagem lesados junto com o LCA fortalecem a indicação cirúrgica). Pacientes idosos com vida sedentária e LCA roto mas joelho estável podem ser tratados com reabilitação conservadora (fisioterapia de fortalecimento muscular) sem reconstrução cirúrgica."),
        ("O que é OPME e por que é tão regulado?",
         "OPME (Órteses, Próteses e Materiais Especiais) são os implantes e dispositivos médicos usados em cirurgias ortopédicas: próteses de quadril e joelho, parafusos de titânio para fixação de fraturas, âncoras para reparo de ligamentos, malhas de reforço para cirurgia de coluna. São altamente regulados porque: têm custos elevados (uma prótese de joelho custa de R$8 mil a R$80 mil dependendo da tecnologia), existem conflitos de interesse históricos na indicação (médico recebia comissão do fornecedor para indicar determinado implante — prática proibida pela ANS e pelo CFM), e a rastreabilidade é obrigatória (ANVISA exige que cada implante tenha número de lote vinculado ao prontuário do paciente para rastreamento em caso de recall). A Resolução ANS 389/2015 criou regras para padronização de OPME nos planos de saúde — o médico deve justificar a escolha do implante específico que não está na padronização do plano.")
    ]
)

# Article 4717 — SaaS sales: Accounting offices and financial software
art(
    slug="vendas-para-o-setor-de-saas-de-contabilidade-e-gestao-financeira-empresarial",
    title="Vendas para o Setor de SaaS de Contabilidade e Gestão Financeira Empresarial",
    desc="Estratégias de vendas B2B para plataformas SaaS de contabilidade e gestão financeira empresarial: como abordar escritórios contábeis, CFOs e PMEs para fechar contratos.",
    h1="Vendas para o Setor de SaaS de Contabilidade e Gestão Financeira Empresarial",
    lead="O Brasil tem mais de 65 mil escritórios de contabilidade e mais de 500 mil empresas que precisam de gestão financeira profissional. Plataformas de contabilidade e gestão financeira SaaS têm um mercado imenso — mas vender para contadores e CFOs exige navegar alta exigência técnica, compliance rigoroso e relações de longa duração.",
    sections=[
        ("O Ecossistema de FinTech B2B e Contabilidade SaaS",
         "O mercado de SaaS para contabilidade e finanças empresariais inclui: ERP financeiro para PMEs (contas a pagar, contas a receber, fluxo de caixa, DRE — como Omie, Conta Azul, Nibo), plataformas de contabilidade para escritórios contábeis (gestão de clientes, lançamentos contábeis, geração de obrigações acessórias — SPED, ECF, ECD, DCTF — como Domínio, Alterdata, Thomson Reuters Onvio), conciliação bancária e integração com Open Finance (importação automática de extratos bancários para reconciliação), gestão de notas fiscais (emissão de NF-e, NFS-e, CF-e, CT-e — integrado com SEFAZ), folha de pagamento (eSocial, GFIP, SEFIP — geralmente integrado ao ERP), e BI e dashboard financeiro (análise de desempenho financeiro — DRE, balanço, análise de liquidez e margem). O ecossistema fiscal e tributário brasileiro é um dos mais complexos do mundo — criando oportunidade enorme para automação e compliance software."),
        ("O Escritório Contábil como Canal e como Cliente",
         "O escritório contábil brasileiro ocupa um papel duplo no mercado de SaaS financeiro: é cliente (precisa de software para gerir seus próprios processos — folha, obrigações acessórias, atendimento ao cliente contábil) e é canal de distribuição (recomenda ou vende ERP financeiro para seus clientes PMEs). Plataformas como Omie e Conta Azul construíram parte de seu crescimento via parceria com escritórios contábeis — o contador recomenda o ERP para seus clientes, recebe comissão de indicação, e os dados da empresa cliente ficam integrados ao sistema do contador (reduzindo o retrabalho de lançamentos manuais). O modelo de parceria 'escritório contábil como distribuidor' é um dos mais eficientes em FinTech B2B — o contador tem credibilidade e acesso ao decisor financeiro de dezenas de empresas clientes."),
        ("SPED e Obrigações Acessórias: O Coração da Demanda",
         "As obrigações acessórias brasileiras são o principal driver de adoção de software contábil: SPED (Sistema Público de Escrituração Digital — que inclui ECD, ECF, EFD ICMS/IPI, EFD Contribuições), DCTF (Declaração de Débitos e Créditos Tributários Federais), RAIS, CAGED, eSocial, DIRF — são dezenas de obrigações com prazos rígidos e penalidades por atraso. A complexidade tributária brasileira (Simples Nacional, Lucro Presumido, Lucro Real — cada um com regras diferentes de apuração) cria uma demanda constante por software que automatize o cumprimento dessas obrigações. Plataformas que integram dados fiscais diretamente da SEFAZ (download automático de NF-e emitidas e recebidas), eliminam retrabalho de lançamento manual e geram as obrigações automaticamente a partir dos dados transacionais, têm proposta de valor concreta e mensurável para o contador."),
        ("CFO de PME: O Comprador de Gestão Financeira",
         "O CFO ou gestor financeiro de PME é o comprador de ERP financeiro — e tem necessidades distintas do contador. O CFO quer: visibilidade em tempo real do fluxo de caixa (não esperar o balancete mensal do contador), DRE gerencial (não contábil — focada em entender a rentabilidade do negócio), painel de contas a receber com aging (quem deve, quanto e há quanto tempo), gestão de múltiplos bancos em um único painel (reconciliação automática via Open Finance — Pix, boleto, cartão), e integração com o sistema operacional da empresa (ERP de operações, sistema de vendas, CRM). A principal objeção do CFO de PME é 'já tenho planilha Excel e o contador faz o resto' — o argumento para superar essa objeção é o tempo perdido nas planilhas e a falta de visibilidade em tempo real que Excel não oferece."),
        ("Métricas de Sucesso em FinTech B2B SaaS",
         "As métricas de produto incluem: transações financeiras processadas por mês (volume que cresce com o negócio do cliente — expansão natural), documentos fiscais emitidos (NF-e, NFS-e — indicador de uso ativo do módulo fiscal), e NPS de contadores e gestores financeiros. As métricas de negócio incluem: MRR por tamanho de empresa (PME de R$1M de faturamento tem ticket diferente de empresa de R$20M), churn por encerramente de empresa (PMEs fecham com frequência — churn bruto relevante em FinTech B2B), NRR via expansão de módulos (empresa que começa com financeiro básico adiciona folha, gestão de estoque, BI), e CAC por canal — parceiros contábeis têm CAC 3 a 5x menor e LTV significativamente maior do que aquisição direta.")
    ],
    faq_list=[
        ("Qual a diferença entre ERP e software de contabilidade?",
         "Software de contabilidade (ou software contábil) é focado nas necessidades do contador: escrituração contábil (lançamentos, razão, balancete), geração de demonstrações financeiras (balanço patrimonial, DRE, DFC), e cumprimento de obrigações acessórias (SPED, ECF, ECD). É o sistema do escritório de contabilidade. ERP (Enterprise Resource Planning) financeiro para PMEs é focado nas necessidades operacionais da empresa: emissão de notas fiscais, contas a receber, contas a pagar, fluxo de caixa, gestão de estoques, pedidos de venda. O ERP gera os dados financeiros que depois são importados pelo sistema do contador para a escrituração contábil. Em empresas de maior porte, o ERP integra todos os módulos (financeiro, produção, RH, vendas) em uma única base de dados — eliminando a necessidade de integração entre sistemas separados."),
        ("Open Finance vai eliminar a necessidade de conciliação bancária manual?",
         "O Open Finance (anteriormente Open Banking) é o sistema regulamentado pelo BACEN que permite que empresas e pessoas autorizem o compartilhamento de seus dados bancários entre instituições. Para empresas, o Open Finance permite que o ERP financeiro conecte diretamente com todos os bancos da empresa (Bradesco, Itaú, Santander, Banco do Brasil, contas digitais) e importe extratos automaticamente — eliminando a necessidade de baixar OFX ou CSV manualmente. Isso automatiza 80% do trabalho de conciliação bancária. O Open Finance está em expansão no Brasil desde 2021 — com adesão crescente de instituições financeiras e empresas usuárias. Plataformas de gestão financeira que integraram o Open Finance oferecem conciliação automática em tempo real — um diferencial operacional concreto para o gestor financeiro."),
        ("Simples Nacional, Lucro Presumido ou Lucro Real: como escolher?",
         "O regime tributário é uma decisão estratégica que impacta significativamente a carga tributária da empresa. Simples Nacional é destinado a empresas com faturamento anual até R$4,8 milhões — simplifica o recolhimento em um único DAS (que cobre IRPJ, CSLL, PIS, COFINS, ICMS, ISS e INSS patronal). Lucro Presumido é permitido até R$78 milhões de faturamento anual — tributa o lucro com base em uma margem presumida definida pela lei (32% para serviços, 8% para comércio) — vantajoso para empresas com margem real acima da presumida. Lucro Real é obrigatório para empresas acima de R$78 milhões e para determinadas atividades (bancos, factoring) — tributa o lucro real apurado contabilmente — vantajoso para empresas com prejuízo ou com margem real abaixo da presumida. A escolha deve ser feita anualmente com o contador — analisando a margem real, o setor e as especificidades tributárias da atividade.")
    ]
)

# Article 4718 — Consulting: ESG and sustainability
art(
    slug="consultoria-de-esg-e-sustentabilidade-corporativa",
    title="Consultoria de ESG e Sustentabilidade Corporativa",
    desc="Como funciona a consultoria de ESG e sustentabilidade corporativa: diagnóstico de materialidade, estratégia ESG, relatórios GRI e SASB, e como ESG impacta o acesso a capital.",
    h1="Consultoria de ESG e Sustentabilidade Corporativa",
    lead="ESG (Environmental, Social and Governance) deixou de ser diferencial para se tornar requisito de acesso a capital e mercados. Consultorias de ESG ajudam empresas a diagnosticar sua posição atual, definir estratégia e metas, implantar práticas sustentáveis, e comunicar o progresso para investidores, clientes e reguladores com credibilidade.",
    sections=[
        ("O que é Consultoria de ESG e Para que Serve",
         "A consultoria de ESG atua nas três dimensões: Ambiental (E) — redução de emissões de carbono (Scopes 1, 2 e 3), gestão de recursos hídricos, gestão de resíduos, biodiversidade, economia circular; Social (S) — diversidade e inclusão (D&I), condições de trabalho na cadeia de fornecedores, impacto nas comunidades, relação com clientes e privacidade de dados; e Governança (G) — estrutura do conselho de administração, remuneração executiva, combate à corrupção, transparência e ética nos negócios, gestão de riscos. O trabalho da consultoria inclui: diagnóstico de materialidade ESG (quais temas são mais relevantes para o setor e para os stakeholders da empresa), definição de estratégia e metas ESG, implementação de gestão de dados ESG, elaboração de relatórios (GRI, SASB, TCFD, CDP), e preparação para avaliações de agências de rating ESG (MSCI, Sustainalytics, ISS, B Lab para certificação B Corp)."),
        ("Análise de Materialidade: O Ponto de Partida",
         "A análise de materialidade ESG identifica quais temas ambientais, sociais e de governança são mais relevantes para o negócio e para os stakeholders — priorizando onde a empresa deve focar esforço e comunicação. A metodologia GRI (Global Reporting Initiative) define materialidade como os temas que têm impacto significativo na economia, no meio ambiente e nas pessoas, e que influenciam as avaliações dos stakeholders. O processo inclui: levantamento de temas relevantes do setor (comparativo com pares e com reguladores), engajamento de stakeholders (entrevistas com investidores, clientes, colaboradores, fornecedores, comunidades), avaliação de impacto e relevância, e validação pela liderança da empresa. A matriz de materialidade — que cruza relevância para stakeholders vs. impacto no negócio — é o entregável central que orienta a estratégia ESG."),
        ("Descarbonização: Scopes 1, 2 e 3",
         "A gestão de emissões de carbono é estruturada em três escopos: Scope 1 são as emissões diretas da empresa (combustão na frota própria, processo industrial próprio, gás refrigerante de ar-condicionado), Scope 2 são as emissões indiretas de energia adquirida (eletricidade comprada da rede — cujas emissões dependem da matriz elétrica do país ou do estado), e Scope 3 são todas as outras emissões indiretas da cadeia de valor (viagens de colaboradores, logística de fornecedores, uso dos produtos pelos clientes, descarte dos produtos no fim de vida). O Scope 3 representa em média 70% a 90% das emissões totais das empresas — e é o mais difícil de medir e reduzir porque depende de fornecedores e clientes. O Acordo de Paris estabelece meta de carbono neutro até 2050 — empresas que anunciam 'net zero 2030' ou 'net zero 2040' precisam de plano de descarbonização robusto para não sofrerem acusações de greenwashing."),
        ("ESG e Acesso a Capital: O Driver Financeiro",
         "O alinhamento com ESG tornou-se requisito de acesso a capital em diversas frentes: fundos de investimento ESG (que só investem em empresas com mínimo de rating ESG), financiamentos verdes e sustentáveis (BNDES Fundo Clima, títulos verdes — green bonds, social bonds — com juros menores para projetos alinhados a critérios ESG), clientes corporativos que exigem evidência de sustentabilidade dos fornecedores (especialmente para exportação para a UE e EUA, onde a pressão ESG da cadeia de fornecimento é forte), e regulação crescente (a CVM passou a exigir relatório de sustentabilidade para empresas de capital aberto — e a tendência é de expansão para empresas de médio porte). A consultoria de ESG que demonstra o impacto do ESG no custo de capital e no acesso a novos mercados tem argumento financeiro para o CFO — não apenas argumento de propósito para o CEO."),
        ("Relatórios ESG: GRI, SASB, TCFD e IFRS S",
         "Os principais frameworks de reporte ESG incluem: GRI (Global Reporting Initiative) — o mais usado globalmente, estrutura modular com padrões universais e setoriais; SASB (Sustainability Accounting Standards Board) — focado nos temas materiais específicos de cada setor, orientado ao investidor; TCFD (Task Force on Climate-related Financial Disclosures) — focado em riscos e oportunidades climáticos, obrigatório ou recomendado por reguladores de vários países; e IFRS S1 e S2 — os novos padrões do ISSB (International Sustainability Standards Board), que em 2024 se tornaram o padrão global de reporte sustentável recomendado. Empresas de capital aberto no Brasil seguem as exigências da CVM. Para empresas de capital fechado, a escolha do framework depende dos stakeholders: investidores privados e de private equity tendem a preferir SASB e TCFD; clientes de grandes varejistas europeus seguem GRI.")
    ],
    faq_list=[
        ("ESG é obrigatório para empresas brasileiras?",
         "Depende do tipo de empresa. Para empresas de capital aberto (listadas na B3), a CVM (Comissão de Valores Mobiliários) exige desde 2023 que as empresas divulguem informações ESG no Formulário de Referência — incluindo práticas relacionadas ao meio ambiente, diversidade no conselho e gestão de riscos socioambientais. A Resolução CVM 59/2021 instituiu o 'relate ou explique' para reporte climático baseado no TCFD. Para empresas de capital fechado, não há obrigação legal de reporte ESG no Brasil atualmente — mas a pressão vem de: investidores (fundos de PE/VC com mandato ESG), clientes corporativos (que exigem questionários de sustentabilidade dos fornecedores), e bancos (que vinculam condições de financiamento a critérios ESG). A tendência regulatória é de expansão gradual da obrigatoriedade, seguindo o modelo europeu (CSRD — Corporate Sustainability Reporting Directive)."),
        ("O que é greenwashing e como evitá-lo?",
         "Greenwashing é a prática de comunicar compromissos ou realizações ambientais que não correspondem à realidade — seja por exagero, por falta de evidência ou por seletividade intencional. Exemplos: empresa que anuncia 'carbono neutro' sem inventário de emissões verificado por terceiros; produto rotulado como 'sustentável' sem certificação ou critério claro; empresa que destaca ações ambientais menores para desviar atenção de impactos negativos maiores. A consultoria de ESG responsável ajuda a empresa a comunicar apenas o que tem evidência verificável — e a ter planos concretos de ação para as lacunas. O greenwashing tem risco crescente no Brasil: o CONAR regula publicidade ambiental enganosa, e a CVM fiscaliza afirmações ESG em documentos de emissores de valores mobiliários. Internacionalmente, a UE aprovou a Diretiva Green Claims (2024) que impõe obrigações específicas para alegações ambientais."),
        ("Certificação B Corp vale a pena para empresas brasileiras?",
         "A certificação B Corp (B Corporation) é concedida pela B Lab para empresas que atendem a padrões rigorosos de desempenho social, ambiental e de governança — avaliados pelo BIA (B Impact Assessment). É uma certificação voluntária, diferente da criação de uma Empresa B (que é um tipo societário disponível em alguns países — no Brasil ainda em discussão legal). As vantagens da certificação B Corp incluem: credencial internacional reconhecida por investidores e clientes globais, acesso à rede global de B Corps (empresas comprometidas com o movimento), vantagem competitiva com consumidores e clientes B2B com perfil ESG, e framework estruturado de melhoria contínua. Os custos incluem a taxa anual de certificação (baseada no faturamento) e o investimento para adequar as práticas ao padrão exigido (que é alto — score mínimo de 80 pontos em 200). No Brasil, há mais de 200 empresas B Corp certificadas — crescimento acelerado nos últimos 3 anos.")
    ]
)

# ── Sitemap & trilha update ──────────────────────────────────────────────────
sitemap_path = pathlib.Path(__file__).parent / "sitemap.xml"
trilha_path  = pathlib.Path(__file__).parent / "trilha.html"

new_slugs = [
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-imobiliarias-e-gestao-de-imoveis",
     "Gestão de Negócios de Empresa de B2B SaaS de Imobiliárias e Gestão de Imóveis"),
    ("gestao-de-clinicas-de-endocrinologia-e-doencas-metabolicas",
     "Gestão de Clínicas de Endocrinologia e Doenças Metabólicas"),
    ("vendas-para-o-setor-de-saas-de-saude-mental-e-psicologia",
     "Vendas para o Setor de SaaS de Saúde Mental e Psicologia"),
    ("consultoria-de-cultura-organizacional-e-gestao-de-mudancas",
     "Consultoria de Cultura Organizacional e Gestão de Mudanças"),
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-clinicas-veterinarias",
     "Gestão de Negócios de Empresa de B2B SaaS de Clínicas Veterinárias"),
    ("gestao-de-clinicas-de-ortopedia-e-medicina-esportiva",
     "Gestão de Clínicas de Ortopedia e Medicina Esportiva"),
    ("vendas-para-o-setor-de-saas-de-contabilidade-e-gestao-financeira-empresarial",
     "Vendas para o Setor de SaaS de Contabilidade e Gestão Financeira Empresarial"),
    ("consultoria-de-esg-e-sustentabilidade-corporativa",
     "Consultoria de ESG e Sustentabilidade Corporativa"),
]

sm = sitemap_path.read_text(encoding="utf-8")
new_urls = "".join(
    f"  <url><loc>https://produtovivo.com.br/blog/{s}/</loc></url>\n"
    for s, _ in new_slugs
)
sitemap_path.write_text(sm.replace("</urlset>", new_urls + "</urlset>"), encoding="utf-8")

tr = trilha_path.read_text(encoding="utf-8")
new_items = "".join(
    f'  <li><a href="/blog/{s}/">{t}</a></li>\n'
    for s, t in new_slugs
)
trilha_path.write_text(tr.replace("</ul>", new_items + "\n</ul>", 1), encoding="utf-8")

print("Done — batch 1614")
