import os, json

BASE   = os.path.join(os.path.dirname(__file__), "blog")
DOMAIN = "https://produtovivo.com.br"
PIXEL  = "4520253334926563"

TMPL = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<!-- Facebook Pixel Code -->
<script>!function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)}};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','{pixel}');fbq('track','PageView');</script>
<style>
body{{font-family:Arial,sans-serif;margin:0;padding:0;color:#222;}}
header{{background:#1a1a2e;color:#fff;padding:16px 24px;}}
header a{{color:#e0e0ff;text-decoration:none;font-weight:bold;font-size:1.2rem;}}
main{{max-width:860px;margin:40px auto;padding:0 20px;}}
h1{{font-size:2rem;color:#1a1a2e;}}
.lead{{font-size:1.1rem;color:#444;margin-bottom:28px;}}
h2{{color:#16213e;margin-top:32px;}}
.faq{{background:#f5f7ff;border-radius:8px;padding:24px;margin-top:40px;}}
.faq h2{{color:#1a1a2e;margin-top:0;}}
.faq-item{{margin-bottom:18px;}}
.faq-item h3{{margin:0 0 6px;color:#16213e;}}
footer{{text-align:center;padding:24px;color:#888;font-size:.9rem;margin-top:60px;border-top:1px solid #eee;}}
footer a{{color:#555;}}
</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<header><a href="/">ProdutoVivo</a></header>
<main>
<h1>{h1}</h1>
<p class="lead">{lead}</p>
{body}
<div class="faq">
<h2>Perguntas Frequentes</h2>
{faqs}
</div>
</main>
<footer><p>&copy; 2025 ProdutoVivo &mdash; <a href="/blog/">Blog</a> | <a href="/trilha">Trilha Gratuita</a></p></footer>
</body>
</html>"""

def art(slug, title, desc, h1, lead, sections, faq_list):
    url = f"{DOMAIN}/blog/{slug}/"
    body_html = ""
    for sec_title, sec_body in sections:
        body_html += f"<h2>{sec_title}</h2>\n<p>{sec_body}</p>\n"
    faqs_html = ""
    schema_faqs = []
    for q, a in faq_list:
        faqs_html += f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>\n'
        schema_faqs.append({"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}})
    schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": schema_faqs}, ensure_ascii=False)
    html = TMPL.format(title=title, desc=desc, url=url, pixel=PIXEL,
                       h1=h1, lead=lead, body=body_html, faqs=faqs_html, schema=schema)
    out_dir = os.path.join(BASE, slug)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

# Article 4311 — B2B SaaS: customer data platform (CDP) e personalização
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-customer-data-platform-e-personalizacao",
    title="Gestão de Negócios para Empresas de B2B SaaS de Customer Data Platform e Personalização | ProdutoVivo",
    desc="Como escalar um negócio de B2B SaaS de Customer Data Platform (CDP) e personalização: modelo de receita, go-to-market e diferenciação competitiva.",
    h1="Gestão de Negócios para Empresas de B2B SaaS de Customer Data Platform e Personalização",
    lead="Customer Data Platforms (CDPs) são a espinha dorsal da personalização em escala — unificando dados de clientes de todas as fontes (CRM, e-commerce, app, mídia paga) em perfis únicos que habilitam comunicação e ofertas personalizadas. Com a deprecação dos cookies de terceiros e a consolidação da LGPD, CDPs de first-party data são um dos segmentos SaaS de maior crescimento no Brasil e no mundo.",
    sections=[
        ("O Que é um CDP e Por Que as Empresas Precisam", "Um CDP é uma plataforma que coleta, unifica e ativa dados de clientes em tempo real. Diferente de um CRM (que gerencia relacionamentos comerciais) ou de um DMP (Data Management Platform, focado em dados de terceiros), o CDP constrói perfis individuais e persistentes de clientes unificando dados de todas as touchpoints — site, app, ponto de venda, call center, e-mail — e disponibiliza esses perfis para qualquer sistema downstream (plataforma de e-mail, mídia paga, CRM, atendimento)."),
        ("Mercado de CDP no Brasil: Oportunidade e Timing", "A deprecação dos cookies de terceiros pelo Google Chrome (prevista para 2024-2025) e a LGPD criaram o timing perfeito para CDPs de first-party data no Brasil. Empresas de varejo, financeiro e telecom que dependiam de audiências de terceiros para personalização estão investindo massivamente em coleta e ativação de dados próprios. O mercado global de CDP cresce a 30% ao ano — no Brasil, ainda está em fase inicial com pouquíssimos players locais especializados."),
        ("Modelo de Receita em CDP SaaS", "Os modelos mais comuns são: (1) Por volume de perfis ativos (MAU — Monthly Active Users/Profiles) na plataforma; (2) Por volume de eventos processados por mês (cliques, compras, visualizações de página); (3) Por número de canais de ativação conectados. Ticket médio para empresas de médio porte: R$ 8.000 a R$ 30.000/mês. Para enterprises com volume massivo de dados (e-commerce de grande porte, operadoras de telecom): R$ 50.000 a R$ 200.000/mês. Implementação e onboarding são serviços adicionais significativos."),
        ("Go-to-Market: CMO, Chief Data Officer e Growth", "O comprador principal é o CMO (para casos de uso de marketing) ou o Chief Data Officer (para estratégia de dados corporativa). Em empresas menores, o Head of Growth ou o Head of CRM são os influenciadores principais. O argumento de vendas tem dois ângulos: (1) eficiência de marketing — reduzir custo de aquisição via ativação de audiências próprias em mídia paga (lookalike de first-party data); (2) personalização de receita — aumentar conversão e LTV via recomendações personalizadas e comunicação relevante no momento certo."),
        ("Diferenciação: Resolução de Identidade e Ativação Omnichannel", "O principal diferencial técnico de CDPs é a resolução de identidade — a capacidade de reconhecer que o João que comprou no e-commerce, o João que abriu o e-mail e o João que visitou a loja física são a mesma pessoa. Isso requer algoritmos de matching probabilístico e determinístico sofisticados. O segundo diferencial é a amplitude de conectores de ativação — quantos sistemas downstream (Meta, Google, Salesforce, Braze, VTEX) a plataforma consegue alimentar com segmentos e perfis em tempo real."),
    ],
    faq_list=[
        ("Qual é a diferença entre CDP, CRM e DMP?", "CRM (Customer Relationship Management) gerencia interações comerciais e pipeline de vendas — focado no relacionamento B2B ou em dados de clientes identificados. DMP (Data Management Platform) gerencia dados de terceiros (cookies) para segmentação de mídia paga — está em declínio com a deprecação dos cookies. CDP unifica todos os dados de primeira parte em perfis individuais persistentes e os ativa em qualquer canal — é a evolução que substitui parcialmente o DMP e complementa o CRM com dados comportamentais ricos."),
        ("Como o CDP ajuda uma empresa a se adaptar ao mundo sem cookies de terceiros?", "O CDP habilita: (1) coleta e enriquecimento de dados próprios (first-party data) via formulários, login, engajamento no site; (2) criação de audiências de lookalike baseadas em clientes existentes (em vez de dados de terceiros) para mídia paga no Meta e Google; (3) reconhecimento de visitantes conhecidos no site mesmo sem cookies (via e-mail hash ou login); (4) personalização de conteúdo e ofertas baseada em comportamento histórico armazenado no CDP — substituindo a personalização que antes dependia de cookies de terceiros."),
        ("Quanto tempo leva a implementação de um CDP e quais são as principais dificuldades?", "Uma implementação básica de CDP (integração de 3 a 5 fontes de dados, criação de perfis e 2 a 3 casos de uso de ativação) leva de 3 a 6 meses. As principais dificuldades são: qualidade e consistência dos dados nas fontes (garbage in, garbage out), alinhamento de governança de dados entre marketing, TI e privacidade (LGPD), definição dos casos de uso prioritários antes de começar a implementação, e mudança organizacional para que equipes de marketing passem a trabalhar com dados de forma mais estruturada."),
    ]
)

# Article 4312 — Clinic: medicina integrativa e fitoterapia clínica
art(
    slug="gestao-de-clinicas-de-medicina-integrativa-e-fitoterapia-clinica",
    title="Gestão de Clínicas de Medicina Integrativa e Fitoterapia Clínica | ProdutoVivo",
    desc="Guia de gestão para clínicas de medicina integrativa e fitoterapia clínica: estrutura de serviços, regulamentação das PICS, faturamento e captação de pacientes.",
    h1="Gestão de Clínicas de Medicina Integrativa e Fitoterapia Clínica",
    lead="A medicina integrativa — que combina medicina convencional com Práticas Integrativas e Complementares (PICS) como acupuntura, fitoterapia, homeopatia e medicina ayurvédica — está em crescimento acelerado no Brasil. A PNPIC (Política Nacional de Práticas Integrativas e Complementares do SUS) expandiu o rol de PICS cobertas, e a demanda por abordagens holísticas de saúde cresce especialmente em centros urbanos.",
    sections=[
        ("Portfolio de Serviços em Medicina Integrativa", "Uma clínica de medicina integrativa pode oferecer: consultas de medicina integrativa (médico com formação em PICS), acupuntura (médicos e fisioterapeutas acupunturistas), fitoterapia clínica (médicos e farmacêuticos com formação em plantas medicinais), auriculoterapia, homeopatia, medicina ayurvédica, yoga terapêutico e meditação orientada. A combinação de consultas médicas com terapias complementares cria um serviço diferenciado com alto valor percebido pelo paciente e menor cobertura por planos de saúde — aumentando o mix particular."),
        ("Regulamentação das PICS no Brasil", "O CFM reconhece como especialidades médicas: acupuntura, homeopatia, medicina antroposófica e fitoterapia (por resolução). Fisioterapeutas têm reconhecimento do COFFITO para acupuntura. A ANVISA regula os fitoterápicos — medicamentos e cosméticos à base de plantas. Clínicas que oferecem fitoterapia clínica devem ter farmacêutico responsável pela dispensação de fitoterápicos manipulados (parceria com farmácia de manipulação). O compliance regulatório é fundamental para proteger a clínica e os pacientes."),
        ("Fitoterapia Clínica: Do Diagnóstico à Prescrição", "A fitoterapia clínica é a prática mais difundida das PICS — médicos e farmacêuticos clínicos prescrevem plantas medicinais com base em evidências científicas para complementar o tratamento convencional. Os fitoterápicos mais prescritos no Brasil incluem: Passiflora (ansiedade), Valeriana (insônia), Ginkgo biloba (cognição), Boswellia (artrite), Cúrcuma (inflamação) e Silimarina (proteção hepática). Parcerias com farmácias de manipulação permitem prescrições personalizadas e representam uma fonte de receita adicional via comissionamento."),
        ("Faturamento: Convênios, PICS e Particular", "A cobertura de PICS por planos de saúde ainda é limitada — a ANS incluiu algumas PICS no rol mínimo obrigatório (como acupuntura), mas a maioria das práticas é atendida no particular ou pelo SUS (PNPIC). Clínicas de medicina integrativa têm um mix de receita mais concentrado no particular (60 a 80%), o que exige estratégia de precificação e captação específica. O ticket de consulta integrativa (R$ 300 a R$ 600) é superior ao de especialidades convencionais, compensando parcialmente a menor cobertura por convênios."),
        ("Captação de Pacientes para Medicina Integrativa", "O paciente de medicina integrativa busca ativamente soluções para condições crônicas não controladas pela medicina convencional — dores crônicas, ansiedade, insônia, síndrome do intestino irritável, fibromialgia. Produza conteúdo educativo sobre PICS para essas condições específicas no Instagram e YouTube — o engajamento com temas de medicina integrativa é muito alto nas redes sociais. Parcerias com centros de yoga, academias holísticas e empregadores com programas de bem-estar abrem canais de captação qualificados."),
    ],
    faq_list=[
        ("Quais PICS (Práticas Integrativas e Complementares) têm cobertura obrigatória pelos planos de saúde?", "A ANS incluiu no rol de procedimentos obrigatórios (Resolução Normativa 465/2021): acupuntura (com cobertura para as condições listadas no CID), homeopatia (consultas médicas homeopáticas) e algumas terapias de reabilitação com base em PICS. A maioria das outras PICS (fitoterapia, ayurveda, meditação terapêutica, yoga terapêutico) ainda não tem cobertura obrigatória pelos planos de saúde privados, mas é ofertada pelo SUS via PNPIC em algumas UBSs e ambulatórios especializados."),
        ("Um clínico geral pode prescrever fitoterapia sem especialização em PICS?", "Sim. Qualquer médico pode prescrever fitoterápicos registrados na ANVISA — da mesma forma que prescreve qualquer medicamento. No entanto, a prescrição adequada de plantas medicinais requer conhecimento sobre interações medicamentosas, contraindicações e posologias corretas. Cursos de fitoterapia clínica para médicos são oferecidos pela ASBRAN (Associação Brasileira de Nutrição), ABFIT e pela maioria das faculdades de medicina integrativa. A especialização eleva a qualidade da prescrição e a credibilidade da clínica."),
        ("Como estruturar uma parceria com farmácia de manipulação para oferecer fitoterapia clínica?", "Firme acordo com uma farmácia de manipulação da região: o médico prescreve a fórmula de fitoterapia personalizada (planta + dose + veículo), a farmácia manipula e entrega ao paciente. A clínica pode receber uma comissão por indicação (modelo de participação nos resultados — regulamentado pelo CFM para médicos dentro de limites éticos) ou simplesmente fortalecer o serviço clínico com o diferencial da fitoterapia personalizada. A rastreabilidade das prescrições e dos resultados clínicos é parte do prontuário da clínica."),
    ]
)

# Article 4313 — SaaS sales: clínicas de ortopedia pediátrica
art(
    slug="vendas-para-o-setor-de-saas-de-gestao-de-clinicas-de-ortopedia-pediatrica-e-deformidades",
    title="Vendas para SaaS de Gestão de Clínicas de Ortopedia Pediátrica e Deformidades | ProdutoVivo",
    desc="Como vender SaaS de gestão para clínicas de ortopedia pediátrica e deformidades congênitas: abordagem consultiva, demonstração de valor e estratégias de conversão.",
    h1="Vendas para SaaS de Gestão de Clínicas de Ortopedia Pediátrica e Deformidades",
    lead="Clínicas de ortopedia pediátrica atendem crianças com condições musculoesqueléticas congênitas e adquiridas — pé torto congênito, displasia do desenvolvimento do quadril, escoliose, paralisia cerebral com comprometimento ortopédico e epifisiólises. O acompanhamento longitudinal dessas condições, frequentemente até a fase adulta, cria um relacionamento clínico de longo prazo que demanda softwares com funcionalidades específicas para pediatria e ortopedia.",
    sections=[
        ("Particularidades Operacionais da Ortopedia Pediátrica", "A ortopedia pediátrica combina consultas ambulatoriais frequentes (acompanhamento do crescimento esquelético), procedimentos de gesso e orteses (imobilização de fraturas, tratamento de pé torto pelo método Ponseti), cirurgias ortopédicas em centros cirúrgicos pediátricos e fisioterapia de reabilitação pós-cirúrgica. Cada etapa tem documentação específica — gráficos de crescimento esquelético (método de Risser para maturidade óssea), ângulos de curvatura (Cobb para escoliose) e escalas funcionais pediátricas."),
        ("Mapeamento do Decisor: Ortopedista Pediátrico e Pais", "O decisor de compra é o ortopedista pediátrico — frequentemente sócio da clínica. Os pais têm alta influência indireta: uma experiência digital positiva (agendamento online, comunicação ágil, acesso ao prontuário e imagens) fideliza a família por anos. Aborde o ortopedista focando em: prontuário com evolução longitudinal gráfica (ângulo de Cobb ao longo do tempo, progressão da escoliose), controle de OPME (órteses, próteses e implantes pediátricos) e faturamento correto de cirurgias com rastreabilidade de material."),
        ("Demo: Evolução Longitudinal e Gráficos Clínicos", "Demonstre: (1) prontuário com linha do tempo de consultas e procedimentos (visão cronológica do tratamento — crítica para condições tratadas ao longo de 10 a 15 anos); (2) gráficos de evolução de escoliose (ângulo de Cobb por consulta com geração automática de curva de progressão); (3) integração com imagens de raio-X (DICOM) vinculadas à consulta no prontuário; (4) controle de aparelhos gessados (data de aplicação, retirada programada, alertas de prazo); (5) protocolo de Ponseti para pé torto (número de sessões e ângulos de correção por consulta)."),
        ("Faturamento Pediátrico: OPME Infantil e Tabelas Específicas", "OPME em ortopedia pediátrica tem especificidades: órteses de abduções para displasia de quadril, aparelhos de Milwaukee e Boston para escoliose, e implantes ortopédicos de crescimento (hastes telescópicas para escoliose de início precoce). A rastreabilidade de cada dispositivo por paciente é obrigatória pela ANVISA. Demonstre que o SaaS controla o inventário de órteses consignadas, vincula cada dispositivo ao prontuário do paciente e gera automaticamente a nota fiscal e o código de rastreamento do item."),
        ("Parcerias com Hospitais Pediátricos e Centros de Referência", "Ortopedistas pediátricos operam frequentemente em múltiplos locais: consultório ambulatorial e hospital pediátrico de referência. O SaaS deve funcionar em ambos os ambientes — com sincronização de prontuário entre o consultório e o hospital. Parcerias com hospitais pediátricos de referência (como AACD, SARHA, hospitais universitários pediátricos) geram fluxo constante de pacientes com condições complexas — e esses hospitais frequentemente indicam o sistema que o cirurgião usa no consultório para toda a rede."),
    ],
    faq_list=[
        ("Quais são as condições ortopédicas pediátricas mais prevalentes que geram demanda ambulatorial?", "As condições mais prevalentes são: deformidades dos pés (pé torto congênito — tratado pelo método Ponseti; metatarso aduto; pé plano patológico), displasia do desenvolvimento do quadril (DDQ — diagnóstico e tratamento até os 18 meses), escoliose idiopática do adolescente (AIS), doenças de crescimento (doença de Osgood-Schlatter, doença de Sever, epifisiólises) e manifestações ortopédicas da paralisia cerebral (escoliose neuromuscular, contraturas de tendões). Cada condição tem um protocolo de acompanhamento específico."),
        ("Como o SaaS pode ajudar no método Ponseti para tratamento de pé torto congênito?", "O método Ponseti é um protocolo sequencial de gessos semanais (geralmente 5 a 7 gessos) seguidos de tenotomia percutânea e uso de órtese de abdução (Denis Browne) por anos. O prontuário especializado deve registrar: tipo e número de cada gesso, ângulos de correção alcançados, data e técnica da tenotomia, tipo e tamanho da órtese, e adesão à órtese (hora de uso/dia relatada pelos pais). Gráficos de progressão da correção são um diferencial que ortopedistas pediátricos valorizam muito em consultas de acompanhamento."),
        ("Qual é o impacto de não ter rastreabilidade adequada de OPME em ortopedia pediátrica?", "A falta de rastreabilidade de OPME expõe a clínica a dois riscos: (1) regulatório — a ANVISA pode exigir o rastreamento de um implante em caso de recall do fabricante, e a incapacidade de identificar os pacientes que receberam o dispositivo resulta em multa e interdição; (2) financeiro — OPME sem rastreabilidade são frequentemente glosados pelas operadoras (nota fiscal de OPME sem número de série vinculado ao prontuário é rejeitada). Em ortopedia pediátrica, onde os implantes são usados por décadas, a rastreabilidade longitudinal é especialmente crítica."),
    ]
)

# Article 4314 — Consulting: gestão de ESG e sustentabilidade empresarial
art(
    slug="consultoria-de-gestao-de-esg-e-sustentabilidade-empresarial",
    title="Consultoria de Gestão de ESG e Sustentabilidade Empresarial | ProdutoVivo",
    desc="Como estruturar e monetizar uma consultoria de ESG e sustentabilidade empresarial: frameworks GRI/SASB, inventário de carbono, relatórios e acesso a mercados exigentes.",
    h1="Consultoria de Gestão de ESG e Sustentabilidade Empresarial",
    lead="ESG (Environmental, Social and Governance) deixou de ser pauta de relações públicas para se tornar requisito de acesso a capital, mercados e cadeias de suprimento globais. Empresas que não conseguem reportar suas práticas de sustentabilidade perdem acesso a financiamentos, licitações e clientes corporativos. Consultorias de ESG têm demanda explosiva em todos os setores — especialmente no agronegócio, indústria e empresas que exportam ou captam investimentos.",
    sections=[
        ("O Que Abrange a Consultoria de ESG", "A consultoria de ESG cobre três dimensões: (1) Ambiental — inventário de emissões de gases de efeito estufa (Protocolo GHG, escopos 1, 2 e 3), análise de riscos climáticos (TCFD), gestão de recursos hídricos e resíduos, biodiversidade; (2) Social — gestão de saúde e segurança no trabalho, diversidade e inclusão, direitos humanos na cadeia de fornecimento; (3) Governança — ética e compliance, composição e independência do board, transparência e remuneração de executivos. A consultoria diagnostica, estrutura e reporta os indicadores ESG da empresa."),
        ("Inventário de Carbono: a Base do ESG Ambiental", "O inventário de emissões de GEE (Gases de Efeito Estufa) é o ponto de partida para qualquer empresa que quer gerenciar seu impacto ambiental. O Protocolo GHG (GHG Protocol) classifica as emissões em três escopos: Escopo 1 (emissões diretas — frota própria, caldeiras, processos industriais), Escopo 2 (energia elétrica comprada) e Escopo 3 (cadeia de valor — fornecedores, transporte de terceiros, uso do produto pelo cliente). O inventário de Escopo 3 é o mais complexo e representa 70 a 90% das emissões totais da maioria das empresas."),
        ("Frameworks de Reporte ESG: GRI, SASB, TCFD e ISSB", "Os principais frameworks de reporte são: GRI (Global Reporting Initiative) — o mais usado globalmente, com indicadores universais e setoriais; SASB (Sustainability Accounting Standards Board) — padrões setoriais específicos para investidores; TCFD (Task Force on Climate-related Financial Disclosures) — foco em riscos e oportunidades climáticas para o sistema financeiro; e ISSB (International Sustainability Standards Board) — os novos padrões globais da IFRS que deverão se tornar obrigatórios para empresas de capital aberto no Brasil. A consultoria orienta qual framework usar conforme o perfil e os objetivos da empresa."),
        ("ESG como Acesso a Capital e Mercados", "A demanda por consultoria de ESG é impulsionada por três gatilhos: (1) Investidores — fundos de PE, venture capital e bancos de desenvolvimento (BNDES, BID) exigem diagnóstico e roadmap de ESG como pré-requisito para investimento; (2) Clientes corporativos — grandes empresas (Unilever, Nestlé, Walmart) exigem que seus fornecedores comprovem conformidade com padrões ESG mínimos (especialmente trabalho infantil, desmatamento e pegada de carbono); (3) Regulação — CVM exige relatório de sustentabilidade de empresas abertas, e o Bacen tem normativas de risco socioambiental para instituições financeiras."),
        ("Monetização e Estrutura da Consultoria de ESG", "Projetos de diagnóstico ESG e materialidade: R$ 80 mil a R$ 250 mil. Inventário de carbono (escopos 1 e 2): R$ 40 mil a R$ 120 mil; Escopo 3: R$ 80 mil a R$ 300 mil adicional. Relatório de sustentabilidade (GRI): R$ 60 mil a R$ 200 mil. Programa de transformação ESG (2 a 3 anos): R$ 500 mil a R$ 2 milhões para grandes empresas. Retainer de monitoramento e atualização anual do inventário e do relatório: R$ 30 mil a R$ 100 mil/ano. Verificação externa das emissões por auditores independentes é um serviço adicional de alto valor."),
    ],
    faq_list=[
        ("O que é materialidade em ESG e por que é importante?", "A análise de materialidade identifica quais temas ESG são mais relevantes para o negócio da empresa e para seus stakeholders — cruzando o impacto do tema para a empresa (risco ou oportunidade financeira) com o impacto da empresa no tema (impacto social ou ambiental gerado). Os temas materiais são os que devem ser priorizados no programa de ESG e reportados no relatório de sustentabilidade. Empresas que reportam sem materialidade prévia correm o risco de divulgar muita informação irrelevante e omitir os temas que mais importam para investidores e clientes."),
        ("Qual é a diferença entre compensação de carbono e neutralidade de carbono?", "Compensação de carbono é a prática de adquirir créditos de carbono (de projetos de reflorestamento, energia renovável ou REDD+) para 'compensar' as emissões que a empresa não conseguiu eliminar. Neutralidade de carbono (net zero para determinado escopo) significa que as emissões restantes após todas as reduções possíveis são compensadas com créditos de alta qualidade. A diferença está na sequência: reduzir primeiro, compensar o que não pode ser reduzido. Empresas que apenas compensam sem reduzir enfrentam crescente crítica de 'greenwashing'."),
        ("Quando uma empresa de capital fechado precisa se preocupar com ESG?", "Imediatamente, se: exporta para mercados com exigências ambientais (Europa está aprovando o CBAM — Carbon Border Adjustment Mechanism); fornece para grandes corporações com programas de ESG em cadeia de valor (como as empresas listadas no Novo Mercado da B3); planeja captar investimento de fundos com mandato ESG ou acessar linhas de financiamento de BNDES ou BID com critérios socioambientais; ou quer se preparar para uma eventual abertura de capital — o ESG é requisito crescente no due diligence de IPOs e M&As."),
    ]
)

# Article 4315 — B2B SaaS: gestão de obras e construção civil (constructiontech)
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-gestao-de-obras-e-construcao-civil",
    title="Gestão de Negócios para Empresas de B2B SaaS de Gestão de Obras e Construção Civil | ProdutoVivo",
    desc="Como escalar um negócio de B2B SaaS de gestão de obras e construção civil: modelo de receita, verticais prioritárias e estratégias de crescimento.",
    h1="Gestão de Negócios para Empresas de B2B SaaS de Gestão de Obras e Construção Civil",
    lead="O setor de construção civil no Brasil representa 6% do PIB e é um dos mais atrasados digitalmente — apenas 5% das construtoras e incorporadoras usam softwares especializados de gestão de obras. SaaS de constructiontech têm oportunidade de modernizar processos de controle de obra, orçamentação, gestão de subcontratados e atendimento ao cliente em um mercado de R$ 500 bilhões anuais praticamente intocado pela transformação digital.",
    sections=[
        ("Segmentos do Mercado de Construção Civil", "O mercado se divide em: (1) Incorporadoras e construtoras residenciais (apartamentos, casas em condomínio) — maior volume de operações e demanda por CRM de relacionamento com compradores; (2) Construtoras comerciais e industriais — EPC de galpões, data centers, hospitais; (3) Obras de infraestrutura (rodovias, pontes, aeroportos) — contratos públicos com rigoroso controle de cronograma e medições; (4) Reformadoras e empresas de manutenção predial. Cada segmento tem um set de funcionalidades prioritárias e um perfil de comprador distinto."),
        ("Funcionalidades Essenciais de um SaaS de Obras", "As funcionalidades mais demandadas incluem: orçamento paramétrico (CUB e tabela SINAPI), cronograma físico-financeiro (Gantt integrado ao orçamento), controle de medições de subempreiteiros (BDI e composições unitárias), gestão de materiais (requisição, compra, estoque em obra), diário de obra digital, controle de RDO (Relatório Diário de Obra) com fotos geolocalizada, gestão de não conformidades (NCs de qualidade e segurança) e relatórios de progresso para incorporadoras e clientes. A integração com BIM (Building Information Modeling) é o diferencial enterprise."),
        ("Modelo de Receita em Constructiontech SaaS", "Os modelos mais comuns são: por obra ativa (R$ 500 a R$ 3.000/obra/mês dependendo do porte), por m² gerenciado, ou flat fee por empresa (R$ 3.000 a R$ 30.000/mês para construtoras com portfólio de obras). Módulos de CRM de relacionamento com comprador (para incorporadoras) têm modelos por unidade vendida ou por empreendimento. A implementação e o treinamento têm peso significativo no ticket inicial — obras têm alta rotatividade de pessoal e precisam de onboarding continuado."),
        ("Go-to-Market: Engenheiros de Obra e Diretores de Operações", "O comprador técnico é o Engenheiro de Obras ou Gerente de Projetos. O decisor financeiro é o Diretor de Operações ou o sócio. Construtoras são conservadoras na adoção de tecnologia — o ciclo de vendas é longo (60 a 180 dias) e a decisão frequentemente é feita com base em indicação de pares. Eventos setoriais (FIESP, CBIC, Expoabeeducar) e o ecossistema de associações do setor (SINDUSCON, ABRAMAT) são os canais de networking mais eficientes para o mercado de construção."),
        ("BIM e Integração como Diferencial Enterprise", "BIM (Building Information Modeling) é o futuro da gestão de obras — modelos 3D que integram projeto, cronograma e orçamento (BIM 4D e 5D). O governo federal exige BIM em obras públicas acima de R$ 75 milhões desde 2021 (Decreto 9.983/2019). SaaS que integram com ferramentas de BIM (Autodesk Revit, Navisworks, Edificius) e extraem automaticamente quantitativos e cronogramas do modelo têm vantagem competitiva crescente no segmento enterprise e em obras de infraestrutura pública."),
    ],
    faq_list=[
        ("Qual é a diferença entre um software de orçamentação e um SaaS de gestão de obras?", "Um software de orçamentação (como Volare, OrçaFácil, Sienge) é especializado em levantar quantitativos e calcular custos antes da obra começar. Um SaaS de gestão de obras gerencia a execução — controla o que foi planejado versus o que está sendo realizado (cronograma, custos, qualidade, segurança) durante toda a obra. Plataformas completas de constructiontech integram o orçamento inicial com o controle de execução, fechando o ciclo de planejamento e controle."),
        ("Como convencer uma construtora conservadora a adotar um SaaS de obras?", "Começe com o Diário de Obra Digital — a substituição do RDO em papel por registros digitais com fotos geolocalizadas é o caso de uso mais simples e com ROI mais imediato (1h/dia de engenheiro economizada em preenchimento manual de RDO). Isso cria familiaridade com a plataforma e abre caminho para a adoção de módulos mais complexos (cronograma, medições, materiais). O modelo de entrada freemium ou trial por 60 dias para uma obra piloto reduz a percepção de risco da adoção inicial."),
        ("O SaaS de construção civil precisa ser homologado pelo CREA ou por algum órgão regulador?", "Não há homologação específica de software pelo CREA. No entanto, para obras públicas com exigência de BIM (Decreto 9.983/2019), a plataforma deve ser compatível com os formatos de intercâmbio de dados BIM (IFC — Industry Foundation Classes) definidos nas especificações do contrato público. Para obras do Minha Casa Minha Vida e outros programas habitacionais do governo federal, a integração com o sistema de acompanhamento de obras do Ministério das Cidades pode ser requisito contratual."),
    ]
)

# Article 4316 — Clinic: nutrição clínica e transtornos alimentares
art(
    slug="gestao-de-clinicas-de-nutricao-clinica-e-transtornos-alimentares",
    title="Gestão de Clínicas de Nutrição Clínica e Transtornos Alimentares | ProdutoVivo",
    desc="Guia de gestão para clínicas de nutrição clínica e transtornos alimentares: estrutura de serviços, abordagem multidisciplinar, faturamento e captação de pacientes.",
    h1="Gestão de Clínicas de Nutrição Clínica e Transtornos Alimentares",
    lead="A nutrição clínica é uma das especialidades em mais rápida expansão no Brasil, impulsionada pela epidemia de obesidade, pelo crescimento dos transtornos alimentares e pela busca por saúde preventiva baseada em dieta. Clínicas que integram nutrição clínica com psicologia alimentar e abordagem de transtornos alimentares (anorexia, bulimia, compulsão alimentar) oferecem um serviço diferenciado com alta demanda e fidelização de longo prazo.",
    sections=[
        ("Portfolio de Serviços: Nutrição Clínica e Transtornos Alimentares", "Uma clínica completa de nutrição clínica oferece: consultas individuais de nutrição (avaliação nutricional, anamnese alimentar, planejamento dietético), bioimpedância e composição corporal, atendimento de transtornos alimentares (com equipe multiprofissional — nutricionista, psicólogo e psiquiatra), nutrição esportiva, nutrição materno-infantil e programas de reeducação alimentar em grupo. A abordagem de transtornos alimentares requer treinamento específico e trabalho integrado com saúde mental — diferenciando a clínica das que fazem apenas emagrecimento."),
        ("Abordagem Multidisciplinar em Transtornos Alimentares", "O tratamento de transtornos alimentares (anorexia nervosa, bulimia nervosa, transtorno de compulsão alimentar periódica — TCAP) requer equipe mínima de: nutricionista especializado em comportamento alimentar, psicólogo com experiência em TCC para transtornos alimentares, e psiquiatra (para casos com comorbidades, uso de antidepressivos ou ISRS). Casos graves (anorexia com IMC < 16) podem requerer internação hospitalar — desenvolva protocolo de encaminhamento para hospitais com unidade de transtornos alimentares."),
        ("Avaliação Nutricional e Ferramentas de Diagnóstico", "A avaliação nutricional completa inclui: anamnese alimentar detalhada (recordatório 24h, questionário de frequência alimentar), avaliação antropométrica (peso, altura, IMC, circunferências), bioimpedância tetrapolar (gordura corporal, massa magra, hidratação) e exames laboratoriais complementares (hemograma, vitaminas, minerais, hormônios tireoidianos). Para transtornos alimentares, adicione escalas validadas de comportamento alimentar (EAT-26, BITE, Binge Eating Scale) para monitorar a evolução ao longo do tratamento."),
        ("Faturamento: Mix Particular e Convênios Especializados", "Consultas de nutrição têm cobertura limitada por planos de saúde — a maioria exige solicitação médica e cobre apenas condições específicas (obesidade grau III, diabetes, desnutrição hospitalar). Clínicas de nutrição trabalham majoritariamente no particular (70 a 85% da receita). O ticket médio de consulta de nutrição varia de R$ 200 a R$ 500 no particular. Programas de acompanhamento em grupo (grupos de reeducação alimentar com 8 a 12 pacientes, R$ 500 a R$ 1.500 por paciente/ciclo) aumentam a rentabilidade por hora do profissional."),
        ("Captação: Médicos, Academia e Marketing de Conteúdo", "Os principais encaminhadores são: endocrinologistas (obesidade, diabetes), gastroenterologistas (SII, DRGE), cardiologistas (hipercolesterolemia, hipertensão), ginecologistas (síndrome dos ovários policísticos) e psiquiatras (transtornos alimentares). No digital, a nutrição é uma das especialidades com maior engajamento nas redes sociais — produza conteúdo sobre emagrecimento saudável, nutrição esportiva e alimentação intuitiva para construir audiência. Parcerias com academias e crossfit boxes são canais eficientes para captação de pacientes de nutrição esportiva."),
    ],
    faq_list=[
        ("Qual é a diferença entre uma clínica de nutrição e um consultório de nutricionista?", "Um consultório de nutricionista é a prática individual de um profissional. Uma clínica de nutrição é uma estrutura que pode incluir múltiplos nutricionistas, equipe de saúde mental (para transtornos alimentares), equipamentos de avaliação (bioimpedância, estadiômetro calibrado, plicômetro), sala de grupo para atendimentos coletivos e, eventualmente, médico (endocrinologista ou clínico) para atendimento integrado. A clínica permite escalar o atendimento, diversificar serviços e construir uma marca mais forte do que o consultório individual."),
        ("Como estruturar um programa multidisciplinar para transtornos alimentares?", "O programa deve ter: avaliação inicial multidisciplinar (nutricionista + psicólogo + psiquiatra em até 2 semanas), plano de tratamento integrado com metas compartilhadas entre todos os profissionais, reuniões de equipe semanais para discussão de casos, comunicação estruturada com família (especialmente em adolescentes) e critérios claros de encaminhamento para internação (critérios de gravidade médica e psiquiátrica). A abordagem baseada em evidência é a TCC-E (Terapia Cognitivo-Comportamental para transtornos alimentares) integrada com nutrição de presença plena (mindful eating)."),
        ("A bioimpedância é confiável como método de avaliação de composição corporal?", "A bioimpedância tetrapolar (BIA) é um método validado, prático e não invasivo para estimar composição corporal — gordura corporal, massa magra e hidratação. Suas limitações incluem: sensibilidade ao estado de hidratação (resultados variam conforme ingestão de água, prática de exercício e ciclo menstrual nas mulheres), menor precisão em extremos de IMC (obesos com IMC > 40 ou muito magros) e variação entre aparelhos de diferentes marcas. Para acompanhamento evolutivo do mesmo paciente no mesmo aparelho, a BIA é suficientemente precisa e prática."),
    ]
)

# Article 4317 — SaaS sales: centros de tratamento de obesidade e cirurgia bariátrica
art(
    slug="vendas-para-o-setor-de-saas-de-gestao-de-centros-de-obesidade-e-cirurgia-bariatrica",
    title="Vendas para SaaS de Gestão de Centros de Obesidade e Cirurgia Bariátrica | ProdutoVivo",
    desc="Estratégias de vendas para SaaS de gestão de centros de obesidade e cirurgia bariátrica: como prospectar, demonstrar valor e fechar contratos nesse segmento especializado.",
    h1="Vendas para SaaS de Gestão de Centros de Obesidade e Cirurgia Bariátrica",
    lead="Centros de tratamento de obesidade e cirurgia bariátrica atendem uma população crescente — 60% dos brasileiros adultos têm sobrepeso ou obesidade — com um processo de atendimento altamente estruturado: avaliação multidisciplinar pré-operatória, procedimento cirúrgico de alto custo e acompanhamento longitudinal pós-operatório por anos. Esse fluxo complexo cria demanda clara por softwares especializados.",
    sections=[
        ("Operações de Centros de Obesidade e Bariátrica", "Um centro de bariátrica completo oferece: consultas de endocrinologia e nutrição para tratamento clínico da obesidade, avaliação multidisciplinar pré-bariátrica (endocrinologista, nutricionista, psicólogo, cardiologista, pneumologista para apneia), cirurgia bariátrica (sleeve gástrico, bypass gástrico em Y-de-Roux, banda gástrica), acompanhamento pós-operatório de longo prazo (mínimo 5 anos, incluindo suplementação nutricional e rastreamento de deficiências) e tratamento de complicações cirúrgicas. O ciclo completo de um paciente bariátrico pode durar 10 a 15 anos."),
        ("Mapeamento do Decisor: Cirurgião Bariátrico e Gestor Administrativo", "O cirurgião bariátrico é frequentemente o sócio-proprietário do centro. Em estruturas maiores (hospitais day-bariátrica, redes), há um coordenador de centro e um gestor administrativo. O cirurgião valoriza: prontuário com protocolo pré-operatório estruturado (checklist de avaliações obrigatórias para autorização do plano), registro de técnica cirúrgica com campos específicos para bariátrica (peso do anel, ponto de bypass, comprimento dos ramos), e acompanhamento pós-operatório com escalas de perda de peso e qualidade de vida (BAROS, IWQOL)."),
        ("Demo: Protocolo Pré-Operatório e Acompanhamento Pós-Bariátrico", "Demonstre: (1) checklist digital de avaliações multidisciplinares obrigatórias para autorização do plano (endocrinologia + nutrição + psicologia + cardio + pneumo — com status de cada avaliação em tempo real); (2) prontuário de cirurgia com campos específicos para bariátrica (técnica, peso, complicações intraoperatórias); (3) programa de acompanhamento pós-operatório com calendário automático de consultas (1 semana, 1 mês, 3 meses, 6 meses, 1 ano, anual até 5 anos); (4) gráfico de curva de perda de peso com comparação ao esperado pelo tipo de cirurgia."),
        ("Faturamento Bariátrico: Cobertura de Convênios e OPME", "Cirurgia bariátrica tem cobertura obrigatória pelos planos de saúde para pacientes com IMC ≥ 40 (ou ≥ 35 com comorbidades como diabetes, HAS, apneia) após 2 anos de tratamento clínico sem sucesso. O faturamento inclui: honorários médicos (cirurgião, assistente, anestesiologista), taxa de sala operatória, OPME (grampeadores circulares e lineares, anéis) e diária hospitalar. O custo de OPME em bariátrica varia de R$ 5.000 a R$ 20.000 por cirurgia — a rastreabilidade e o faturamento correto desses materiais são críticos para a rentabilidade do centro."),
        ("Expansão para Redes Bariátricas e Plataformas de Telemedicina", "Redes bariátricas (como as operadas por grandes hospitais e redes de clínicas de cirurgia) representam o maior potencial de expansão. Implante em um centro-piloto e expanda com protocolo padronizado. Para o acompanhamento pós-operatório — que ocorre por anos — a telemedicina é o canal ideal: consultas de rotina de suplementação e evolução de peso podem ser realizadas por videochamada, reduzindo o custo de seguimento e aumentando a adesão do paciente ao protocolo de longo prazo."),
    ],
    faq_list=[
        ("Quais são os critérios de cobertura de cirurgia bariátrica pelos planos de saúde?", "A Resolução ANS 428/2017 estabelece: IMC ≥ 40 kg/m² sem comorbidades, ou IMC ≥ 35 kg/m² com pelo menos uma comorbidade grave (diabetes tipo 2, HAS, apneia obstrutiva do sono, dislipidemia, refluxo grave, artropatias com limitação funcional). É exigida documentação de tratamento clínico prévio por no mínimo 2 anos sem sucesso sustentado. A avaliação multidisciplinar pré-operatória é obrigatória e deve ser documentada no prontuário."),
        ("Como o SaaS pode apoiar o acompanhamento de longo prazo de pacientes bariátricos?", "O módulo de seguimento pós-bariátrico deve incluir: calendário automático de consultas com todos os profissionais da equipe (nutricionista, psicólogo, endocrinologista) nos marcos do protocolo, alertas de suplementação periódica (vitaminas A, D, B12, ferro, cálcio — deficiências frequentes após bypass), monitoramento de exames laboratoriais (proteinemia, ferritina, B12, folato, PTH) com interpretação automatizada e alertas de valores fora do alvo, e escala de qualidade de vida (BAROS) a cada 6 meses para medir desfechos além do peso."),
        ("Qual é o ticket médio de SaaS para centros de bariátrica?", "Para centros com 30 a 80 cirurgias/mês, o ticket varia de R$ 2.500 a R$ 7.000/mês. Centros com 100+ cirurgias/mês e gestão de redes hospitalares chegam a R$ 15.000 a R$ 30.000/mês com módulos de BI centralizado, faturamento multi-plano e gestão de complicações pós-operatórias. O ciclo de vendas é médio (30 a 90 dias) — o cirurgião decide relativamente rápido se o sistema atende ao protocolo específico do seu centro."),
    ]
)

# Article 4318 — Consulting: gestão de crescimento e scale-up de startups
art(
    slug="consultoria-de-gestao-de-crescimento-e-scale-up-de-startups",
    title="Consultoria de Gestão de Crescimento e Scale-up de Startups | ProdutoVivo",
    desc="Como estruturar e monetizar uma consultoria de crescimento e scale-up de startups: metodologias de growth, modelo de negócio e posicionamento no ecossistema.",
    h1="Consultoria de Gestão de Crescimento e Scale-up de Startups",
    lead="A jornada da startup da tração ao scale-up é repleta de armadilhas — escalar antes de atingir o product-market fit, crescer o time sem processos, queimar caixa em aquisição sem retenção. Consultorias especializadas em crescimento e scale-up de startups têm demanda crescente do ecossistema de venture capital brasileiro, que precisa de suporte operacional para as empresas do portfólio além do capital.",
    sections=[
        ("O Que é Scale-up e Quando Contratar Consultoria de Crescimento", "Scale-up é a fase em que a startup comprovou o product-market fit (NPS > 40, churn < 5%/mês, retenção de receita > 100%) e precisa escalar sistematicamente — crescer revenue, time e operação sem perder a eficiência e a cultura. A consultoria de crescimento é mais valiosa nesse momento — não na fase de ideação ou validação, onde a startup precisa de agilidade e experimentação, não de processos formais. O gatilho mais comum de contratação é após uma rodada Série A ou B, quando há capital mas falta capacidade operacional para escalar."),
        ("Metodologias de Growth: AARRR, OKRs e Growth Loops", "O framework AARRR (Acquisition, Activation, Retention, Referral, Revenue) estrutura os experimentos de crescimento por etapa do funil. OKRs (Objectives and Key Results) alinham o time em torno de metas de crescimento quantificáveis e transparentes. Growth Loops são os mecanismos de crescimento composto que fazem o produto crescer por si só — um cliente satisfeito traz outro cliente (loop viral), o uso do produto gera dados que melhoram o produto (loop de dados), ou cada cliente pago financia aquisição de mais clientes (loop de capital). Identificar e acelerar o growth loop principal da startup é a principal contribuição da consultoria."),
        ("Estrutura de Time de Growth e Experimentos", "A consultoria ajuda a estruturar o squad de growth: Growth PM (prioriza experimentos), Growth Engineer (implementa experimentos de forma rápida e reversível), Data Analyst (mede resultados) e Growth Marketer (executa canais). O processo de experimentação segue o ciclo: hipótese → priorização (ICE score: Impact × Confidence × Ease) → implementação → medição → decisão (escalar, iterar ou matar). Startups com 10+ experimentos de growth por mês têm taxas de crescimento 3x superiores a startups com processos ad hoc."),
        ("Go-to-Market e Expansão de Canal para Scale-ups", "Startups em fase de scale-up frequentemente precisam diversificar canais de aquisição: o canal inicial que funcionou na tração (ex.: outbound de founder) não escala. A consultoria estrutura o playbook de go-to-market para novos canais: programa de parceiros, inbound marketing via SEO/content, mídia paga com unit economics positivos, produto-led growth (PLG) se o produto permitir auto-serviço. Para cada canal, define o CAC meta, o payback máximo e as métricas de eficiência que justificam continuar investindo."),
        ("Precificação e Modelos de Engajamento da Consultoria de Scale-up", "A consultoria de crescimento para startups adota diferentes modelos: (1) Projeto fixo (diagnóstico de growth e roadmap — R$ 60 mil a R$ 200 mil); (2) Retainer mensal + participação em resultados (R$ 20 mil a R$ 60 mil/mês + 0,5 a 1% do crescimento incremental de receita); (3) Equity — para early-stage, a consultoria pode aceitar participação societária (0,5 a 2%) em vez de cash; (4) EIR (Entrepreneur in Residence) — consultor sênior embedded na empresa 2 a 3 dias/semana (R$ 15 mil a R$ 40 mil/mês). O modelo de resultado é o mais alinhado — consultor e startup têm o mesmo objetivo."),
    ],
    faq_list=[
        ("Como saber se uma startup está pronta para scale-up?", "Indicadores de prontidão para scale-up incluem: NPS > 50 (produto amado pelos clientes), churn mensal < 3% (clientes ficam), NRR > 110% (receita de clientes existentes cresce), CAC payback < 18 meses (aquisição é sustentável), processo de vendas repetível e documentado (não depende do founder para fechar), e produto com capacidade de escalar tecnicamente (sem dívida técnica crítica). Startups que escalam antes de atingir esses indicadores frequentemente enfrentam crescimento com churn alto — crescem e perdem clientes ao mesmo tempo."),
        ("Qual é a diferença entre uma consultoria de crescimento e uma aceleradora?", "Aceleradoras (como Y Combinator, Endeavor, Cubo) oferecem programa estruturado com currículo, mentorias coletivas, rede de contatos e, frequentemente, capital — geralmente tomando entre 2 e 10% de equity. Consultorias de crescimento são mais especializadas em diagnóstico e execução de growth e podem ser contratadas a qualquer momento, sem dilução. Para startups que já passaram por aceleração e captaram uma rodada, a consultoria especializada em crescimento preenche a lacuna de capacidade operacional que as aceleradoras não cobrem na fase pós-programa."),
        ("O que é PLG (Product-Led Growth) e quando é a estratégia certa?", "PLG é uma estratégia go-to-market em que o produto é o principal motor de aquisição, conversão e expansão — sem necessidade de uma equipe de vendas tradicional. Usuários experimentam o produto gratuito ou freemium, percebem valor e se convertem em clientes pagantes ou convidam colegas (loop viral). PLG é mais eficaz quando o produto tem: valor individual perceptível (o usuário sozinho experimenta o valor sem onboarding extenso), baixo custo de implementação (começa a usar em minutos) e rede social dentro da empresa (um usuário converte colegas). Slack, Zoom, Figma e Notion são exemplos icônicos de PLG."),
    ]
)

# ── sitemap.xml ───────────────────────────────────────────────────────────────
content = open('public/sitemap.xml').read()
new_urls = (
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-customer-data-platform-e-personalizacao/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-clinicas-de-medicina-integrativa-e-fitoterapia-clinica/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/vendas-para-o-setor-de-saas-de-gestao-de-clinicas-de-ortopedia-pediatrica-e-deformidades/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/consultoria-de-gestao-de-esg-e-sustentabilidade-empresarial/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-gestao-de-obras-e-construcao-civil/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-clinicas-de-nutricao-clinica-e-transtornos-alimentares/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/vendas-para-o-setor-de-saas-de-gestao-de-centros-de-obesidade-e-cirurgia-bariatrica/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/consultoria-de-gestao-de-crescimento-e-scale-up-de-startups/</loc></url>'
)
open('public/sitemap.xml', 'w').write(content.replace('</urlset>', new_urls + '</urlset>'))

# ── trilha.html ───────────────────────────────────────────────────────────────
content = open('public/trilha.html').read()
new_items = (
    '<li><a href="/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-customer-data-platform-e-personalizacao/">Gestao De Negocios De Empresa De B2b Saas De Customer Data Platform E Personalizacao</a></li>\n'
    '<li><a href="/blog/gestao-de-clinicas-de-medicina-integrativa-e-fitoterapia-clinica/">Gestao De Clinicas De Medicina Integrativa E Fitoterapia Clinica</a></li>\n'
    '<li><a href="/blog/vendas-para-o-setor-de-saas-de-gestao-de-clinicas-de-ortopedia-pediatrica-e-deformidades/">Vendas Para O Setor De Saas De Gestao De Clinicas De Ortopedia Pediatrica E Deformidades</a></li>\n'
    '<li><a href="/blog/consultoria-de-gestao-de-esg-e-sustentabilidade-empresarial/">Consultoria De Gestao De Esg E Sustentabilidade Empresarial</a></li>\n'
    '<li><a href="/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-gestao-de-obras-e-construcao-civil/">Gestao De Negocios De Empresa De B2b Saas De Gestao De Obras E Construcao Civil</a></li>\n'
    '<li><a href="/blog/gestao-de-clinicas-de-nutricao-clinica-e-transtornos-alimentares/">Gestao De Clinicas De Nutricao Clinica E Transtornos Alimentares</a></li>\n'
    '<li><a href="/blog/vendas-para-o-setor-de-saas-de-gestao-de-centros-de-obesidade-e-cirurgia-bariatrica/">Vendas Para O Setor De Saas De Gestao De Centros De Obesidade E Cirurgia Bariatrica</a></li>\n'
    '<li><a href="/blog/consultoria-de-gestao-de-crescimento-e-scale-up-de-startups/">Consultoria De Gestao De Crescimento E Scale Up De Startups</a></li>'
)
open('public/trilha.html', 'w').write(content.replace('</ul>', new_items + '\n</ul>', 1))

print("Done — batch 1414")
