import os, json

BASE   = os.path.join(os.path.dirname(__file__), "blog")
DOMAIN = "https://produtovivo.com.br"
PIXEL  = "4520253334926563"

TMPL = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<!-- Facebook Pixel Code -->
<script>!function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)}};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','{pixel}');fbq('track','PageView');</script>
<style>
body{{font-family:Arial,sans-serif;margin:0;padding:0;color:#222;}}
header{{background:#1a1a2e;color:#fff;padding:16px 24px;}}
header a{{color:#e0e0ff;text-decoration:none;font-weight:bold;font-size:1.2rem;}}
main{{max-width:860px;margin:40px auto;padding:0 20px;}}
h1{{font-size:2rem;color:#1a1a2e;}}
.lead{{font-size:1.1rem;color:#444;margin-bottom:28px;}}
h2{{color:#16213e;margin-top:32px;}}
.faq{{background:#f5f7ff;border-radius:8px;padding:24px;margin-top:40px;}}
.faq h2{{color:#1a1a2e;margin-top:0;}}
.faq-item{{margin-bottom:18px;}}
.faq-item h3{{margin:0 0 6px;color:#16213e;}}
footer{{text-align:center;padding:24px;color:#888;font-size:.9rem;margin-top:60px;border-top:1px solid #eee;}}
footer a{{color:#555;}}
</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<header><a href="/">ProdutoVivo</a></header>
<main>
<h1>{h1}</h1>
<p class="lead">{lead}</p>
{body}
<div class="faq">
<h2>Perguntas Frequentes</h2>
{faqs}
</div>
</main>
<footer><p>&copy; 2025 ProdutoVivo &mdash; <a href="/blog/">Blog</a> | <a href="/trilha">Trilha Gratuita</a></p></footer>
</body>
</html>"""

def art(slug, title, desc, h1, lead, sections, faq_list):
    url = f"{DOMAIN}/blog/{slug}/"
    body_html = ""
    for sec_title, sec_body in sections:
        body_html += f"<h2>{sec_title}</h2>\n<p>{sec_body}</p>\n"
    faqs_html = ""
    schema_faqs = []
    for q, a in faq_list:
        faqs_html += f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>\n'
        schema_faqs.append({"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}})
    schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": schema_faqs}, ensure_ascii=False)
    html = TMPL.format(title=title, desc=desc, url=url, pixel=PIXEL,
                       h1=h1, lead=lead, body=body_html, faqs=faqs_html, schema=schema)
    out_dir = os.path.join(BASE, slug)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

# Article 4319 — B2B SaaS: gestão de vendas e CRM para PMEs
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-crm-e-gestao-de-vendas-para-pmes",
    title="Gestão de Negócios para Empresas de B2B SaaS de CRM e Gestão de Vendas para PMEs | ProdutoVivo",
    desc="Como escalar um negócio de B2B SaaS de CRM e gestão de vendas para PMEs: modelo de receita, go-to-market e estratégias de diferenciação.",
    h1="Gestão de Negócios para Empresas de B2B SaaS de CRM e Gestão de Vendas para PMEs",
    lead="O mercado de CRM para PMEs no Brasil é um dos maiores e mais fragmentados do mundo SaaS — milhões de pequenas e médias empresas ainda gerenciam relacionamentos com clientes em planilhas, WhatsApp e cadernos. SaaS de CRM adaptados à realidade brasileira (integração nativa com WhatsApp, NF-e, PIX e marketplace como Mercado Livre) têm oportunidade de capturar uma base imensa de clientes com altíssimo potencial de conversão.",
    sections=[
        ("Mercado de CRM para PMEs no Brasil", "Estima-se que menos de 10% das empresas com 5 a 50 funcionários no Brasil usam algum CRM dedicado — a maioria usa WhatsApp como principal canal de relacionamento com clientes e Excel para controle de pipeline. As soluções internacionais (Salesforce, HubSpot) são percebidas como caras e complexas para esse perfil. Isso cria espaço para CRMs locais com: interface simples, integração nativa com WhatsApp Business API, suporte em português e preço acessível (R$ 100 a R$ 500/mês para equipes de 3 a 15 pessoas)."),
        ("Modelo de Receita e Precificação de CRM SaaS para PMEs", "O modelo padrão é por usuário/mês (R$ 50 a R$ 150/usuário/mês) ou por empresa com número ilimitado de usuários até um teto (R$ 300 a R$ 800/mês para até 10 usuários). Módulos premium incluem: automação de WhatsApp (sequências de follow-up automatizadas), integração com e-commerce (pedidos do Mercado Livre e VTEX puxados automaticamente para o CRM), relatórios avançados de performance de vendas e gestão de propostas com assinatura eletrônica. O modelo freemium (1 a 3 usuários gratuito, cobrança a partir do 4º) é altamente eficiente para PMEs."),
        ("Diferenciação pelo WhatsApp: a Maior Oportunidade no Brasil", "O Brasil é o segundo maior mercado de WhatsApp do mundo — 99% das PMEs brasileiras usam WhatsApp para vendas e atendimento. Um CRM com integração nativa ao WhatsApp Business API (envio de mensagens, automação de follow-up, chatbot de triagem, central de WhatsApp multi-atendente com histórico unificado) é o maior diferencial competitivo no mercado brasileiro. Plataformas que fazem essa integração de forma fluida e intuitiva têm taxas de conversão 3 a 4x superiores aos concorrentes sem essa funcionalidade."),
        ("Go-to-Market: PLG e Ecossistema de Parceiros", "O modelo PLG (Product-Led Growth) é o mais eficiente para CRM de PMEs: trial gratuito de 14 dias sem cartão de crédito, onboarding guiado que leva o usuário ao valor em menos de 30 minutos (primeiro lead cadastrado, primeira mensagem de WhatsApp enviada pelo CRM), e loops de convite para adicionar colegas do time. Complementarmente, construa um ecossistema de parceiros: agências de marketing digital, consultores de vendas e contadores que indicam o CRM para seus clientes PMEs em troca de comissão de revenda (20 a 30% do MRR)."),
        ("Expansão: de CRM para Plataforma de Negócios para PMEs", "CRM é a porta de entrada, mas a expansão de ARPU ocorre com módulos adjacentes: gestão financeira simplificada (contas a pagar e a receber com integração bancária), emissão de NF-e e NFS-e, gestão de contratos (propostas + assinatura digital) e atendimento ao cliente (helpdesk). Empresas que criam um ecossistema de módulos integrados para PMEs constroem um custo de troca alto — nenhum empresário quer migrar 5 sistemas diferentes ao mesmo tempo — e atingem MRR por cliente de R$ 500 a R$ 1.500/mês."),
    ],
    faq_list=[
        ("Qual é a diferença entre um CRM para PMEs e um CRM enterprise como Salesforce?", "CRMs enterprise (Salesforce, Microsoft Dynamics) são altamente customizáveis mas exigem meses de implementação, equipes técnicas dedicadas e investimentos de R$ 5.000 a R$ 50.000/mês. CRMs para PMEs são projetados para uso imediato — setup em horas, interface intuitiva sem necessidade de TI, preço acessível e funcionalidades focadas nas necessidades de equipes de vendas pequenas. A troca de simplicidade por customização é a decisão de design central que define o mercado-alvo."),
        ("Como o CRM com integração ao WhatsApp funciona na prática?", "Via WhatsApp Business API (oficial), o CRM pode: criar um número de WhatsApp da empresa acessível por múltiplos atendentes simultaneamente, registrar automaticamente todas as conversas no histórico do cliente no CRM, enviar sequências de mensagens automáticas para leads que não responderam (follow-up), criar chatbots de triagem que qualificam o lead antes de passar para um vendedor humano, e gerar relatórios de tempo de resposta e conversão por atendente. Tudo isso sem instalar nada — acessível via navegador."),
        ("Qual é o CAC (Custo de Aquisição de Cliente) típico para CRM SaaS de PMEs?", "Em modelos PLG bem executados, o CAC de CRM para PMEs pode ser surpreendentemente baixo: R$ 100 a R$ 500 por cliente quando a ativação ocorre via trial auto-self-service. Modelos com vendas inside sales têm CAC de R$ 800 a R$ 3.000 dependendo do ticket. Para o modelo ser sustentável, o LTV (Lifetime Value) deve ser 3x o CAC no mínimo — com churn mensal de 2 a 3% e MRR médio de R$ 400/cliente, o LTV é de R$ 13.000 a R$ 20.000, suportando CAC de até R$ 4.000 a R$ 6.000."),
    ]
)

# Article 4320 — Clinic: angiologia e cirurgia vascular minimamente invasiva
art(
    slug="gestao-de-clinicas-de-angiologia-e-cirurgia-vascular-minimamente-invasiva",
    title="Gestão de Clínicas de Angiologia e Cirurgia Vascular Minimamente Invasiva | ProdutoVivo",
    desc="Guia de gestão para clínicas de angiologia e cirurgia vascular minimamente invasiva: estrutura de serviços, equipamentos, faturamento e captação de pacientes.",
    h1="Gestão de Clínicas de Angiologia e Cirurgia Vascular Minimamente Invasiva",
    lead="A angiologia e cirurgia vascular trata doenças das artérias, veias e vasos linfáticos — desde varizes até isquemia crítica de membros inferiores. Com o avanço dos procedimentos endovasculares (angioplastia, endoprótese aórtica, embolização), muitos procedimentos antes realizados em centro cirúrgico passaram para o ambulatório, democratizando o acesso e criando novas oportunidades para clínicas especializadas.",
    sections=[
        ("Portfolio de Serviços em Angiologia e Cirurgia Vascular", "Uma clínica vascular completa oferece: consultas clínicas, eco-Doppler vascular (arterial e venoso — exame de maior volume), tratamento de varizes (escleroterapia líquida e espuma, laser endovenoso, radiofrequência), tratamento de úlceras vasculares (arteriais e venosas), procedimentos ambulatoriais de acesso vascular (cateter venoso central, PICC), e avaliação pré-operatória vascular para cirurgias de grande porte. Em centros mais equipados, inclua angioplastia periférica em sala de hemodinâmica."),
        ("Eco-Doppler Vascular: o Exame Central da Especialidade", "O eco-Doppler é o exame de maior volume em angiologia — diagnóstico de trombose venosa profunda (TVP), insuficiência venosa crônica, isquemia arterial periférica e avaliação de fístulas para diálise. Um aparelho de ultrassom com Doppler colorido de alta resolução (R$ 80 a R$ 250 mil) permite de 10 a 20 exames por dia. Calcule o custo por exame e compare com o faturamento por convênio (R$ 150 a R$ 400 por eco-Doppler) para garantir rentabilidade. Técnicos de ultrassom especializados em vascular são fundamentais para a qualidade dos exames."),
        ("Tratamento de Varizes: Alto Volume, Alta Satisfação", "O tratamento de varizes é o procedimento de maior volume em clínicas vasculares — insuficiência venosa crônica afeta 35% da população adulta. Escleroterapia (espuma de polidocanol) pode ser realizada em qualquer sala de procedimentos simples; laser endovenoso (EVL) e radiofrequência (RFA) requerem sala equipada e anestesia tumescente. A combinação de tratamentos — RFA para o tronco safeno + escleroterapia de finos ramos — gera receita de R$ 3.000 a R$ 12.000 por membro tratado, com altíssima satisfação do paciente pelo resultado estético e funcional."),
        ("Faturamento: Eco-Doppler, Procedimentos e OPME Vascular", "O eco-Doppler tem boa cobertura por convênios (código CBHPM específico por vaso estudado). Procedimentos de tratamento de varizes têm cobertura variável — escleroterapia por estética não é coberta, mas por insuficiência venosa documentada (dor, edema, alterações tróficas) é obrigatória pela ANS. Procedimentos endovasculares (angioplastia, endoprótese) são de alto custo com faturamento de R$ 20.000 a R$ 80.000 — incluindo OPME vascular com rastreabilidade obrigatória."),
        ("Captação: Clínicos, Cardiologistas e Marketing Digital", "Principais encaminhadores: clínicos gerais (TVP, isquemia periférica), cardiologistas (avaliação vascular em pacientes com doença cardiovascular), nefrologistas (confecção de fístula arteriovenosa para hemodiálise — procedimento de alta recorrência). No digital, tratamento de varizes tem altíssima busca no Google e nas redes sociais — especialmente por mulheres de 30 a 55 anos. Resultados antes/depois de tratamento de varizes têm engajamento excepcional no Instagram. Invista em fotos de alta qualidade dos resultados obtidos."),
    ],
    faq_list=[
        ("Qual é a diferença entre flebologia e cirurgia vascular?", "Flebologia é a subespecialidade focada exclusivamente nas doenças venosas (varizes, insuficiência venosa, trombose). Cirurgia vascular é mais abrangente e inclui também doenças arteriais (aterosclerose, aneurismas, isquemia) e doenças linfáticas. Na prática, muitos cirurgiões vasculares fazem flebologia como parte de sua prática ambulatorial de alto volume, enquanto reservam os procedimentos arteriais para o centro cirúrgico. O título de especialidade em cirurgia vascular e endovascular é concedido pela SBACV após residência médica específica."),
        ("Laser endovenoso vs. radiofrequência no tratamento de varizes: qual é melhor?", "Ambas as técnicas (EVLA — Endovenous Laser Ablation e RFA — Radiofrequency Ablation) são minimamente invasivas, realizam-se com anestesia tumescente em consultório e têm eficácia similar (>90% de oclusão do tronco safeno em 5 anos). As diferenças são: o laser é ligeiramente mais doloroso no pós-operatório; a radiofrequência tem curva de aprendizado maior, mas resultado de dor pós-procedimento inferior. Ambas são superiores à stripping cirúrgico tradicional em termos de recuperação, complicações e resultado cosmético."),
        ("Uma clínica de angiologia pode realizar angioplastia periférica ambulatorial?", "Sim, em clínicas com sala de hemodinâmica equipada (fluoroscópio/arco cirúrgico) e estrutura de suporte para complicações. A angioplastia periférica ambulatorial (sem internação) é realizada para lesões de baixo e médio risco em artérias ilíacas, femorais e poplíteas. Requer credenciamento específico da operadora e da Vigilância Sanitária para procedimento hemodinâmico ambulatorial. O investimento em sala de hemodinâmica (R$ 800 mil a R$ 3 milhões) é justificado em clínicas com volume de 10+ procedimentos endovasculares por mês."),
    ]
)

# Article 4321 — SaaS sales: centros de medicina estética e tratamentos corporais
art(
    slug="vendas-para-o-setor-de-saas-de-gestao-de-centros-de-medicina-estetica-e-tratamentos-corporais",
    title="Vendas para SaaS de Gestão de Centros de Medicina Estética e Tratamentos Corporais | ProdutoVivo",
    desc="Como vender SaaS de gestão para centros de medicina estética e tratamentos corporais: abordagem consultiva, demonstração de valor e estratégias de conversão.",
    h1="Vendas para SaaS de Gestão de Centros de Medicina Estética e Tratamentos Corporais",
    lead="Centros de medicina estética e tratamentos corporais combinam alta densidade de procedimentos por dia com demanda por experiência premium do paciente. Gestão eficiente de agenda, estoque de insumos cosméticos, fidelização de clientes e faturamento diferenciado entre particular e convênio são os principais pontos de valor de um SaaS especializado nesse segmento em expansão acelerada.",
    sections=[
        ("Operações de Centros de Medicina Estética Corporal", "Um centro de estética médica corporal realiza: criolipólise, radiofrequência corporal, ultrassom focalizado de alta intensidade (HIFU corporal), carboxiterapia, aplicações de toxina botulínica para hiperidrose e bruxismo, preenchedores e bioestimuladores, laser para gordura localizada e flacidez, e depilação a laser. O fluxo de atendimento é de alta rotatividade — 6 a 15 procedimentos por dia por sala — exigindo agendamento preciso e controle de equipamentos que requerem manutenção regular."),
        ("Mapeamento do Decisor: Médico Esteta e Gestor do Centro", "O decisor é o médico responsável ou o proprietário do centro (que pode ser médico ou empresário com médico contratado). O médico esteta valoriza: prontuário com protocolo fotográfico padronizado (antes/depois de cada procedimento), controle de insumos por procedimento (quantidade de toxina por aplicação, volume de preenchedor usado), e CRM de follow-up para pré-agendamento de manutenções. O gestor administrativo prioriza: agenda eficiente, controle de estoque de insumos de alto custo e relatórios de receita por tipo de procedimento."),
        ("Demo: Protocolo Fotográfico e CRM de Fidelização", "Demonstre: (1) prontuário com câmera integrada e ângulos padronizados por procedimento (face frontal + 45° + perfil para facial; abdome + flancos para corporal); (2) comparação automática antes/depois vinculada à sessão do prontuário; (3) controle de lote e quantidade de insumos usados por procedimento (toxina botulínica por unidade, preenchedor por ml); (4) CRM de retorno automático — pacientes de toxina recebem lembrete em 3 e 4 meses; pacientes de criolipólise em 45 dias para avaliação de resultado; (5) relatório de receita por procedimento e por profissional."),
        ("Controle de Estoque de Insumos de Alto Custo", "Toxina botulínica (Botox, Dysport, Xeomin) custa R$ 800 a R$ 2.000 por frasco e tem validade de 4 a 8 horas após abertura — o desperdício não controlado pode representar 10 a 20% da margem bruta do procedimento. Preenchedores de ácido hialurônico (Juvederm, Restylane) custam R$ 400 a R$ 1.500 por seringa de 1 ml — o controle por lote e por paciente é crítico para ANVISA (rastreabilidade de implante). Demonstre que o SaaS controla o estoque por unidade (unidades de toxina, ml de preenchedor) e alerta sobre insumos próximos ao vencimento."),
        ("Expansão: de Clínica Unitária para Rede de Estética Médica", "Centros de medicina estética têm alta tendência de expansão para redes — o modelo de negócio é replicável e existe demanda em múltiplas regiões. Para redes, o SaaS deve oferecer: gestão centralizada de prontuários (paciente pode atender em qualquer unidade), controle de estoque consolidado com transferência entre unidades, painel de desempenho cross-unidade (receita, ocupação, produtividade por profissional) e padronização de protocolos e preços em toda a rede. Redes de 3 a 10 unidades são os clientes de maior valor e de maior fidelidade."),
    ],
    faq_list=[
        ("Quais regulamentações se aplicam a centros de medicina estética?", "A medicina estética é regulamentada pelo CFM (Resolução 1.974/2011 — define práticas médicas estéticas), ANVISA (RDC 56/2021 — cosméticos; registro de dispositivos médicos como equipamentos de laser e HIFU), CRF (para procedimentos realizados por farmacêuticos) e Vigilância Sanitária municipal (alvará sanitário). Procedimentos médicos (aplicação de toxina, preenchedores, laser médico) são exclusivos do médico ou dentista para face. Esteticistas e fisioterapeutas têm escopo diferente — conforme resoluções dos respectivos conselhos."),
        ("Como demonstrar ROI para um centro de medicina estética que não usa sistema?", "Calcule: (1) tempo gasto em agenda manual (agendamentos por telefone, remarcações, confirmações) = 2 a 3h/dia = R$ 400 a R$ 600/dia de custo administrativo; (2) taxa de não-comparecimento sem confirmação automática (15 a 25% vs. 5% com confirmação por WhatsApp) = em um centro com 10 procedimentos/dia a R$ 500 médio, 10% de redução de no-show = R$ 500/dia adicional de receita; (3) retorno de pacientes de toxina com CRM automático (+20% de retorno = R$ 2.000 a R$ 5.000/mês a mais). ROI total de R$ 3.000 a R$ 6.000/mês vs. ticket de R$ 600 a R$ 1.500."),
        ("O SaaS de medicina estética precisa cumprir alguma exigência específica da ANVISA para rastreabilidade de insumos?", "Sim. Produtos como preenchedores de ácido hialurônico e bioestimuladores são dispositivos médicos implantáveis de Classe III (alto risco). A RDC ANVISA 185/2001 e a RDC 36/2013 exigem rastreabilidade completa: registro do número de série/lote do produto no prontuário do paciente, possibilidade de recall imediato de todos os pacientes que receberam um lote específico em caso de alerta do fabricante. O SaaS deve garantir essa rastreabilidade de forma simples e automática para cada procedimento realizado."),
    ]
)

# Article 4322 — Consulting: gestão de crise e comunicação de crise
art(
    slug="consultoria-de-gestao-de-crise-e-comunicacao-de-crise",
    title="Consultoria de Gestão de Crise e Comunicação de Crise | ProdutoVivo",
    desc="Como estruturar e monetizar uma consultoria de gestão de crise e comunicação de crise: metodologias, manual de crise, media training e casos de uso.",
    h1="Consultoria de Gestão de Crise e Comunicação de Crise",
    lead="Toda empresa está a uma notícia negativa de uma crise de reputação — vazamento de dados, acidente de produto, escândalo corporativo, boicote nas redes sociais ou crise ambiental. Consultorias de gestão de crise ajudam empresas a se preparar antes da crise (planos, simulações, treinos), a responder durante a crise (comunicação rápida e consistente) e a se recuperar depois (gestão de reputação de longo prazo).",
    sections=[
        ("O Que Abrange a Consultoria de Gestão de Crise", "A consultoria atua em três fases: (1) Pré-crise (preparação) — mapeamento de riscos de crise específicos do setor e da empresa, desenvolvimento do Manual de Gestão de Crise, formação do Comitê de Crise, treinamento de porta-vozes (media training), simulações de crise; (2) Durante a crise (resposta) — ativação do Comitê de Crise, desenvolvimento de mensagens-chave por stakeholder, monitoramento de mídia e redes sociais em tempo real, gestão de coletiva de imprensa e respostas a jornalistas; (3) Pós-crise (recuperação) — monitoramento de sentimento, estratégia de reconstrução de reputação."),
        ("Manual de Gestão de Crise: o Entregável Central", "O Manual de Crise define: lista de crises prováveis por probabilidade e impacto, protocolo de ativação do Comitê de Crise (quem aciona quem, em quanto tempo), escalação de decisões (quem pode aprovar comunicados em cada nível de crise), modelo de comunicado de imprensa para os cenários de crise mais prováveis, lista de contatos de jornalistas e influenciadores-chave, e protocolo de monitoramento de redes sociais (ferramentas, horários, responsáveis). Um bom manual de crise permite que a empresa responda em minutos, não em horas."),
        ("Media Training: Preparando Porta-Vozes para Crises", "Media training é um dos serviços mais demandados em gestão de crise — treinar executivos e líderes para falar com jornalistas em situações de pressão. A metodologia inclui: técnica da mensagem-puxa (message pull — responder à pergunta e imediatamente puxar para a mensagem-chave que o porta-voz quer transmitir), bridging (pontes entre a pergunta e a mensagem desejada), regra do não diga nunca (nunca diga 'sem comentários', 'foi um erro' sem contexto ou 'é confidencial'), e simulações de entrevistas em câmera com feedback em vídeo. O treinamento semestral mantém a capacidade de resposta afiada."),
        ("Gestão de Crise nas Redes Sociais", "Uma crise nas redes sociais pode se tornar nacional em minutos. O protocolo de resposta social media inclui: monitoramento 24/7 durante a crise com ferramentas como Mention, Brandwatch ou Sprinklr, definição clara de o que responder e o que não responder (trolls vs. críticas legítimas), tom de voz adequado por plataforma (LinkedIn é mais formal; Twitter/X exige respostas rápidas e diretas; Instagram prioriza empatia visual), e critérios para deletar, ignorar ou responder cada tipo de comentário. Erros de protocolo nas redes podem amplificar a crise — não a atenuar."),
        ("Precificação e Modelos de Engajamento", "Projetos de preparação para crise (Manual de Crise + media training + simulação): R$ 80 mil a R$ 300 mil. Gestão de crise ativa (acionamento de plantão em crise real): R$ 50 mil a R$ 200 mil por projeto, com componente de horas adicionais em crises de longa duração. Retainer mensal de monitoramento e prontidão para crise: R$ 15 mil a R$ 50 mil/mês. A consultoria de gestão de crise é um dos poucos segmentos onde o cliente mais valioso é o que nunca precisou usar o produto — pagou pela prevenção que evitou uma crise devastadora."),
    ],
    faq_list=[
        ("O que é a Golden Hour em gestão de crise?", "A Golden Hour é a primeira hora após o início de uma crise pública. Estudos de comunicação de crise mostram que empresas que emitem a primeira comunicação nas primeiras 60 minutos têm 40% mais chance de controlar a narrativa do que as que demoram. A comunicação inicial não precisa ter todas as respostas — apenas demonstrar que a empresa está ciente da situação, que levará a sério e que fornecerá mais informações em breve. Silêncio nas primeiras horas é frequentemente interpretado como culpa ou descaso."),
        ("Quais são as piores coisas que uma empresa pode fazer durante uma crise?", "Os erros mais comuns e danosos são: (1) Silêncio prolongado — deixar o vácuo ser preenchido por narrativas negativas; (2) Negação sem base — negar fatos que serão provados posteriormente, destruindo a credibilidade; (3) Culpar outros — desvia a atenção do problema mas não resolve e parece irresponsável; (4) Comunicação inconsistente — porta-vozes dizendo coisas diferentes para audiências distintas; (5) Ataque à imprensa ou às vítimas — sempre piora a percepção pública. O antídoto é: reconheça, informe, corrija e mostre ação concreta."),
        ("Quando uma empresa precisa de uma consultoria de crise preventiva vs. reativa?", "Preventiva: quando a empresa atua em setor de alto risco (alimentício, farmacêutico, mineração, aviação, financeiro), tem alta visibilidade pública, está em processo de fusão ou IPO (que amplifica o escrutínio público), ou passou por uma crise recente e quer estar melhor preparada para a próxima. Reativa: quando já está em crise e precisa de apoio imediato. A consultoria preventiva tem ROI 5 a 10x superior à reativa — custa menos e os resultados são significativamente melhores quando a equipe já foi treinada e o manual já existe."),
    ]
)

# Article 4323 — B2B SaaS: gestão de conformidade fiscal e tributária
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-conformidade-fiscal-e-tributaria",
    title="Gestão de Negócios para Empresas de B2B SaaS de Conformidade Fiscal e Tributária | ProdutoVivo",
    desc="Como escalar um negócio de B2B SaaS de conformidade fiscal e tributária no Brasil: modelo de receita, go-to-market e diferenciação em um mercado obrigatório.",
    h1="Gestão de Negócios para Empresas de B2B SaaS de Conformidade Fiscal e Tributária",
    lead="O Brasil possui um dos sistemas tributários mais complexos do mundo — mais de 60 tributos, obrigações acessórias mensais (SPED, EFD, DCTF, ECD) e uma legislação que muda constantemente. SaaS de conformidade fiscal e tributária são praticamente obrigatórios para empresas de médio e grande porte — qualquer erro pode resultar em multas, autuações e riscos à operação. É um mercado de alta necessidade, baixo churn e crescimento previsível.",
    sections=[
        ("Mercado de Tax Tech no Brasil: Necessidade Estrutural", "Com a reforma tributária em curso (Emenda Constitucional 132/2023 — criação do IBS, CBS e Imposto Seletivo), o mercado de conformidade fiscal está em transformação histórica. Empresas precisarão adaptar todos os seus sistemas fiscais ao novo modelo dual (coexistência de ICMS/ISS com IBS/CBS até 2033). Isso cria uma onda de demanda por atualização de software tributário que é uma oportunidade histórica para SaaS de tax compliance. O contexto de reforma é o argumento de vendas mais poderoso do setor nos próximos anos."),
        ("Módulos de um SaaS de Conformidade Fiscal", "As soluções mais demandadas incluem: (1) Emissão e validação de NF-e, NFS-e, CT-e e MDF-e; (2) Escrituração Fiscal Digital (EFD ICMS/IPI e EFD Contribuições); (3) SPED Contábil (ECD); (4) Gestão de obrigações acessórias (DCTF, DIRF, REINF); (5) Controle de benefícios fiscais e incentivos (ICMS diferido, créditos presumidos); (6) Conformidade com o e-Social (obrigações trabalhistas e previdenciárias). Cada módulo pode ser vendido separadamente ou em bundle, com receita crescendo conforme o cliente ativa módulos adicionais."),
        ("Modelo de Receita: Necessidade e Recorrência Garantidas", "O modelo padrão é mensalidade por volume de documentos fiscais emitidos (NF-e, CT-e) ou por módulo ativo. Ticket médio para PMEs: R$ 500 a R$ 3.000/mês; para enterprises: R$ 10.000 a R$ 100.000/mês. A característica mais positiva do mercado de tax tech é a previsibilidade de demanda — conformidade fiscal não é opcional. O churn é extremamente baixo (< 1% ao mês) porque migrar de sistema fiscal envolve risco alto e custo de troca elevado (paralisia operacional durante a migração, risco de perda de dados históricos)."),
        ("Go-to-Market: Contadores e Departamentos Fiscais", "O comprador técnico é o Contador, Gerente Fiscal ou CFO. Contadores e escritórios de contabilidade são canais poderosos — eles recomendam sistemas para seus clientes empresariais e podem ser parceiros de revenda com comissão de 15 a 30% do MRR. Construa um programa de parceiro contábil com: plataforma white-label para o escritório oferecer aos clientes, certificação técnica para os contadores do parceiro, e desconto progressivo por volume de clientes gerenciados via a plataforma."),
        ("Reforma Tributária como Oportunidade Histórica", "A reforma tributária brasileira é o maior projeto de modernização fiscal do país em 50 anos. Para os SaaS de tax compliance, é uma oportunidade única: (1) Todos os clientes existentes precisarão atualizar seus sistemas para o novo regime (IBS/CBS) — receita incremental garantida; (2) Empresas que ainda não usam software fiscal serão forçadas a adotar pela complexidade da transição dual; (3) Novos módulos de simulação e planejamento tributário no novo regime têm altíssimo valor percebido. Posicione-se como o parceiro estratégico da transição tributária."),
    ],
    faq_list=[
        ("Quais são as principais obrigações acessórias que um SaaS fiscal deve cobrir?", "As obrigações acessórias mais críticas são: NF-e (Nota Fiscal eletrônica — obrigatória para toda comercialização de mercadorias), SPED EFD ICMS/IPI (escrituração fiscal mensal de empresas do Lucro Real e Presumido), EFD Contribuições (PIS/COFINS), ECD (Escrituração Contábil Digital — anual), ECF (Escrituração Contábil Fiscal — apuração do IRPJ e CSLL), DCTF (Declaração de Débitos e Créditos de Tributos Federais — mensal) e REINF (Retenções na Fonte e outras informações). O descumprimento de qualquer uma sujeita a empresa a multas de 0,5 a 5% da receita."),
        ("Como a reforma tributária impacta os SaaS de conformidade fiscal?", "A reforma cria dois cenários de receita para os SaaS: (1) Curto prazo (2024-2026) — atualização de sistemas para emissão de NF-e dual (com ICMS e com IBS/CBS simultaneamente no período de transição), módulos de simulação para comparar o impacto do novo regime vs. o atual, e ferramentas de gestão de créditos acumulados de ICMS e IPI para aproveitamento antes do encerramento do regime; (2) Longo prazo (2027-2033) — plataforma completa para o novo regime de IBS/CBS com as IVA Split Payments e as obrigações acessórias reformuladas. Quem se posicionar primeiro nesse mercado captura a maior fatia."),
        ("Por que o churn é tão baixo em SaaS de conformidade fiscal?", "O custo de troca em sistemas fiscais é extremamente alto: migração de histórico fiscal (XML de NF-e dos últimos 5 anos, EFDs anteriores), risco de inconsistência entre os sistemas durante a transição (que pode gerar autuações), necessidade de treinamento de toda a equipe fiscal no novo sistema, e o risco de indisponibilidade durante a migração (impossibilitando emissão de NF-e). Além disso, as obrigações acessórias são contínuas e urgentes — não há janelas de pausa para migração. Por isso, uma vez que o cliente está no sistema, ele fica por anos."),
    ]
)

# Article 4324 — Clinic: clínicas de dor crônica e medicina da dor
art(
    slug="gestao-de-clinicas-de-dor-cronica-e-medicina-da-dor",
    title="Gestão de Clínicas de Dor Crônica e Medicina da Dor | ProdutoVivo",
    desc="Guia de gestão para clínicas de dor crônica e medicina da dor: estrutura multidisciplinar, procedimentos intervencionistas, faturamento e captação de pacientes.",
    h1="Gestão de Clínicas de Dor Crônica e Medicina da Dor",
    lead="A dor crônica afeta mais de 30% da população adulta brasileira e é a principal causa de incapacidade funcional e absenteísmo no trabalho. Clínicas de medicina da dor oferecem tratamento especializado que vai além dos analgésicos convencionais — incluindo procedimentos intervencionistas, neuromodulação e abordagem multidisciplinar. É uma especialidade com demanda crescente e déficit significativo de especialistas no país.",
    sections=[
        ("Estrutura de um Centro de Dor Multidisciplinar", "Um centro de dor de referência integra: médico especialista em dor (anestesiologista, neurologista ou ortopedista com formação em dor), psicólogo (TCC para dor crônica, manejo de catastrofização e depressão associada), fisioterapeuta (técnicas analgésicas, RPG, Pilates terapêutico), farmacêutico clínico (gestão de opioides e polifarmácia em pacientes complexos) e, em centros avançados, acupunturista e terapeuta ocupacional. A abordagem biopsicossocial da dor crônica requer essa integração multidisciplinar — tratamento isolado tem resultados significativamente inferiores."),
        ("Procedimentos Intervencionistas: Diferencial Técnico e Financeiro", "Os procedimentos intervencionistas são o grande diferencial de clínicas de medicina da dor especializadas: bloqueios de nervos periféricos e plexos (guiados por US ou fluoroscópio), infiltrações intra-articulares (joelho, ombro, coluna) guiadas por imagem, radiofrequência de nervos facetários e ramos mediais para dor de coluna, aplicação de ozônio medicinal, implante de bomba intratecal e de estimulador medular (neuromodulação — casos refratários). Cada procedimento tem faturamento de R$ 500 a R$ 15.000 dependendo da complexidade — muito superior às consultas clínicas."),
        ("Gestão de Opioides e Medicamentos Controlados", "Pacientes com dor crônica frequentemente usam opioides (tramadol, codeína, morfina, oxicodona) — medicamentos de controle especial com prescrição em receituário amarelo especial (Portaria SVS/MS 344/98). A gestão de opioides exige: controle rigoroso de prescrição (doses, intervalos, quantidade máxima por receita), monitoramento de uso problemático (escalation de dose não autorizada, múltiplos prescritores, sintomas de dependência), e rastreabilidade de todas as prescrições no prontuário. Implante protocolos de opioid stewardship para proteger os pacientes e a clínica de riscos legais."),
        ("Faturamento: Consultas, Bloqueios e Fisioterapia", "Consultas de medicina da dor têm boa cobertura por planos de saúde quando realizadas por especialistas em anestesiologia, neurologia ou medicina física. Procedimentos intervencionistas de bloqueio têm cobertura variável — alguns planos cobrem bloqueios facetários e de nervos periféricos via CBHPM, outros exigem autorização prévia com laudo justificativo. Fisioterapia para dor crônica tem cobertura geral pelos planos. No mix de receita, procedimentos intervencionistas devem representar 40 a 60% para garantir viabilidade financeira do centro de dor."),
        ("Captação: Ortopedistas, Reumatologistas e Neurologistas", "Os maiores encaminhadores são: ortopedistas (lombalgias crônicas, dor pós-cirúrgica de coluna), reumatologistas (fibromialgia, artrite reumatoide com dor refratária), neurologistas (neuropatias dolorosas, enxaqueca crônica, neuralgia do trigêmeo), oncologistas (dor oncológica — câncer) e médicos de família (dores crônicas difusas não diagnosticadas). O neurologista é o encaminhador de maior volume para dor de cabeça crônica — construa protocolos específicos para tratamento de enxaqueca crônica refratária."),
    ],
    faq_list=[
        ("Qual é a especialidade médica que trata dor crônica?", "A área de medicina da dor não é uma especialidade formal única — pode ser exercida por médicos de diferentes especialidades que fazem formação complementar em dor. As especialidades mais comuns em centros de dor são: anestesiologia (especialidade com maior tradição em procedimentos de dor intervencionista), neurologia (foco em neuropatias e cefaleia crônica), reumatologia (fibromialgia e dores articulares), medicina física e reabilitação (fisiatria — abordagem funcional). O título de Especialista em Dor é concedido pela Sociedade Brasileira para o Estudo da Dor (SBED) em parceria com o CFM."),
        ("O que é neuromodulação e para quais condições é indicada?", "Neuromodulação é uma família de técnicas que modula a atividade do sistema nervoso por meios elétricos, magnéticos ou farmacológicos para controlar a dor refratária. As principais técnicas são: Estimulação Medular (SCS — implante de eletrodo epidural que estimula a medula com corrente elétrica), Estimulação Transcraniana por Corrente Contínua (tDCS — não invasiva), e Bomba Intratecal (implante de reservatório de morfina com liberação direta no líquor). A neuromodulação é indicada para: dor neuropática refratária, síndrome de dor regional complexa (SDRC), lombalgia pós-cirúrgica, angina refratária e dor oncológica."),
        ("Como uma clínica de dor pode lidar com o risco de abuso de opioides?", "Implante um programa de opioid stewardship com: triagem de risco de abuso (ORT — Opioid Risk Tool) antes de iniciar opioide, contrato de uso de opioides assinado pelo paciente (compromisso de não buscar prescrição de outros médicos, de usar apenas a farmácia indicada e de comparecer a todas as consultas), monitoramento por dosagem de opioides na urina (periódico e aleatório), vigilância de múltiplos prescritores via SCTIE/ANVISA, e protocolo de redução gradual (desmame) para pacientes com uso problemático identificado."),
    ]
)

# Article 4325 — SaaS sales: centros de diagnóstico por imagem (TC, RM, PET-CT)
art(
    slug="vendas-para-o-setor-de-saas-de-gestao-de-centros-de-diagnostico-por-imagem-tc-rm-pet-ct",
    title="Vendas para SaaS de Gestão de Centros de Diagnóstico por Imagem (TC, RM, PET-CT) | ProdutoVivo",
    desc="Como vender SaaS de gestão para centros de diagnóstico por imagem com TC, RM e PET-CT: abordagem consultiva, demonstração de valor e estratégias de conversão.",
    h1="Vendas para SaaS de Gestão de Centros de Diagnóstico por Imagem (TC, RM, PET-CT)",
    lead="Centros de diagnóstico por imagem de alta complexidade operam equipamentos que custam de R$ 1 a R$ 15 milhões por unidade e precisam de gestão precisa de agendamento, laudos radiológicos, rastreabilidade de contraste e faturamento de exames de alto valor. Vender SaaS para esse segmento exige conhecimento profundo das operações de radiologia e capacidade de demonstrar impacto direto na rentabilidade do equipamento.",
    sections=[
        ("Operações de Centros de Diagnóstico por Imagem de Alta Complexidade", "Um centro de imagem avançado opera: Tomografia Computadorizada (TC — multidetectora, 64 a 256 cortes), Ressonância Magnética (RM — 1,5T ou 3T), PET-CT (para oncologia e neurologia), Raio-X digital e Mamografia digital. O fluxo envolve: agendamento específico por equipamento (RM requer triagem de contraindicações — marca-passo, implantes metálicos; PET-CT requer preparo com glucose controlada), administração de contraste (iodado para TC, gadolínio para RM — com protocolo de triagem de alergia e função renal), aquisição das imagens, laudo por radiologista (local ou via teleradiologia) e entrega digital ao paciente e ao médico solicitante."),
        ("Mapeamento do Decisor: Radiologista e Diretor Técnico", "O decisor técnico é o radiologista diretor ou o médico especialista responsável. Em centros maiores (redes de diagnóstico como Fleury, DASA, Hermes Pardini), há um gerente de operações e um gerente de TI. O radiologista prioriza: integridade do sistema PACS (Picture Archiving and Communication System) para armazenamento e visualização de imagens, workflow de laudo que minimize o tempo de assinatura e maximize o throughput por radiologista, e integração com o HIS do hospital referenciador para receber solicitações e enviar laudos digitalmente."),
        ("Demo: Agendamento de Alta Complexidade e Workflow de Laudo", "Demonstre: (1) agendamento por equipamento com triagem automática de contraindicações (perguntas sobre marca-passo, clipes cirúrgicos, gravidez para RM); (2) protocolo de contraste integrado ao agendamento (solicitação de creatinina prévia para TC com contraste); (3) recebimento de DICOM do equipamento no PACS integrado ao prontuário; (4) workflow de laudo com voice recognition (reconhecimento de voz para ditado do laudo — reduz 60% do tempo de laudo); (5) entrega digital automatizada do laudo ao médico solicitante e ao paciente via portal."),
        ("Faturamento de Exames de Alto Custo: TC, RM e PET-CT", "O faturamento de imagem de alta complexidade é altamente regulado: TC de alta resolução varia de R$ 400 a R$ 2.500 por convênio dependendo do protocolo e do número de fases (sem contraste, com contraste, com e sem contraste = 3x o valor unitário); RM de corpo inteiro ou espectroscopia atinge R$ 1.500 a R$ 8.000; PET-CT com FDG é faturado via APAC para pacientes oncológicos (R$ 5.000 a R$ 12.000). Cada exame tem código TUSS específico por protocolo — erros de codificação resultam em glosas significativas."),
        ("Teleradiologia como Expansão de Mercado", "A teleradiologia — laudar exames remotamente via internet — permite que um centro de imagem em cidade menor tenha acesso a radiologistas especialistas (neuroradiologista, cardiologista de imagem, músculo-esquelético) que não residem na região. Para o SaaS, a teleradiologia abre um novo segmento: hospitais e clínicas sem radiologista próprio que precisam de plataforma para envio de DICOM e recebimento de laudo digital. O mercado de teleradiologia cresce a 25% ao ano no Brasil — especialmente em regiões Norte e Nordeste com déficit de especialistas."),
    ],
    faq_list=[
        ("O que é PACS e por que é fundamental para centros de imagem?", "PACS (Picture Archiving and Communication System) é o sistema que armazena, gerencia e distribui imagens médicas digitais (radiografias, TCs, RMs) em formato DICOM. Um PACS integra: as modalidades (equipamentos de imagem que enviam DICOM ao PACS), as estações de laudação dos radiologistas, o RIS (Radiology Information System — que gerencia agendamentos e laudos) e o HIS do hospital ou clínica (que recebe os laudos digitais). Sem um PACS funcional, o centro de imagem não consegue operar — é a infra-estrutura central da radiologia digital."),
        ("Como um SaaS pode ajudar a aumentar o throughput de um centro de RM?", "O throughput de uma RM é medido em exames/dia. Uma RM de 1,5T bem operada faz 10 a 15 exames/dia de corpo inteiro (60 a 90 min/exame). Para maximizar: agendamento otimizado que minimiza setups entre exames similares (agrupar exames de abdome juntos, depois exames de cabeça), confirmação automática 24h antes para reduzir no-show (cada slot desperdiçado custa R$ 300 a R$ 1.000), alerta de preparo específico (paciente jejum para exames com sedação, controle de glicemia para PET-CT), e dashboards de tempo de giro entre exames para identificar gargalos operacionais."),
        ("Como a inteligência artificial está impactando a radiologia e o que o SaaS deve oferecer?", "A IA em radiologia está transformando o laudo: ferramentas de Computer-Aided Detection (CAD) identificam achados suspeitos (nódulos pulmonares, lesões mamográficas, fracturas vertebrais) e os destacam automaticamente na imagem para o radiologista. O SaaS deve integrar-se com soluções de IA radiológica (como as da Enlitic, Arterys, ou fabricantes locais) via API, inserindo os achados do CAD no workflow de laudo do radiologista. Isso reduz o tempo de laudo e aumenta a sensibilidade diagnóstica — argumentos de valor clínico e operacional ao mesmo tempo."),
    ]
)

# Article 4326 — Consulting: gestão de product management e cultura de produto
art(
    slug="consultoria-de-gestao-de-product-management-e-cultura-de-produto",
    title="Consultoria de Gestão de Product Management e Cultura de Produto | ProdutoVivo",
    desc="Como estruturar e monetizar uma consultoria de product management e cultura de produto: metodologias de discovery, roadmap e construção de times de produto.",
    h1="Consultoria de Gestão de Product Management e Cultura de Produto",
    lead="Product Management evoluiu de função operacional de software para disciplina estratégica que define o futuro dos produtos digitais. Empresas que não têm product managers capacitados, processos de discovery rigorosos e roadmaps bem priorizados tomam decisões de produto com base em intuição — e desperdiçam recursos de desenvolvimento em funcionalidades que os usuários não precisam. Consultorias de PM têm demanda crescente em fintechs, healthtechs, e-commerces e qualquer empresa que vive ou morre pelo produto.",
    sections=[
        ("O Que Faz uma Consultoria de Product Management", "A consultoria atua em: (1) Diagnóstico da maturidade de produto — avaliação dos processos de discovery, priorização, roadmap e métricas do time de produto atual; (2) Construção de processos de product discovery — pesquisa de usuário, entrevistas, análise de dados, definição de problemas e oportunidades; (3) Desenvolvimento de roadmap estratégico — priorização baseada em impacto no usuário e no negócio, alinhamento com stakeholders; (4) Formação do time de produto — recrutamento, onboarding e treinamento de PMs; (5) Implantação de métricas de produto (North Star Metric, HEART, OKRs de produto)."),
        ("Product Discovery: a Base de um Produto que Funciona", "Discovery é o processo de descobrir os problemas reais dos usuários antes de construir a solução. Um bom processo de discovery inclui: entrevistas em profundidade com usuários (mínimo 5 a 10 por ciclo de discovery), análise de dados comportamentais (onde os usuários ficam presos, o que buscam, o que abandonam), mapa de jornada do usuário com pontos de dor identificados, definição de oportunidades de produto (qual problema vale resolver e por que agora), e validação de hipóteses de solução antes da construção (protótipos, wizard-of-oz, landing pages de teste). Companies que fazem discovery bem constroem o produto certo."),
        ("Roadmap de Produto: Estratégia vs. Lista de Features", "Um roadmap estratégico não é uma lista de funcionalidades com datas — é a expressão da estratégia de produto em termos de problemas a resolver e resultados esperados. A consultoria ajuda a: definir os OKRs de produto alinhados à estratégia de negócio (não metas de output, mas de outcome — qual mudança de comportamento do usuário queremos alcançar?), priorizar iniciativas pelo framework RICE (Reach × Impact × Confidence ÷ Effort), comunicar o roadmap a stakeholders distintos com linguagem adequada (investidores, desenvolvimento, marketing, suporte) e manter o roadmap vivo — revisado trimestralmente conforme os aprendizados."),
        ("Cultura de Produto: Empoderamento vs. Alinhamento", "Cultura de produto é o conjunto de princípios e práticas que definem como a empresa toma decisões de produto. Os dois extremos: (1) Feature factory — PMs executam listas de requisitos de stakeholders sem autonomia para descobrir ou questionar; (2) Time de produto empoderado — PMs definem o problema, têm autonomia para escolher a solução e são responsabilizados pelos resultados (outcomes). A consultoria ajuda lideranças a fazerem a transição de feature factory para times empoderados — mudança cultural que requer alinhamento de CEO, VP de Produto e desenvolvimento."),
        ("Precificação e Modelos de Engajamento", "Diagnóstico de maturidade de produto: R$ 60 mil a R$ 150 mil. Programa de formação de PMs (training + coaching individual): R$ 80 mil a R$ 250 mil. Construção de roadmap e processo de discovery: R$ 100 mil a R$ 300 mil. Embedded PM sênior (consultor como PM interino por 3 a 6 meses): R$ 25 mil a R$ 60 mil/mês. Retainer de advisory de produto para C-level (revisão mensal de estratégia de produto, participação em planning trimestral): R$ 15 mil a R$ 40 mil/mês. O mercado de consultoria de PM é relativamente novo no Brasil — com poucos players especializados e demanda crescente de startups e empresas digitais."),
    ],
    faq_list=[
        ("Qual é a diferença entre um Product Manager e um Project Manager?", "Product Manager (PM) é responsável pelo sucesso do produto — define a estratégia, prioriza o que construir e garante que o produto resolve os problemas dos usuários e atinge os objetivos do negócio. É orientado ao outcome (resultado) e ao por quê e o quê. Project Manager é responsável pela entrega do projeto — planeja, coordena recursos e garante que o projeto seja entregue no prazo e no orçamento. É orientado ao output (entrega) e ao como e quando. Em empresas de produto digital maduras, o PM trabalha com times de engenharia e design autônomos, sem necessidade de Project Manager separado."),
        ("O que é a North Star Metric e como definir a certa para um produto?", "A North Star Metric (NSM) é o único indicador que melhor captura o valor que o produto entrega aos usuários — e que, quando cresce, prediz o crescimento sustentável do negócio. Exemplos: Spotify — 'minutos de música ouvida por usuário'; Airbnb — 'noites de hospedagem agendadas'; WhatsApp — 'mensagens enviadas/dia'. Para definir a NSM correta: ela deve refletir a entrega de valor ao usuário (não receita — receita é consequência), ser mensurável em tempo real, ser acionável pelo time de produto (não dependente exclusivamente de fatores externos) e ser única (uma só métrica, não um painel)."),
        ("Quando uma empresa deve contratar um consultor de product management em vez de um PM interno?", "Consultores são ideais quando: (1) A empresa está estruturando pela primeira vez a área de produto e precisa de expertise para não reinventar a roda; (2) Há um projeto específico de redesenho de produto ou de lançamento de nova plataforma que requer capacidade extra por tempo limitado; (3) O VP de Produto ou CPO precisa de um parceiro externo para pensar estratégia de produto sem as limitações políticas internas; (4) A empresa quer acelerar a maturidade de PMs internos com coaching e treinamento sem contratar um líder sênior permanente. PMs internos são melhores para construção de produto contínua a longo prazo."),
    ]
)

# ── sitemap.xml ───────────────────────────────────────────────────────────────
content = open('public/sitemap.xml').read()
new_urls = (
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-crm-e-gestao-de-vendas-para-pmes/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-clinicas-de-angiologia-e-cirurgia-vascular-minimamente-invasiva/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/vendas-para-o-setor-de-saas-de-gestao-de-centros-de-medicina-estetica-e-tratamentos-corporais/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/consultoria-de-gestao-de-crise-e-comunicacao-de-crise/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-conformidade-fiscal-e-tributaria/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/gestao-de-clinicas-de-dor-cronica-e-medicina-da-dor/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/vendas-para-o-setor-de-saas-de-gestao-de-centros-de-diagnostico-por-imagem-tc-rm-pet-ct/</loc></url>'
    '<url><loc>https://produtovivo.com.br/blog/consultoria-de-gestao-de-product-management-e-cultura-de-produto/</loc></url>'
)
open('public/sitemap.xml', 'w').write(content.replace('</urlset>', new_urls + '</urlset>'))

# ── trilha.html ───────────────────────────────────────────────────────────────
content = open('public/trilha.html').read()
new_items = (
    '<li><a href="/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-crm-e-gestao-de-vendas-para-pmes/">Gestao De Negocios De Empresa De B2b Saas De Crm E Gestao De Vendas Para Pmes</a></li>\n'
    '<li><a href="/blog/gestao-de-clinicas-de-angiologia-e-cirurgia-vascular-minimamente-invasiva/">Gestao De Clinicas De Angiologia E Cirurgia Vascular Minimamente Invasiva</a></li>\n'
    '<li><a href="/blog/vendas-para-o-setor-de-saas-de-gestao-de-centros-de-medicina-estetica-e-tratamentos-corporais/">Vendas Para O Setor De Saas De Gestao De Centros De Medicina Estetica E Tratamentos Corporais</a></li>\n'
    '<li><a href="/blog/consultoria-de-gestao-de-crise-e-comunicacao-de-crise/">Consultoria De Gestao De Crise E Comunicacao De Crise</a></li>\n'
    '<li><a href="/blog/gestao-de-negocios-de-empresa-de-b2b-saas-de-conformidade-fiscal-e-tributaria/">Gestao De Negocios De Empresa De B2b Saas De Conformidade Fiscal E Tributaria</a></li>\n'
    '<li><a href="/blog/gestao-de-clinicas-de-dor-cronica-e-medicina-da-dor/">Gestao De Clinicas De Dor Cronica E Medicina Da Dor</a></li>\n'
    '<li><a href="/blog/vendas-para-o-setor-de-saas-de-gestao-de-centros-de-diagnostico-por-imagem-tc-rm-pet-ct/">Vendas Para O Setor De Saas De Gestao De Centros De Diagnostico Por Imagem Tc Rm Pet Ct</a></li>\n'
    '<li><a href="/blog/consultoria-de-gestao-de-product-management-e-cultura-de-produto/">Consultoria De Gestao De Product Management E Cultura De Produto</a></li>'
)
open('public/trilha.html', 'w').write(content.replace('</ul>', new_items + '\n</ul>', 1))

print("Done — batch 1418")
