import os, json, pathlib

BASE   = os.path.join(os.path.dirname(__file__), "blog")
DOMAIN = "https://produtovivo.com.br"
PIXEL  = "4520253334926563"

TMPL = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)}};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init','{pixel}');fbq('track','PageView');
</script>
<style>
body{{font-family:sans-serif;margin:0;padding:0;color:#222}}
header{{background:#0a7c4e;padding:16px 24px}}
header a{{color:#fff;text-decoration:none;font-size:1.3rem;font-weight:700}}
main{{max-width:860px;margin:40px auto;padding:0 20px}}
h1{{font-size:2rem;color:#0a7c4e}}
h2{{font-size:1.3rem;color:#065f3a;margin-top:32px}}
p{{line-height:1.7}}
.lead{{font-size:1.1rem;color:#444}}
.faq{{background:#f4faf7;border-left:4px solid #0a7c4e;padding:20px 24px;margin-top:40px}}
.faq h2{{margin-top:0}}
.faq-item{{margin-bottom:20px}}
.faq-item h3{{margin-bottom:4px;color:#065f3a}}
footer{{text-align:center;padding:32px;color:#777;font-size:.9rem;margin-top:60px}}
</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<header><a href="/">ProdutoVivo</a></header>
<main>
<h1>{h1}</h1>
<p class="lead">{lead}</p>
{body}
<div class="faq">
<h2>Perguntas Frequentes</h2>
{faqs}
</div>
</main>
<footer>© 2025 ProdutoVivo · Conteúdo informativo sobre gestão e tecnologia</footer>
</body>
</html>"""

def art(slug, title, desc, h1, lead, sections, faq_list):
    url = f"{DOMAIN}/blog/{slug}/"
    body_html = ""
    for sec_title, sec_body in sections:
        body_html += f"<h2>{sec_title}</h2>\n<p>{sec_body}</p>\n"
    faqs_html = ""
    schema_faqs = []
    for q, a in faq_list:
        faqs_html += f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>\n'
        schema_faqs.append({"@type": "Question", "name": q,
                             "acceptedAnswer": {"@type": "Answer", "text": a}})
    schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage",
                         "mainEntity": schema_faqs}, ensure_ascii=False)
    html = TMPL.format(title=title, desc=desc, url=url, pixel=PIXEL,
                       h1=h1, lead=lead, body=body_html, faqs=faqs_html, schema=schema)
    out_dir = os.path.join(BASE, slug)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

# Article 4727 — B2B SaaS: Freight and carrier management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-transportadoras-e-gestao-de-frete",
    title="Gestão de Negócios de Empresa de B2B SaaS de Transportadoras e Gestão de Frete",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para transportadoras e gestão de frete: modelo de negócio, TMS, rastreamento, go-to-market e métricas do setor logístico.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Transportadoras e Gestão de Frete",
    lead="O transporte rodoviário responde por 65% da matriz logística brasileira, com mais de 150 mil transportadoras registradas na ANTT. Plataformas de TMS (Transportation Management System) e gestão de frete são infraestrutura crítica para embarcadores e transportadoras — cobrindo cotação, rastreamento, gestão de documentos fiscais e pagamento de frete.",
    sections=[
        ("O Mercado de TransportTech SaaS",
         "O mercado de SaaS para transporte e frete é dividido por perfil de usuário: embarcadores (indústrias, distribuidoras, e-commerces que contratam frete de terceiros — precisam de TMS para cotação multi-transportadora, contratação, rastreamento e auditoria de faturas de frete), transportadoras (empresas de transporte que precisam de TMS para gestão de pedidos, programação de cargas, roteirização de entregas, gestão de motoristas e auditoria de CTe), e marketplaces de frete (plataformas que conectam embarcadores a transportadoras — como Fretebras, Transplace, CargoX). Os módulos mais demandados incluem: cotação de frete em tempo real com múltiplas transportadoras, rastreamento de carga por posição do veículo ou milestone de entrega, gestão de CT-e e MDF-e (documentos fiscais obrigatórios no transporte), e pagamento e auditoria de frete (confrontar o frete cobrado vs. frete acordado — uma das maiores fontes de perda em logística)."),
        ("TMS: O Sistema Central do Embarcador e da Transportadora",
         "O TMS (Transportation Management System) é o ERP da operação de transporte. Para o embarcador, o TMS faz: planejamento de expedição (quais pedidos saem em qual carga, para qual transportadora, em qual prazo), cotação de frete (comparar custo e prazo de múltiplas transportadoras para a mesma carga), emissão de CT-e e integração com SEFAZ, rastreamento de entregas (visibilidade end-to-end da carga do embarcador ao cliente final), e auditoria de faturas de frete (confrontar o frete cobrado pelo transportador com o frete calculado pelo TMS — discrepâncias acima de 1-2% são comuns e custam caro). Para a transportadora, o TMS adiciona: programação de carga (otimização do preenchimento do veículo — carga de retorno para evitar viagens vazias), gestão de motoristas (escalas, documentos, performance), e gestão de ocorrências (atrasos, avarias, furtos)."),
        ("Integração Fiscal no Transporte: CTe, MDFe e NF-e",
         "O transporte rodoviário de cargas no Brasil tem obrigações fiscais específicas que são pré-requisito para operar: CT-e (Conhecimento de Transporte Eletrônico — o documento fiscal que habilita o transporte da carga, obrigatório desde 2013 para transportadoras de cargas), MDF-e (Manifesto Eletrônico de Documentos Fiscais — obrigatório para veículos que transportam múltiplas cargas de diferentes remetentes, ou que transitam por mais de um estado), e integração com a NF-e da carga (o CT-e deve referenciar a NF-e da mercadoria transportada). Plataformas de TMS que automatizam a emissão do CT-e e MDF-e integradas com a SEFAZ, e que monitoram a situação dos documentos (autorizado, cancelado, denegado) eliminam um dos maiores gargalos operacionais das transportadoras — que ainda dependem de processos manuais ou de sistemas legados para essa obrigação."),
        ("Marketplace de Frete: Conectando Embarcadores e Transportadoras",
         "Os marketplaces de frete (freight brokers digitais) resolvem a ineficiência estrutural do mercado: embarcadores que têm carga para transportar e transportadoras com veículos disponíveis não se encontram facilmente — especialmente para cargas spot (não regulares) e para cargas de retorno. O Fretebras — maior plataforma do tipo no Brasil — conecta mais de 400 mil transportadores a embarcadores em todo o país. O modelo de negócio inclui: plano de assinatura para transportadoras (acesso aos anúncios de carga), plano para embarcadores (visibilidade da carga para transportadoras qualificadas), e take rate sobre transações intermediadas. Plataformas que adicionam serviços financeiros (antecipação de recebíveis de frete, seguro de carga, conta digital para caminhoneiro) aumentam o LTV e criam vantagem competitiva. O caminhoneiro autônomo — que representa 60% da frota rodoviária brasileira — é o maior usuário e o maior beneficiário desses marketplaces."),
        ("Métricas de Saúde do TransportTech SaaS",
         "As métricas de produto incluem: cargas gerenciadas por mês (volume que cresce com a operação do cliente), CT-e emitidos pela plataforma (uso ativo do módulo fiscal — alta correlação com adoção real), e NPS do gestor de logística. As métricas de negócio incluem: MRR por perfil de cliente (embarcador enterprise tem ticket muito maior que transportadora SMB), NRR (embarcadores que crescem em volume de expedição pagam mais em modelos baseados em volume), churn sazonal (operações com sazonalidade — como e-commerce no Natal — expandem e contraem ao longo do ano), e CAC por canal (associações de transporte como NTC&Logística, CNT — confederação do transporte — e eventos como Intermodal South America são os principais canais de acesso ao decisor do setor).")
    ],
    faq_list=[
        ("O que é CT-e e quando é obrigatório?",
         "CT-e (Conhecimento de Transporte Eletrônico) é o documento fiscal digital que comprova a prestação do serviço de transporte rodoviário, ferroviário, aquaviário, aéreo ou dutoviário de cargas. É obrigatório para todas as transportadoras que prestam serviço de transporte interestadual ou intermunicipal de cargas — com raras exceções para pequenos produtores rurais e alguns casos específicos. O CT-e substitui os documentos em papel (CTRC, CTMF) e deve ser emitido antes do início do transporte — a carga não pode circular sem o CT-e autorizado pela SEFAZ. A multa por transportar carga sem CT-e varia por estado mas pode chegar a 100% do valor do serviço. O CT-e é também o documento que habilita o crédito de ICMS sobre o serviço de transporte para o tomador — o que o torna relevante não apenas fiscalmente mas também comercialmente."),
        ("Como funciona a auditoria de frete e qual seu impacto financeiro?",
         "Auditoria de frete é o processo de confrontar o frete cobrado pelo transportador com o frete que deveria ser cobrado com base no contrato, tabela de preços e parâmetros da carga (peso, cubagem, distância, tipo de serviço). Inconsistências são mais comuns do que se imagina: erro no cálculo de cubagem (peso cúbico vs. peso real), cobrança de adicionais não contratuais (pedágio, GRIS, TAS), taxa de entrega ao destinatário não acordada, e reavalias (cobranças de diferença de peso não verificadas). Empresas com volume de frete acima de R$500 mil/mês sem auditoria sistemática frequentemente pagam de 3% a 8% a mais do que deveriam. Uma plataforma de TMS com módulo de auditoria de frete automatizado paga seu próprio custo em poucos meses de uso — o ROI é um dos mais claros e rápidos no mercado de software logístico."),
        ("Qual a diferença entre TMS, WMS e ERP logístico?",
         "TMS (Transportation Management System) gerencia o transporte — do embarcador à entrega no destino: cotação de frete, contratação de transportadora, tracking de carga, gestão de CT-e, auditoria de frete. WMS (Warehouse Management System) gerencia o armazém — do recebimento à expedição: controle de estoque por localização (endereço de prateleira), picking, packing, expedição, gestão de inventário. ERP logístico integra ambos com o financeiro, compras e vendas — visão integrada da cadeia. Na prática, muitas empresas usam os três: o ERP centraliza pedidos e finanças, o WMS gerencia o armazém, e o TMS gerencia o transporte. A integração entre os três sistemas — para que um pedido de venda acione automaticamente o WMS (separação) e o TMS (cotação e contratação de frete) — é o grande desafio de arquitetura logística das empresas de médio e grande porte.")
    ]
)

# Article 4728 — Clinic: Urology and men's health
art(
    slug="gestao-de-clinicas-de-urologia-e-saude-do-homem",
    title="Gestão de Clínicas de Urologia e Saúde do Homem",
    desc="Guia de gestão para clínicas de urologia e saúde do homem: fluxo de atendimento, rastreamento de câncer de próstata, litíase renal, disfunção erétil e indicadores de qualidade.",
    h1="Gestão de Clínicas de Urologia e Saúde do Homem",
    lead="A urologia trata doenças do trato urinário em homens e mulheres, e do sistema reprodutor masculino. É uma especialidade de alta demanda com crescimento impulsionado pelo envelhecimento da população — câncer de próstata, litíase renal e hiperplasia prostática benigna afetam dezenas de milhões de brasileiros e exigem acompanhamento especializado contínuo.",
    sections=[
        ("O Escopo da Urologia Clínica e Cirúrgica",
         "A urologia abrange: oncologia urológica (câncer de próstata — o mais comum em homens no Brasil, com 70 mil novos casos por ano; câncer de bexiga; câncer de rim; câncer de testículo), litíase urinária (cálculos renais, ureterais e vesicais — prevalência de 10% na população adulta), hiperplasia prostática benigna (HPB — sintomas obstrutivos do trato urinário inferior em homens acima de 50 anos, altamente prevalente), disfunção erétil e saúde sexual masculina, infertilidade masculina (avaliação andrológica do casal infértil), incontinência urinária (em homens e mulheres, em parceria com uroginecologia em mulheres), e nefrologia cirúrgica (rim transplantado, fístulas arteriovenosas — em parceria com nefrologia). O rastreamento de câncer de próstata com PSA e o toque retal são os procedimentos preventivos de maior impacto em volume ambulatorial."),
        ("Rastreamento de Câncer de Próstata: O Procedimento de Maior Volume",
         "O câncer de próstata é o segundo tumor mais incidente em homens no Brasil (o primeiro é o de pele não-melanoma). O rastreamento é feito pelo PSA (Antígeno Prostático Específico) sérico e pelo toque retal — a partir dos 50 anos em homens de risco médio, ou a partir dos 45 anos em negros e homens com histórico familiar de primeiro grau. A biópsia de próstata é indicada quando o PSA está elevado para a faixa etária ou quando o toque retal é suspeito — e cada vez mais é guiada por ressonância magnética (biópsia de fusão de próstata — RM + ultrassom) para aumentar a taxa de detecção de tumores clinicamente significativos e reduzir biópsias desnecessárias. Clínicas de urologia com sala de ultrassonografia transretal própria têm o módulo de biópsia disponível imediatamente — aumentando o ticket e a conveniência."),
        ("Litíase Renal: Alto Volume e Procedimentos de Alto Valor",
         "A litíase renal (cálculos nos rins e vias urinárias) afeta 10% da população adulta brasileira e tem alta taxa de recorrência (50% dos pacientes têm novo episódio em 5 anos sem prevenção). A cólica renal — dor intensa por obstrução do ureter por cálculo — é uma das emergências médicas mais frequentes no Brasil. O tratamento depende do tamanho e localização do cálculo: cálculos menores passam espontaneamente com hidratação e analgesia; cálculos maiores podem precisar de litotripsia extracorpórea por ondas de choque (LECO — procedimento ambulatorial que fragmenta o cálculo sem cirurgia), ureteroscopia com laser (endoscopia — remove cálculo ureterais e renais pelo canal natural) ou nefrolitotomia percutânea (para cálculos renais grandes — cirurgia minimamente invasiva). Clínicas de urologia que têm litotripsia própria têm um serviço de alto valor e alta demanda que diferencia o portfólio."),
        ("Medicina do Homem: Prevenção e Saúde Sexual",
         "A medicina do homem — voltada para a saúde preventiva masculina e para condições como disfunção erétil, hipogonadismo e infertilidade — é o segmento de maior crescimento em urologia. Historicamente, homens buscam menos serviços de saúde preventiva — o que cria uma demanda reprimida enorme quando bem endereçada. Serviços de check-up masculino (PSA, testosterona, perfil lipídico, glicemia, pressão arterial — com consulta urológica integrada) são produtos de medicina preventiva com boa aceitação no público masculino de 40 a 60 anos de classe média alta. A telemedicina em urologia — especialmente para acompanhamento de pacientes de HPB e disfunção erétil em zonas remotas — expandiu o alcance de serviços que antes exigiam presença física para procedimentos que podem ser gerenciados remotamente."),
        ("Indicadores de Qualidade em Urologia",
         "As métricas clínicas incluem: taxa de detecção de câncer de próstata clinicamente significativo por biópsia (indicador de qualidade da seleção dos pacientes para biópsia — biópsias desnecessárias têm risco de complicação sem benefício), taxa de eliminação espontânea de cálculos após tratamento conservador (indica qualidade do seguimento clínico), taxa de recorrência de cálculos renais em pacientes com acompanhamento preventivo (indicador de efetividade do programa de litíase), e NPS. As métricas de negócio incluem: mix de procedimentos (LECO, ureteroscopia, biópsia de fusão — procedimentos de alto ticket que definem a rentabilidade da clínica), taxa de retorno para seguimento de HPB e PSA (receita recorrente previsível de pacientes crônicos), e taxa de conversão de rastreamento para biópsia (quando PSA elevado — indica que o fluxo clínico está bem estruturado e o paciente não abandona o seguimento).")
    ],
    faq_list=[
        ("A partir de qual idade devo fazer o exame de próstata?",
         "O rastreamento de câncer de próstata — com PSA sérico e toque retal — é recomendado a partir dos 50 anos para homens de risco médio (sem histórico familiar, sem fatores de risco específicos). Para homens com histórico familiar de câncer de próstata em parente de primeiro grau (pai ou irmão) ou para homens negros (que têm maior incidência e pior prognóstico), o rastreamento deve ser iniciado a partir dos 45 anos. A SBU (Sociedade Brasileira de Urologia) recomenda que a decisão de rastrear seja tomada de forma compartilhada entre médico e paciente, após discussão dos benefícios (detecção precoce de tumores curáveis) e dos riscos (sobrediagnóstico de tumores indolentes que nunca causariam sintomas). O exame de PSA é realizado com um simples exame de sangue — não há justificativa para não fazer após os 50 anos."),
        ("Cálculo renal tem tratamento sem cirurgia?",
         "Sim — a maioria dos cálculos renais é tratável sem cirurgia aberta. As opções de tratamento minimamente invasivo incluem: conduta expectante com analgesia (cálculos menores de 5mm passam espontaneamente em 80% dos casos com boa hidratação e analgesia — o urologista acompanha por ultrassonografia), litotripsia extracorpórea por ondas de choque (LECO — ondas de choque geradas externamente fragmentam o cálculo sem corte, em sessão ambulatorial de 45 a 60 minutos sob sedação leve), ureteroscopia com laser holmium (endoscopia pelo canal natural — fragmenta cálculos ureterais e renais e remove os fragmentos), e nefrolitotomia percutânea (NLPC — mini-cirurgia com punção percutânea para cálculos renais grandes, mais de 2 cm, que não respondem à LECO). A cirurgia aberta para cálculo renal tornou-se rara com a evolução dos tratamentos endoscópicos e da LECO."),
        ("Disfunção erétil é sinal de problema cardíaco?",
         "Sim — a disfunção erétil (DE) é considerada um marcador precoce de doença cardiovascular, especialmente em homens abaixo de 60 anos. A ereção depende de fluxo sanguíneo adequado para os corpos cavernosos — que é prejudicado pelos mesmos fatores de risco que causam doença coronariana: hipertensão, diabetes, dislipidemia, tabagismo, sedentarismo. Estudos mostram que homens com DE têm risco 2 a 3 vezes maior de ter um evento cardiovascular (infarto, AVC) nos próximos 5 a 10 anos do que homens sem DE. Por isso, o urologista que atende um paciente com DE deve realizar avaliação cardiovascular completa — pressão arterial, glicemia, perfil lipídico — e considerar encaminhar ao cardiologista se houver fatores de risco. A DE não é apenas um problema de qualidade de vida: é um sinal de alerta sistêmico que salva vidas quando investigado adequadamente.")
    ]
)

# Article 4729 — SaaS sales: Corporate training and e-learning
art(
    slug="vendas-para-o-setor-de-saas-de-educacao-corporativa-e-elearning",
    title="Vendas para o Setor de SaaS de Educação Corporativa e E-learning",
    desc="Estratégias de vendas B2B para plataformas SaaS de educação corporativa e e-learning: como abordar CHROs, diretores de T&D e gestores de L&D para fechar contratos de LMS.",
    h1="Vendas para o Setor de SaaS de Educação Corporativa e E-learning",
    lead="O mercado de educação corporativa no Brasil movimenta R$15 bilhões por ano e cresce acelerado pela escassez de talentos e pela necessidade de upskilling contínuo. Plataformas LMS e de aprendizagem corporativa têm oportunidade enorme — mas vender para RH e T&D exige entender um comprador que equilibra impacto pedagógico, engajamento do colaborador e retorno sobre investimento.",
    sections=[
        ("O Ecossistema de EdTech Corporativa",
         "O mercado de SaaS para educação corporativa inclui: LMS (Learning Management System — plataforma de gestão de treinamentos, trilhas de aprendizado, avaliações e relatórios — como Moodle, TalentLMS, Docebo, SAP SuccessFactors Learning), plataformas de microlearning e mobile learning (conteúdo em pílulas de 3 a 5 minutos — como Axonify, EdApp), ferramentas de criação de conteúdo e-learning (authoring tools — Articulate 360, Adobe Captivate, iSpring — para equipes de T&D criarem seus próprios cursos), plataformas de learning experience (LXP — mais intuitivas que LMS, focadas em descoberta e recomendação de conteúdo — como Degreed, Cornerstone), e marketplaces de conteúdo corporativo (cursos prontos por especialistas — Coursera for Business, LinkedIn Learning, Udemy for Business). O mercado brasileiro tem players locais relevantes: Twygo, Spark, EAD Plataforma, Nuvemshop — focados nas especificidades do mercado nacional."),
        ("O Decisor em T&D Corporativo",
         "O decisor de educação corporativa é geralmente o CHRO, o diretor de T&D (Treinamento e Desenvolvimento) ou o gerente de L&D (Learning & Development) — em empresas menores, o gerente de RH acumula esse papel. Os critérios de decisão variam por perfil: o CHRO foca em impacto estratégico (a plataforma apoia a estratégia de talentos? melhora a retenção? desenvolve as competências do futuro?), o diretor de T&D foca em facilidade de criação de conteúdo e em métricas de aprendizagem (conclusão de cursos, NPS do aprendiz, evolução de competências), e o financeiro foca em custo por usuário e ROI. O IT entra como avaliador técnico de segurança, integração com Active Directory (SSO) e conformidade com LGPD. O caminho de venda mais eficiente é gerar um champion no T&D que defende internamente — mas o patrocínio do CHRO é necessário para aprovação do orçamento."),
        ("Conteúdo vs. Plataforma: A Dicotomia do Mercado",
         "O maior debate em educação corporativa SaaS é entre plataforma e conteúdo: a empresa deve investir em um LMS para hospedar conteúdo próprio, em conteúdo pronto (curadoria de cursos externos), ou em ambos? Plataformas de conteúdo como LinkedIn Learning e Udemy for Business oferecem catálogos de dezenas de milhares de cursos em inglês — com cobertura ampla mas pouca personalização para a cultura e os processos específicos da empresa. LMS com authoring tools permitem criar conteúdo personalizado (onboarding da empresa, treinamento de produtos próprios, compliance específico) — mas exigem equipe de T&D para produção. O modelo vencedor para empresas médias e grandes combina os dois: LMS próprio com conteúdo customizado para o core (cultura, processos, liderança) + licença de marketplace de conteúdo externo para hard skills técnicas e idiomas. A plataforma que oferece ambos nativamente tem vantagem de consolidação."),
        ("Gamificação e Engajamento: Do Problema à Solução",
         "O maior problema de educação corporativa não é a falta de conteúdo — é a falta de engajamento. A maioria das plataformas LMS tradicionais tem taxa de conclusão de cursos abaixo de 30% (o colaborador abre o curso, assiste 20% e nunca volta). As soluções de engajamento incluem: gamificação (pontos, badges, rankings, recompensas — criam motivação extrínseca que sustenta o engajamento no início), microlearning (pílulas de 3 a 5 minutos que cabem na rotina sem gerar a resistência do treinamento longo), social learning (fóruns, comentários, grupos de estudo — o aprendizado entre pares tem retenção muito maior do que a leitura passiva de conteúdo), e learning in the flow of work (conteúdo acessível no contexto do trabalho — no momento em que o colaborador precisa, via integração com Slack, Teams ou no CRM). Plataformas que demonstram taxas de conclusão acima de 70% em cases de referência têm argumento de venda muito mais forte do que as que entregam funcionalidades sem evidência de engajamento."),
        ("Métricas de Sucesso em EdTech Corporativa",
         "As métricas de produto incluem: usuários ativos por mês (MAU — o indicador de adoção real), taxa de conclusão de cursos (o benchmark saudável é acima de 60%), horas de aprendizado por colaborador por mês (indicador de profundidade de engajamento), e NPS do colaborador e do gestor de T&D. As métricas de negócio incluem: MRR por empresa com preço por assento (R$20 a R$100/colaborador/mês dependendo do tier e do mercado), NRR via expansão de assentos (empresas que crescem expandem naturalmente — NRR alto é comum em EdTech corporativa de sucesso), churn por ROI não percebido (o maior risco é renovação sem demonstrar impacto — o time de Customer Success deve proativamente construir o business case de renovação com dados de uso e impacto nos primeiros 60 dias), e CAC por canal (parceiros de consultoria de RH e T&D que indicam a plataforma têm CAC baixo e alta qualificação).")
    ],
    faq_list=[
        ("O que é LMS e como escolher o certo para a empresa?",
         "LMS (Learning Management System) é o sistema que hospeda, organiza e rastreia os treinamentos da empresa — permitindo criar cursos, matricular colaboradores, acompanhar progresso e gerar relatórios de conclusão e avaliação. A escolha do LMS adequado depende de: tamanho da empresa (soluções como TalentLMS e Twygo são excelentes para empresas de 100 a 5.000 colaboradores; Docebo e Cornerstone atendem enterprise acima de 5.000), necessidade de criação de conteúdo interno (a empresa tem equipe de T&D para criar cursos? então authoring tools integradas são importantes), integração com sistemas de RH (o LMS deve conectar com o HRIS para sincronizar colaboradores automaticamente — evitando cadastro manual), e orçamento (soluções open source como Moodle são gratuitas mas exigem TI para implementação; SaaS tem custo mensal mas sem custo de infraestrutura). Faça um piloto com a equipe de T&D antes de contratar — a usabilidade do sistema de criação de conteúdo é frequentemente o fator decisivo."),
        ("Treinamento presencial vs. EAD: qual mais eficaz?",
         "A eficácia depende do tipo de conteúdo e dos objetivos de aprendizagem. Treinamentos de habilidades práticas (operar uma máquina, atender um cliente no balcão, técnica cirúrgica) têm melhor resultado com presencial ou simulação — onde a prática física é possível. Treinamentos de conhecimento e conformidade (política da empresa, legislação, uso de sistemas, soft skills conceituais) têm eficácia comparável entre presencial e EAD quando o EAD é bem desenhado — com interatividade, exercícios práticos e avaliação. O modelo blended (híbrido — conteúdo online para a base teórica + encontro presencial para prática e discussão) tem a melhor evidência de eficácia combinando o melhor dos dois mundos: escalabilidade do EAD com profundidade do presencial. A escolha deve ser guiada pelos objetivos de aprendizagem, não pela preferência operacional de gestores."),
        ("Como medir o ROI de treinamento corporativo?",
         "O modelo de Kirkpatrick é o framework mais usado para avaliar o ROI de treinamento em 4 níveis: Reação (o aprendiz gostou do treinamento? — NPS do treinamento — fácil de medir, mas pouco correlacionado com resultado), Aprendizagem (o colaborador aprendeu? — avaliação antes e depois — indica se houve transferência de conhecimento), Comportamento (o colaborador aplicou no trabalho? — avaliação 30/60/90 dias após o treinamento — o nível mais relevante e mais difícil de medir), e Resultados (o treinamento impactou KPIs de negócio? — redução de erros, aumento de vendas, queda de acidentes — o ROI real). Medir o nível 4 é difícil mas possível: o time de vendas que passou pelo treinamento de produto aumentou a taxa de conversão em 8%? O time de operações que fez o treinamento de segurança reduziu acidentes em 30%? Esses números constroem o business case de renovação e expansão do programa de T&D.")
    ]
)

# Article 4730 — Consulting: Operations management and lean manufacturing
art(
    slug="consultoria-de-gestao-de-operacoes-e-lean-manufacturing",
    title="Consultoria de Gestão de Operações e Lean Manufacturing",
    desc="Como funciona a consultoria de gestão de operações e lean manufacturing: mapeamento de fluxo de valor, eliminação de desperdícios, implementação de ferramentas lean e métricas OEE.",
    h1="Consultoria de Gestão de Operações e Lean Manufacturing",
    lead="Operações enxutas — que entregam mais valor ao cliente usando menos recursos — são a fonte mais sustentável de vantagem competitiva em manufatura, serviços e logística. Consultoria de lean manufacturing e gestão de operações ajuda empresas a identificar e eliminar desperdícios sistematicamente, aumentando produtividade, qualidade e capacidade sem necessariamente investir em novos equipamentos.",
    sections=[
        ("O que é Lean Manufacturing e a Origem Toyota",
         "Lean manufacturing é um sistema de produção desenvolvido pela Toyota no pós-guerra — conhecido como Toyota Production System (TPS) — que busca maximizar o valor entregue ao cliente minimizando todos os tipos de desperdício (muda, em japonês). Os 8 tipos de desperdício lean são: superprodução (produzir mais do que o cliente pede), espera (tempo ocioso de pessoas ou equipamentos), transporte desnecessário (movimentação de material que não agrega valor), processamento excessivo (fazer mais do que o cliente precisa), estoque excessivo (além do necessário para a operação), movimentação desnecessária (de pessoas — ergonomia e layout), defeitos (retrabalho e sucata), e talento não utilizado (subutilização das capacidades das pessoas). A consultoria lean ajuda a identificar e priorizar a eliminação desses desperdícios por meio de ferramentas como VSM, 5S, Kaizen, SMED, TPM e Kanban."),
        ("Value Stream Mapping: A Ferramenta de Diagnóstico Central",
         "O VSM (Value Stream Mapping — Mapeamento de Fluxo de Valor) é a ferramenta mais importante do diagnóstico lean: mapeia o fluxo de material e informação do pedido do cliente até a entrega — identificando onde está o valor, onde está o desperdício, e qual é o tempo de atravessamento (lead time) total. O VSM atual mostra a situação como ela é: com todos os estoques intermediários, tempos de espera, retrabalhos e movimentações desnecessárias. O VSM futuro mostra a situação desejada: com fluxo contínuo, pull system, redução de estoques e lead time reduzido. A diferença entre o VSM atual e o futuro define o plano de melhoria. Um VSM bem feito geralmente revela que o tempo que agrega valor ao produto é apenas 1% a 5% do lead time total — o resto é espera e processamento desnecessário."),
        ("5S, Kaizen e SMED: As Ferramentas de Melhoria Contínua",
         "As ferramentas lean de implementação incluem: 5S (Seiri — separar, Seiton — organizar, Seiso — limpar, Seiketsu — padronizar, Shitsuke — sustentar — o alicerce da organização do posto de trabalho e da cultura de melhoria), Kaizen (evento focado de melhoria — equipe multifuncional trabalhando por 3 a 5 dias para resolver um problema específico com melhoria imediata), SMED (Single Minute Exchange of Die — redução do tempo de setup/troca de produto para menos de 10 minutos — que aumenta a flexibilidade da linha sem aumentar capacidade instalada), Kanban (sistema de sinalização visual para controle de produção puxada — o processo downstream sinaliza quando precisa de material, eliminando a superprodução), e Poka-Yoke (dispositivos à prova de erro — que impedem fisicamente que um defeito aconteça ou alertam imediatamente quando acontece). A implementação bem-sucedida dessas ferramentas requer comprometimento da liderança e treinamento da equipe operacional."),
        ("Lean em Serviços: Além da Manufatura",
         "O lean manufacturing foi originalmente desenvolvido para fábricas — mas seus princípios se aplicam a qualquer processo que transforma entradas em saídas: hospitais (lean healthcare — redução do tempo de espera do paciente, eliminar passos desnecessários no fluxo de atendimento), escritórios de contabilidade e serviços profissionais (lean office — redução do tempo de ciclo de entrega de serviço, eliminação de retrabalho), serviços de saúde (lean healthcare — o hospital que adotou lean reduz o tempo de alta hospitalar de 3 horas para 45 minutos), e logística (lean logistics — eliminação de movimentações desnecessárias no armazém, redução do tempo de separação). A consultoria de lean que sabe aplicar as ferramentas em contextos de serviço — não apenas em fábrica — tem mercado muito maior e pode cobrar ticket premium pelo conhecimento específico do setor."),
        ("Métricas de Operações: OEE e KPIs de Manufatura",
         "O OEE (Overall Equipment Effectiveness — Efetividade Global dos Equipamentos) é a métrica principal de eficiência em manufatura: combina Disponibilidade (% do tempo planejado em que o equipamento está disponível), Performance (velocidade real vs. velocidade teórica máxima), e Qualidade (% de peças boas vs. total produzido). OEE = Disponibilidade × Performance × Qualidade. Um OEE de 85% é considerado classe mundial — a maioria das fábricas brasileiras opera entre 50% e 70%. Outras métricas de operações incluem: lead time de produção (do pedido à entrega), tempo de throughput (velocidade de processamento), FPY (First Pass Yield — percentual de peças que passam pela primeira vez sem retrabalho), MTTR (Mean Time to Repair — tempo médio de reparo), MTBF (Mean Time Between Failures — tempo médio entre falhas), e custo de não qualidade (retrabalho, sucata, devoluções de cliente).")
    ],
    faq_list=[
        ("Lean é aplicável em pequenas e médias empresas?",
         "Sim — lean é ainda mais impactante em PMEs do que em grandes empresas, porque os desperdícios são relativamente maiores e o custo de implementação é menor. Uma fábrica de R$10 milhões de faturamento que reduz desperdícios em 15% gera R$1,5 milhão de impacto no resultado — um impacto muito mais significativo em termos percentuais do que o mesmo percentual em uma multinacional. Os desafios em PMEs incluem: menor número de pessoas disponíveis para liderar a melhoria (o dono acumula funções), resistência cultural maior (as pessoas conhecem o dono pessoalmente e a mudança é mais pessoal), e menor budget para consultoria externa. Por isso, consultorias lean para PMEs geralmente usam metodologias de implementação mais aceleradas (workshops de 3 a 5 dias com resultado imediato) em vez de projetos longos de transformação cultural. O Sebrae e o Senai oferecem programas subsidiados de lean para PMEs industriais."),
        ("Quanto tempo leva uma implementação lean?",
         "A velocidade depende do escopo da implementação. Um evento Kaizen focado em um processo específico leva de 3 a 5 dias de trabalho intensivo e produz melhoria imediata e mensurável naquele processo. Uma implementação mais ampla (transformação de uma célula de produção ou de um fluxo de valor completo) leva de 3 a 6 meses. Uma transformação lean de toda a fábrica — criando uma cultura de melhoria contínua sustentável — leva de 2 a 5 anos. A chave para sustentabilidade é o development de líderes internos de lean (facilitadores de kaizen, green belts, líderes de célula) que perpetuam a melhoria após o consultor externo sair. Implementações lean que dependem exclusivamente do consultor externo para manter o ritmo de melhoria regridem rapidamente quando o consultor se vai — o maior erro de projetos lean é não investir no desenvolvimento da capacidade interna."),
        ("Lean vs. Six Sigma: qual a diferença?",
         "Lean e Six Sigma são abordagens complementares que frequentemente são combinadas (Lean Six Sigma). Lean foca em velocidade e eliminação de desperdícios — reduzir o lead time, eliminar atividades que não agregam valor, criar fluxo contínuo. Six Sigma foca em qualidade e redução de variabilidade — usar métodos estatísticos (DMAIC — Define, Measure, Analyze, Improve, Control) para identificar as causas raiz de defeitos e reduzir a variação do processo até 3,4 defeitos por milhão de oportunidades (6σ). Lean resolve: 'estamos fazendo as coisas rápido mas às vezes errado?' Não — Lean não resolve isso diretamente. Six Sigma resolve: 'estamos fazendo as coisas com boa qualidade mas lentamente e com muito desperdício?' Não — Six Sigma não resolve isso diretamente. Lean Six Sigma combina os dois: fluxo rápido, sem desperdício e com qualidade consistente. A certificação Lean Six Sigma (Green Belt, Black Belt) é a mais valorizada em gestão de operações no Brasil.")
    ]
)

# Article 4731 — B2B SaaS: Aesthetic clinics and beauty management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-clinicas-de-estetica-e-beleza",
    title="Gestão de Negócios de Empresa de B2B SaaS de Clínicas de Estética e Beleza",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para clínicas de estética e salões de beleza: modelo de negócio, funcionalidades, go-to-market e métricas do mercado beauty.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Clínicas de Estética e Beleza",
    lead="O mercado de beleza e estética brasileiro é o quarto maior do mundo, com mais de 1,5 milhão de estabelecimentos entre salões de beleza, barbearias e clínicas de estética. Plataformas SaaS para esse mercado — agenda online, gestão de clientes, financeiro e fidelização — têm oportunidade enorme num setor de alta fragmentação e baixa digitalização.",
    sections=[
        ("O Mercado de BeautyTech SaaS no Brasil",
         "O mercado de SaaS para beleza e estética é segmentado por tipo de estabelecimento: salões de beleza (corte, coloração, tratamentos capilares — o maior segmento em volume), barbearias (que cresceram exponencialmente com o movimento de barbearia premium), clínicas de estética (procedimentos estéticos não médicos — depilação a laser, limpeza de pele, drenagem linfática, tratamentos corporais), clínicas de estética médica (médicos ou sob responsabilidade médica — toxina botulínica, preenchimento, laser médico — mercado com complexidade regulatória adicional), e spas e espaços de bem-estar. O produto SaaS cobre: agenda online (cliente agenda pelo link do estabelecimento sem precisar ligar), gestão de clientes (histórico de serviços, preferências, aniversários — base para fidelização), financeiro (caixa, comissões de profissionais, relatórios), e programa de fidelidade (pontos, cashback, pacotes de serviços). O ticket médio varia de R$80 a R$600/mês dependendo do número de profissionais e dos módulos."),
        ("Agenda Online: O Módulo de Maior Impacto Imediato",
         "A agenda online é o módulo de maior impacto imediato para o estabelecimento de beleza: elimina o tempo gasto com ligações de agendamento (que pode consumir de 30 minutos a 2 horas por dia da recepcionista ou do próprio profissional), reduz o no-show (a confirmação automática por WhatsApp D-1 e D-3 reduz o no-show de 15-20% para menos de 5%), e aumenta o volume de agendamentos (o cliente agenda no domingo à noite quando lembrá de que precisa cortar o cabelo — não espera a segunda-feira para ligar). A integração da agenda com o Google Meu Negócio e o Instagram (botão 'agendar' direto no perfil) captura o cliente no momento da intenção de compra — sem fricção. Salões e barbearias que implementam agenda online reportam aumento de 20% a 40% no volume de agendamentos nos primeiros 3 meses — o que se reflete diretamente na receita."),
        ("Gestão de Comissões: A Dor Operacional do Salão",
         "O modelo de remuneração por comissão é universal no setor de beleza: o profissional recebe de 30% a 60% do valor dos serviços que realiza — com variações por tipo de serviço, por categoria do profissional e por acordo individual. A gestão manual de comissões — calcular manualmente quanto cada profissional deve receber com base nos serviços registrados — é trabalhosa, sujeita a erros e fonte frequente de conflito entre o dono e os profissionais. Um sistema de gestão que: registra cada serviço no momento do atendimento, calcula automaticamente a comissão de cada profissional com as regras configuradas, e gera o extrato de comissão transparente — elimina horas de trabalho manual e conflitos por falta de transparência. O dono de salão que não usa sistema de gestão frequentemente não sabe exatamente qual profissional é mais rentável, quais serviços têm maior margem, e onde estão os vazamentos de caixa."),
        ("Go-to-Market em BeautyTech SaaS",
         "O decisor em salão de beleza e barbearia é o próprio dono — frequentemente também o principal profissional. A decisão de compra é rápida quando a dor está clara (o dono reclamou do no-show há semanas), o demo é visual (mostrar o app do cliente agendando em tempo real conquista imediatamente), e o onboarding é assistido (o suporte que ajuda a importar os clientes e configurar a agenda no primeiro dia é determinante para a adoção). Os canais mais eficientes incluem: distribuidores de produtos de beleza (L'Oréal, Wella, Schwarzkopf — que têm representantes que visitam todos os salões da região), cursos e eventos do setor (Beauty Fair — a maior feira de beleza da América Latina — Expo Beauty Show), comunidades de donos de salão no Instagram e WhatsApp (o boca a boca entre donos de salão é o canal de maior conversão), e SEO para 'aplicativo para salão de beleza' e 'software para barbearia'."),
        ("Métricas de Saúde do BeautyTech SaaS",
         "As métricas de produto incluem: agendamentos realizados pela plataforma por mês (a métrica central de uso ativo — quanto maior o volume de agendamentos, maior o valor percebido e o switching cost), taxa de redução de no-show nos clientes que usam confirmação automática (indicador de impacto no negócio do cliente), e NPS do dono e dos profissionais. As métricas de negócio incluem: MRR por número de profissionais (o modelo per-cadeira ou per-profissional é o mais comum — R$20 a R$50/profissional/mês), churn (o setor de beleza tem abertura e fechamento frequente de estabelecimentos — churn bruto relevante, especialmente no SMB), expansão por módulos (dono que começa com agenda e adiciona financeiro, fidelidade e gestão de estoque de produtos), e CAC por canal (distribuidores de beleza têm CAC muito mais baixo do que inbound direto — pelo volume de estabelecimentos que visitam).")
    ],
    faq_list=[
        ("Sistema de gestão para salão de beleza é realmente necessário ou Excel resolve?",
         "Excel resolve até um determinado ponto — geralmente até o salão ter mais de 2 profissionais e mais de 50 clientes ativos. A partir daí, os problemas ficam visíveis: o controle de agendamentos por planilha não previne conflitos de horário entre profissionais, não envia confirmação automática por WhatsApp, e não gera relatório de serviços mais rentáveis sem trabalho manual. A gestão de comissões em Excel é trabalhosa e sujeita a erros que geram conflito com os profissionais. O histórico de serviços de cada cliente — que permite personalizar o atendimento ('a Maria sempre pede o mesmo corte') — não é facilmente acessível em planilha. O sistema de gestão que substitui o Excel permite que o dono foque no atendimento e na gestão estratégica em vez de na burocracia operacional. O custo de R$80 a R$300/mês se paga com 1 a 3 agendamentos adicionais por semana graças à agenda online — o que é facilmente alcançável."),
        ("Como funciona o programa de fidelidade em salão de beleza?",
         "Os programas de fidelidade em salão de beleza funcionam por acúmulo de pontos ou por pacotes de serviços. Acúmulo de pontos: cada serviço gera pontos que podem ser trocados por descontos ou serviços gratuitos (ex: a cada 10 cortes, o 11º é grátis). Pacotes de serviços: o cliente compra um pacote antecipado de serviços com desconto (ex: 5 sessões de depilação a laser com 20% de desconto — pagamento à vista). Os pacotes são excelentes para o fluxo de caixa do salão e para criar comprometimento do cliente — que já pagou e vai priorizar esse salão para usar o pacote. Programas de aniversário (desconto no mês do aniversário) e de indicação (desconto para quem indica um amigo) têm alto ROI e baixo custo de implementação. O sistema de gestão que automatiza essas comunicações — enviando mensagem de aniversário automaticamente no dia, alertando sobre pontos acumulados — torna o programa escalável sem depender de ação manual da recepcionista."),
        ("Qual a diferença entre estética e medicina estética no aspecto regulatório?",
         "A distinção é importante e tem implicações regulatórias: Estética não médica (ou simplesmente 'estética') são procedimentos realizados por esteticistas — profissionais com formação técnica ou superior em estética — que não envolvem invasão da pele, injeção de substâncias ou uso de equipamentos de alta energia: limpeza de pele, massagens, drenagem linfática, esfoliações, maquiagem. O SENAC e outras instituições formam esses profissionais. Medicina estética são procedimentos realizados exclusivamente por médicos ou sob responsabilidade médica: toxina botulínica (Botox), preenchimento com ácido hialurônico, laser de ablação, peelings químicos profundos, fios de sustentação. O CFM define quais procedimentos são atos médicos. Clínicas que anunciam 'aplicação de botox por esteticista' estão em irregularidade grave — com risco de interdição pela vigilância sanitária e processo no CRM. Plataformas SaaS para clínicas de estética médica devem incluir funcionalidades de prontuário médico e controle de materiais — que não são necessárias em salões de beleza.")
    ]
)

# Article 4732 — Clinic: Pediatrics and child health
art(
    slug="gestao-de-clinicas-de-pediatria-e-saude-infantil",
    title="Gestão de Clínicas de Pediatria e Saúde Infantil",
    desc="Guia de gestão para clínicas de pediatria: fluxo de atendimento, calendário de vacinas, desenvolvimento infantil, manejo de doenças agudas e indicadores de qualidade assistencial.",
    h1="Gestão de Clínicas de Pediatria e Saúde Infantil",
    lead="A pediatria é a especialidade médica que cuida da saúde de crianças e adolescentes — do recém-nascido até os 18 anos. Com mais de 60 milhões de crianças no Brasil, clínicas de pediatria têm altíssima demanda e alta fidelidade — a família que encontra um pediatra de confiança permanece por anos ou décadas.",
    sections=[
        ("O Escopo da Pediatria Clínica",
         "A pediatria clínica geral abrange: puericultura (consultas periódicas de saúde da criança desde o nascimento — vacinas, crescimento e desenvolvimento, orientação de alimentação e sono), manejo de doenças agudas (infecções respiratórias — o motivo mais frequente de consulta pediátrica, gastroenterites, otites, exantemas), manejo de doenças crônicas pediátricas (asma, rinite alérgica, dermatite atópica — o trio alérgico que afeta até 20% das crianças brasileiras), desenvolvimento neuropsicomotor (rastreamento de atrasos de linguagem, motor e cognitivo — encaminhamento precoce para terapias faz diferença significativa no prognóstico), e saúde do adolescente (puberdade, saúde mental adolescente, orientação sexual e reprodutiva). As subespecialidades pediátricas (neonatologia, cardiologia pediátrica, neurologia pediátrica, oncologia pediátrica) atendem casos de maior complexidade geralmente em ambiente hospitalar."),
        ("Puericultura: A Âncora da Relação com a Família",
         "A puericultura — consultas periódicas de saúde da criança nos primeiros anos de vida — é o produto de maior fidelização em pediatria. O calendário de puericultura da SBP (Sociedade Brasileira de Pediatria) recomenda consultas: ao nascimento, com 15 dias, 1, 2, 4, 6, 9, 12, 15, 18 e 24 meses — depois semestralmente até os 6 anos e anualmente até os 18 anos. Cada consulta de puericultura avalia: crescimento (peso, altura, PC — plotados nas curvas de crescimento da OMS), desenvolvimento neuropsicomotor (marcos de desenvolvimento por faixa etária), vacinas em dia (conferência do cartão de vacina), alimentação (introdução alimentar, aleitamento materno, prevenção de anemia), sono, e orientações de desenvolvimento. O pediatra que conduz a puericultura de forma completa e empática constrói a relação de maior confiança da família com o sistema de saúde — essa relação dura décadas."),
        ("Cartão de Vacinas: Gestão e Alertas",
         "O calendário vacinal brasileiro — o mais completo do mundo para imunizações no serviço público — inclui mais de 20 vacinas do nascimento aos 18 anos no SUS. Na rede privada, vacinas adicionais são oferecidas (meningocócica ACWY e B, varicela, HPV, febre tifoide, dengue). A gestão do calendário vacinal é uma das principais dores operacionais em pediatria: garantir que cada criança está com as vacinas em dia para a idade, alertar os pais quando uma vacina está vencida ou próxima do vencimento, e registrar as vacinas aplicadas no prontuário com lote e fabricante (rastreabilidade exigida pela vigilância sanitária). Sistemas de prontuário pediátrico que têm o calendário vacinal integrado — com alertas automáticos por WhatsApp para os pais — transformam a adesão vacinal da carteira de pacientes e são um diferencial de valor imenso para o pediatra que quer monitorar a saúde da criança de forma proativa."),
        ("Saúde Mental Infantil e Adolescente: Crescimento de Demanda",
         "A saúde mental de crianças e adolescentes é o segmento de maior crescimento em pediatria pós-pandemia: transtorno de ansiedade, depressão adolescente, TDAH (Transtorno do Déficit de Atenção e Hiperatividade), TEA (Transtorno do Espectro Autista) e transtornos alimentares em adolescentes cresceram significativamente na última década — e foram amplificados pelo uso excessivo de telas e pelo isolamento da pandemia. O pediatra geral atua no rastreamento (escalas de triagem como M-CHAT para autismo, Conners para TDAH, PHQ-A para depressão adolescente) e no encaminhamento precoce para neuropediatra, psiquiatra infantojuvenil e psicólogo. Clínicas de pediatria que têm psicólogo infantojuvenil integrado — ou parceria estruturada — capturam esse fluxo crescente de demanda sem perder o paciente para outra clínica."),
        ("Indicadores de Qualidade em Pediatria",
         "As métricas clínicas incluem: cobertura vacinal da carteira de pacientes (percentual de crianças com vacinas em dia para a idade — meta acima de 95%), taxa de acompanhamento regular de puericultura (crianças que comparecem às consultas programadas vs. esperadas — indicador de retenção e proatividade da clínica), taxa de crescimento adequado nos pacientes acompanhados (indicador de efetividade do cuidado longitudinal), e NPS dos pais. As métricas de negócio incluem: receita por paciente por ano (criança em puericultura tem de 6 a 12 consultas por ano — alta frequência), taxa de permanência da família na clínica até a adolescência (LTV de uma família que começa na puericultura e acompanha até os 18 anos é enorme — de 15 a 20 anos de atendimento), e taxa de irmãos atendidos (a família satisfeita traz o segundo filho e recomenda para outras famílias — indicador de satisfação e NPS operacional).")
    ],
    faq_list=[
        ("Com que frequência devo levar meu filho ao pediatra?",
         "O calendário de puericultura recomendado pela SBP (Sociedade Brasileira de Pediatria) inclui: consultas mais frequentes no primeiro ano de vida (ao nascimento, 15 dias, 1, 2, 4, 6, 9 e 12 meses — 8 consultas no primeiro ano), menos frequentes no segundo e terceiro anos (15, 18, 24 meses, 3 anos), semestral dos 3 aos 6 anos, e anual dos 6 aos 18 anos. Além dessas consultas de rotina, consultas de doença aguda (febre, tosse, otite, gastroenterite) ocorrem de forma não programada — a frequência depende da saúde da criança. Crianças com condições crônicas (asma, alergias severas, TDAH, TEA) têm retornos mais frequentes conforme o plano de acompanhamento. A mensagem principal: as consultas de puericultura não são opcionais — mesmo a criança saudável precisa de acompanhamento regular para garantir que o crescimento e o desenvolvimento estão dentro do esperado."),
        ("Como saber se meu filho tem TDAH?",
         "O diagnóstico de TDAH (Transtorno do Déficit de Atenção e Hiperatividade) é clínico — não existe exame de sangue ou imagem que confirme o diagnóstico. É feito por neuropediatra ou psiquiatra infantojuvenil com base em: história clínica detalhada (sintomas de desatenção, hiperatividade e impulsividade presentes há mais de 6 meses, em mais de um contexto — escola e casa), avaliação do desenvolvimento, escalas comportamentais preenchidas pelos pais e professores (Conners, SNAP-IV), e exclusão de outras condições que podem mimetizar o TDAH (privação de sono, ansiedade, deficiência de ferro, problemas visuais ou auditivos). O pediatra geral realiza o rastreamento inicial — e encaminha para o especialista quando há suspeita. O tratamento combina intervenção comportamental (psicoterapia, orientação escolar) e quando necessário medicação (metilfenidato — Ritalina, Concerta — ou outros). TDAH tratado corretamente não prejudica o desenvolvimento acadêmico ou social."),
        ("O que é TEA (Transtorno do Espectro Autista) e quando suspeitar?",
         "TEA (Transtorno do Espectro Autista) é um transtorno do neurodesenvolvimento caracterizado por dificuldades na comunicação e interação social e por padrões restritos e repetitivos de comportamento. Os sinais de alerta que devem motivar avaliação especializada incluem: ausência de sorriso social ao 2 meses, não balbuciar ou apontar ao 12 meses, não falar palavras ao 16 meses, não fazer frases de 2 palavras ao 24 meses, e qualquer regressão no desenvolvimento (perda de habilidades já adquiridas — como falar ou interagir). O M-CHAT (Modified Checklist for Autism in Toddlers) é aplicado na puericultura dos 18-24 meses como rastreamento. O diagnóstico definitivo é feito por neuropediatra ou equipe multidisciplinar especializada. A intervenção precoce — iniciada antes dos 3 anos quando o cérebro tem maior plasticidade — é o fator com maior impacto no prognóstico funcional da criança com TEA.")
    ]
)

# Article 4733 — SaaS sales: Pharmacies and drugstores
art(
    slug="vendas-para-o-setor-de-saas-de-farmacias-e-drogarias",
    title="Vendas para o Setor de SaaS de Farmácias e Drogarias",
    desc="Estratégias de vendas B2B para plataformas SaaS de farmácias e drogarias: como abordar proprietários e redes de farmácias para fechar contratos de PDV, estoque e conformidade SNGPC.",
    h1="Vendas para o Setor de SaaS de Farmácias e Drogarias",
    lead="O Brasil tem mais de 90 mil farmácias e drogarias, com faturamento superior a R$250 bilhões por ano. Plataformas SaaS para farmácias cobrem PDV, gestão de estoque, SNGPC (controle de medicamentos controlados) e integração com operadoras de saúde — um mercado de alta regulação e alta recorrência.",
    sections=[
        ("O Mercado de PharmaTech SaaS",
         "O mercado de SaaS para farmácias é dividido por porte: farmácias independentes de bairro (o maior segmento em número — proprietário individual ou família, faturamento de R$50 mil a R$500 mil/mês), redes regionais de farmácias (de 5 a 50 unidades — com gestão centralizada de estoque e compras), e grandes redes nacionais (Raia Drogasil, Pacheco, Pague Menos — com sistemas próprios ou ERPs enterprise). O produto SaaS para farmácias cobre: PDV (frente de caixa — venda de medicamentos, produtos de higiene e cosméticos), gestão de estoque (curva ABC de medicamentos, ponto de pedido, rastreabilidade de lote e validade), SNGPC (Sistema Nacional de Gerenciamento de Produtos Controlados — obrigação legal de notificação de vendas de medicamentos controlados à ANVISA), integração com convênios e planos de saúde (processamento de receitas, cashback de planos, cartão de benefícios como FarmaBem e Farmácias Populares), e gestão financeira. O ticket médio varia de R$200 a R$800/mês para farmácias independentes."),
        ("SNGPC: A Obrigação Regulatória que Gera Demanda",
         "O SNGPC (Sistema Nacional de Gerenciamento de Produtos Controlados) é a principal obrigação regulatória que impulsiona a adoção de software em farmácias: toda farmácia que vende medicamentos sujeitos a controle especial (tarja preta, tarja vermelha com retenção de receita, antimicrobianos) deve notificar eletronicamente cada venda à ANVISA em tempo real. O software de farmácia deve: integrar com o SNGPC da ANVISA (envio automático das vendas de controlados), controlar o saldo de cada medicamento controlado (o SNGPC confronta o estoque declarado com as entradas e saídas), e manter o registro de receitas retidas (prazo mínimo de 3 anos). Farmácias que operam sem sistema integrado ao SNGPC ou que têm inconsistências no envio estão sujeitas a multas e interdição da ANVISA — a conformidade regulatória é argumento de venda não negociável para o farmacêutico."),
        ("Integração com Convênios e Planos de Saúde",
         "A farmácia moderna é um ponto de dispensação de medicamentos para pacientes com planos de saúde — e essa integração exige infraestrutura tecnológica específica: integração com a plataforma do plano de saúde para verificar elegibilidade do paciente, processar a receita coberta pelo plano, e calcular a coparticipação do paciente. Programas como Farmácia Popular (subsidiado pelo governo federal) e programas de cashback das redes (como o Programa Viva da Raia Drogasil) também exigem integração de sistema. Farmácias que não têm integração com os principais planos perdem receita — pacientes que querem usar o benefício do plano vão à farmácia concorrente que tem o sistema integrado. O software que tem o maior número de integrações com operadoras e planos tem vantagem competitiva clara no mercado de farmácias."),
        ("Gestão de Estoque Farmacêutico: Especificidades e Riscos",
         "O estoque de farmácia tem especificidades críticas que diferenciam o WMS farmacêutico do estoque de varejo genérico: controle de validade (medicamentos vencidos devem ser recolhidos — e a exposição ao público de medicamento vencido é infração sanitária grave), rastreabilidade de lote (para recall — quando um lote de medicamento é recolhido pelo fabricante, a farmácia precisa saber se tem aquele lote em estoque), controle de temperatura (medicamentos que exigem refrigeração — como insulinas, algumas vacinas — devem ter registro de temperatura do armazém), e controle FEFO (First Expired, First Out — medicamentos que vencem antes devem sair primeiro, diferente do varejo que usa FIFO). Plataformas farmacêuticas que controlam automaticamente a validade e emitem alerta antes do vencimento reduzem as perdas por vencimento — que podem representar 1% a 3% do faturamento em farmácias sem controle adequado."),
        ("Métricas de Saúde do PharmaTech SaaS",
         "As métricas de produto incluem: transações de PDV processadas por mês (volume que cresce com o faturamento da farmácia), notificações SNGPC enviadas sem erro (indicador de conformidade regulatória — a farmácia que não tem falha de SNGPC não troca de sistema facilmente), e NPS do farmacêutico e do operador de caixa. As métricas de negócio incluem: MRR por farmácia (R$200 a R$800/mês para independentes — com expansão por módulos), churn por fechamento de farmácia ou aquisição por grande rede (que tem sistema próprio), NRR via redes regionais (farmácia que abre segunda unidade dobra o ticket), e CAC por canal — distribuidores farmacêuticos (EMS, Hypera, Eurofarma têm representantes que visitam farmácias diariamente) e sindicatos de farmácias (SindiFarma por estado) são os canais de maior confiança do setor.")
    ],
    faq_list=[
        ("O que é SNGPC e por que é obrigatório para farmácias?",
         "SNGPC (Sistema Nacional de Gerenciamento de Produtos Controlados) é o sistema da ANVISA para monitorar a dispensação de medicamentos sujeitos a controle especial em todo o Brasil. É obrigatório para todas as farmácias e drogarias que comercializam medicamentos de tarja preta (psicotrópicos, entorpecentes, anorexígenos), tarja vermelha com retenção de receita (vários antibióticos, corticosteroides sistêmicos em formulações específicas), e antimicrobianos. A farmácia deve informar ao SNGPC, em tempo real: o medicamento vendido (nome, princípio ativo, concentração, forma farmacêutica), a quantidade dispensada, o número do lote, e os dados do comprador e da receita. A ANVISA usa esses dados para monitorar o consumo nacional de medicamentos controlados e identificar irregularidades. Farmácias que não enviam ou que enviam com inconsistências estão sujeitas à Resolução RDC 20/2011 — que prevê multas e interdição."),
        ("Como funciona a precificação de medicamentos no Brasil?",
         "O preço dos medicamentos no Brasil é regulado pela CMED (Câmara de Regulação do Mercado de Medicamentos), órgão interministerial vinculado à ANVISA. Cada medicamento tem um preço máximo ao consumidor (PMC) definido pela CMED — a farmácia não pode cobrar mais do que o PMC. O preço de fábrica (PF) é o preço máximo cobrado pelo fabricante à distribuidora. A farmácia compra com base no PF e vende até o PMC — a margem depende do desconto obtido do distribuidor e do preço praticado (sempre abaixo do PMC). O Sistema de Controle de Preços da CMED publica a tabela de PMC mensalmente — e o software de farmácia deve estar atualizado com essa tabela para evitar cobrar acima do máximo legal. Medicamentos genéricos têm PMC obrigatoriamente mais baixo do que o referência (originador) — o que torna a indicação de genéricos uma obrigação ética e uma oportunidade comercial para a farmácia."),
        ("Farmácia pode vender pela internet?",
         "Sim — a farmácia pode vender pela internet mediante autorização sanitária específica. A RDC ANVISA 44/2009 e a Resolução 20/2011 regulamentam o comércio eletrônico de medicamentos: a farmácia online deve ter CNPJ como farmácia física (não pode operar apenas online), Alvará Sanitário, farmacêutico responsável técnico, e autorização específica para comércio eletrônico emitida pela vigilância sanitária estadual. Medicamentos controlados não podem ser vendidos pela internet — apenas os de venda livre (MIPs — Medicamentos Isentos de Prescrição) e os de tarja vermelha sem retenção de receita mediante apresentação da receita digital ou digitalizada. Redes como Droga Raia, Pacheco e Ultrafarma têm operações online robustas. Para farmácias independentes, plataformas como iFood Farma e Mercado Livre Farmácias permitem vender online sem construir a própria plataforma digital — o software de gestão farmacêutica deve integrar com essas plataformas para sincronizar o estoque e os pedidos.")
    ]
)

# Article 4734 — Consulting: Strategic planning and OKRs
art(
    slug="consultoria-de-planejamento-estrategico-e-okrs",
    title="Consultoria de Planejamento Estratégico e OKRs",
    desc="Como funciona a consultoria de planejamento estratégico e OKRs: metodologias de estratégia, implementação de OKRs, alinhamento organizacional e métricas de execução estratégica.",
    h1="Consultoria de Planejamento Estratégico e OKRs",
    lead="Estratégia sem execução é apenas intenção. Consultoria de planejamento estratégico e OKRs ajuda empresas a traduzir a visão de longo prazo em metas trimestrais mensuráveis, alinhar todos os níveis da organização em torno das prioridades, e criar a cadência de revisão que mantém a execução no rumo certo.",
    sections=[
        ("O que é Consultoria de Planejamento Estratégico",
         "A consultoria de planejamento estratégico conduz o processo de definição da direção de longo prazo da empresa: análise de ambiente externo (PESTEL, forças de Porter, mapeamento de tendências do setor), análise interna (SWOT, cadeia de valor, competências essenciais), definição de visão e missão com propósito claro, formulação de estratégia (onde competir, como ganhar, quais capacidades desenvolver), e tradução da estratégia em metas e iniciativas. O processo típico dura de 2 a 4 meses e envolve a alta liderança em workshops de construção coletiva — o envolvimento da liderança na construção aumenta drasticamente a adesão na execução. O entregável central é um plano estratégico de 3 a 5 anos com metas de resultado de negócio e iniciativas estratégicas priorizadas — mas o maior valor da consultoria é o processo de alinhamento da liderança, não apenas o documento produzido."),
        ("OKRs: Objetivos e Resultados-Chave",
         "OKRs (Objectives and Key Results) é o sistema de gestão de metas popularizado pelo Google (que o adotou em 1999 com base no trabalho de Andy Grove na Intel). A estrutura é simples: Objetivo é uma declaração qualitativa inspiradora de onde queremos chegar ('Ser a referência em atendimento ao cliente do setor'); Key Results são as métricas quantitativas que provam que atingimos o objetivo (NPS acima de 70, tempo de resposta ao cliente abaixo de 2 horas, taxa de resolução no primeiro contato acima de 85%). Cada nível da organização define seus próprios OKRs, alinhados verticalmente com os OKRs da empresa. O ciclo trimestral cria urgência e aprendizado rápido — o que não funcionou em um trimestre é corrigido no próximo. A consultoria de OKR ajuda a definir OKRs de qualidade, a implantar o processo de revisão semanal e trimestral, e a criar a disciplina de execução."),
        ("BSC vs. OKR: Quando Usar Cada Abordagem",
         "BSC (Balanced Scorecard — Kaplan e Norton) e OKR são as duas metodologias de gestão de metas mais usadas no mundo — e servem a propósitos distintos. BSC é mais adequado para organizações maduras e estáveis que precisam de um mapa estratégico que conecte causa e efeito entre as perspectivas (financeiro, cliente, processos internos, aprendizado e crescimento) — é mais completo como framework de comunicação da estratégia, mas mais lento para implantar e mais rígido. OKR é mais adequado para empresas de crescimento acelerado (startups, scale-ups, empresas em transformação) que precisam de foco, velocidade e adaptabilidade — ciclos trimestrais permitem pivotar rapidamente. A tendência do mercado é usar os dois de forma complementar: o BSC para o planejamento estratégico anual e o mapa de causa-efeito, e o OKR para a execução trimestral ágil. Consultorias que só conhecem uma das metodologias recomendam aquela que conhecem — independentemente do contexto do cliente."),
        ("Armadilhas na Implementação de OKRs",
         "As armadilhas mais comuns na implementação de OKRs incluem: OKRs como lista de tarefas (KR é 'fazer reunião mensal com clientes' em vez de 'NPS acima de 70' — o KR deve ser uma métrica de resultado, não uma atividade), muitos OKRs (mais de 3 objetivos e 3-5 KRs por objetivo dilui o foco — 'se tudo é prioridade, nada é prioridade'), OKRs definidos apenas pela liderança sem envolvimento das equipes (OKR imposto de cima gera conformidade sem comprometimento — o OKR deve ter componente bottom-up), vinculação direta a bônus e avaliação (quando o OKR vira instrumento de avaliação individual, as pessoas definem OKRs conservadores para garantir o bônus — a Google recomenda separar OKRs de gestão de desempenho), e falta de cadência de revisão (OKR sem check-in semanal ou quinzenal vira documento de gaveta — a revisão regular é o coração do sistema). A consultoria que previne essas armadilhas entrega muito mais valor do que a que apenas conduz o workshop de definição."),
        ("Alinhamento Organizacional: Do Topo à Base",
         "O maior desafio de execução estratégica não é a definição da estratégia — é o alinhamento: garantir que todos os níveis da organização entendem as prioridades e estão trabalhando coerentemente na mesma direção. Pesquisas do Balanced Scorecard Institute mostram que apenas 5% dos colaboradores conhecem ou entendem a estratégia de sua empresa, e apenas 25% dos líderes têm incentivos vinculados à estratégia. Os mecanismos de alinhamento incluem: cascateamento de OKRs (OKRs da empresa → OKRs de departamento → OKRs de equipe — com alinhamento vertical explícito), reuniões de cadência estratégica (weekly check-in de OKRs, retrospectiva trimestral, planning do próximo trimestre), comunicação da estratégia de forma acessível a todos os níveis (não apenas para o board e para a C-suite), e alinhamento dos sistemas de incentivo com as prioridades estratégicas (quem é reconhecido e promovido com base em que critérios?).")
    ],
    faq_list=[
        ("OKR funciona para pequenas empresas?",
         "Sim — e muitas vezes com mais impacto do que em grandes empresas, onde a burocracia pode diluir o efeito. Pequenas empresas (de 5 a 50 pessoas) se beneficiam do OKR principalmente porque: obriga a escolher poucas prioridades (uma PME com recursos limitados não pode fazer tudo — o OKR força o foco), cria alinhamento rápido (com 10 pessoas, um OKR trimestral bem definido em um workshop de 2 horas alinha toda a equipe), e gera visibilidade de progresso (o check-in semanal de 15 minutos mantém todos informados sobre como está a execução). A simplificação é a chave em PMEs: não use múltiplas camadas de cascateamento, não implemente ferramentas caras de OKR (uma planilha compartilhada funciona bem para empresas menores), e foque em 2 a 3 objetivos da empresa com KRs claros e mensuráveis. A disciplina de revisar semanalmente é mais importante do que a sofisticação do framework."),
        ("Qual a diferença entre meta SMART e OKR?",
         "Meta SMART (Specific, Measurable, Achievable, Relevant, Time-bound) e OKR têm sobreposição mas diferenças importantes. Meta SMART é um critério de qualidade para qualquer meta — define que uma boa meta deve ser específica, mensurável, alcançável, relevante e com prazo. OKR é um sistema completo com estrutura específica (Objetivo qualitativo + Key Results quantitativos), filosofia (OKRs devem ser ambiciosos — atingir 70% de um OKR stretch é sucesso, não falha), cadência (trimestral com check-ins semanais), e mecanismo de alinhamento (cascateamento e OKRs compartilhados entre equipes interdependentes). A principal diferença filosófica é a da ambição: a meta SMART pela definição deve ser 'Achievable' (alcançável) — o que incentiva metas conservadoras. O OKR é deliberadamente desafiador — atingir 100% de um OKR significa que ele não era ambicioso o suficiente (segundo Larry Page do Google)."),
        ("Com que frequência deve-se revisar o planejamento estratégico?",
         "O planejamento estratégico de longo prazo (3 a 5 anos) deve ser revisado anualmente — para incorporar mudanças do ambiente externo, aprendizados da execução e novos dados de mercado. Revisões mais frequentes do plano de longo prazo são ineficientes — a estratégia precisa de consistência para ser executada. O plano anual e as metas de curto prazo devem ser revisados com maior frequência: semestralmente para o plano anual, e trimestralmente para os OKRs ou metas trimestrais. Em empresas de crescimento acelerado ou em setores muito dinâmicos (tecnologia, serviços financeiros), o ciclo estratégico pode ser encurtado — revisão trimestral do horizonte de 12 meses com manutenção da visão de 3 a 5 anos. A pandemia de COVID-19 forçou muitas empresas a comprimir o ciclo de revisão estratégica para mensal — o que é insustentável no longo prazo mas útil em períodos de alta turbulência.")
    ]
)

# ── Sitemap & trilha update ──────────────────────────────────────────────────
sitemap_path = pathlib.Path(__file__).parent / "sitemap.xml"
trilha_path  = pathlib.Path(__file__).parent / "trilha.html"

new_slugs = [
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-transportadoras-e-gestao-de-frete",
     "Gestão de Negócios de Empresa de B2B SaaS de Transportadoras e Gestão de Frete"),
    ("gestao-de-clinicas-de-urologia-e-saude-do-homem",
     "Gestão de Clínicas de Urologia e Saúde do Homem"),
    ("vendas-para-o-setor-de-saas-de-educacao-corporativa-e-elearning",
     "Vendas para o Setor de SaaS de Educação Corporativa e E-learning"),
    ("consultoria-de-gestao-de-operacoes-e-lean-manufacturing",
     "Consultoria de Gestão de Operações e Lean Manufacturing"),
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-clinicas-de-estetica-e-beleza",
     "Gestão de Negócios de Empresa de B2B SaaS de Clínicas de Estética e Beleza"),
    ("gestao-de-clinicas-de-pediatria-e-saude-infantil",
     "Gestão de Clínicas de Pediatria e Saúde Infantil"),
    ("vendas-para-o-setor-de-saas-de-farmacias-e-drogarias",
     "Vendas para o Setor de SaaS de Farmácias e Drogarias"),
    ("consultoria-de-planejamento-estrategico-e-okrs",
     "Consultoria de Planejamento Estratégico e OKRs"),
]

sm = sitemap_path.read_text(encoding="utf-8")
new_urls = "".join(
    f"  <url><loc>https://produtovivo.com.br/blog/{s}/</loc></url>\n"
    for s, _ in new_slugs
)
sitemap_path.write_text(sm.replace("</urlset>", new_urls + "</urlset>"), encoding="utf-8")

tr = trilha_path.read_text(encoding="utf-8")
new_items = "".join(
    f'  <li><a href="/blog/{s}/">{t}</a></li>\n'
    for s, t in new_slugs
)
trilha_path.write_text(tr.replace("</ul>", new_items + "\n</ul>", 1), encoding="utf-8")

print("Done — batch 1622")
