import os, json, pathlib

BASE   = os.path.join(os.path.dirname(__file__), "blog")
DOMAIN = "https://produtovivo.com.br"
PIXEL  = "4520253334926563"

TMPL = """<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{url}">
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){{if(f.fbq)return;n=f.fbq=function(){{n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)}};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init','{pixel}');fbq('track','PageView');
</script>
<style>
body{{font-family:sans-serif;margin:0;padding:0;color:#222}}
header{{background:#0a7c4e;padding:16px 24px}}
header a{{color:#fff;text-decoration:none;font-size:1.3rem;font-weight:700}}
main{{max-width:860px;margin:40px auto;padding:0 20px}}
h1{{font-size:2rem;color:#0a7c4e}}
h2{{font-size:1.3rem;color:#065f3a;margin-top:32px}}
p{{line-height:1.7}}
.lead{{font-size:1.1rem;color:#444}}
.faq{{background:#f4faf7;border-left:4px solid #0a7c4e;padding:20px 24px;margin-top:40px}}
.faq h2{{margin-top:0}}
.faq-item{{margin-bottom:20px}}
.faq-item h3{{margin-bottom:4px;color:#065f3a}}
footer{{text-align:center;padding:32px;color:#777;font-size:.9rem;margin-top:60px}}
</style>
<script type="application/ld+json">{schema}</script>
</head>
<body>
<header><a href="/">ProdutoVivo</a></header>
<main>
<h1>{h1}</h1>
<p class="lead">{lead}</p>
{body}
<div class="faq">
<h2>Perguntas Frequentes</h2>
{faqs}
</div>
</main>
<footer>© 2025 ProdutoVivo · Conteúdo informativo sobre gestão e tecnologia</footer>
</body>
</html>"""

def art(slug, title, desc, h1, lead, sections, faq_list):
    url = f"{DOMAIN}/blog/{slug}/"
    body_html = ""
    for sec_title, sec_body in sections:
        body_html += f"<h2>{sec_title}</h2>\n<p>{sec_body}</p>\n"
    faqs_html = ""
    schema_faqs = []
    for q, a in faq_list:
        faqs_html += f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>\n'
        schema_faqs.append({"@type": "Question", "name": q,
                             "acceptedAnswer": {"@type": "Answer", "text": a}})
    schema = json.dumps({"@context": "https://schema.org", "@type": "FAQPage",
                         "mainEntity": schema_faqs}, ensure_ascii=False)
    html = TMPL.format(title=title, desc=desc, url=url, pixel=PIXEL,
                       h1=h1, lead=lead, body=body_html, faqs=faqs_html, schema=schema)
    out_dir = os.path.join(BASE, slug)
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

# Article 4719 — B2B SaaS: E-commerce and marketplace management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-ecommerce-e-marketplace",
    title="Gestão de Negócios de Empresa de B2B SaaS de E-commerce e Marketplace",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para e-commerce e marketplace: modelo de negócio, plataformas, integrações, go-to-market e métricas do comércio digital.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de E-commerce e Marketplace",
    lead="O e-commerce brasileiro faturou R$185 bilhões em 2024, com mais de 90 milhões de compradores online. Plataformas SaaS que habilitam lojas virtuais, gerenciam estoques multichannel e integram marketplaces dominam a infraestrutura do comércio digital nacional — um mercado de altíssimo crescimento e rápida evolução tecnológica.",
    sections=[
        ("O Ecossistema de E-commerce SaaS",
         "O mercado de SaaS para e-commerce é estruturado em camadas: plataformas de loja virtual (Shopify, VTEX, Nuvemshop, Tray — onde o lojista monta e gerencia a loja), integradores de marketplace (Bling, Tiny, Omnichannel.io — que sincronizam estoque e pedidos entre a loja e os marketplaces como Mercado Livre, Shopee, Americanas, Magalu), ERPs de e-commerce (gestão financeira, estoque, emissão de NF-e, expedição), plataformas de fulfillment (gestão de armazém e expedição — WMS para e-commerce, incluindo a logística de devolução), ferramentas de marketing digital para e-commerce (e-mail marketing, recuperação de carrinho abandonado, push notification, CRM de clientes), e plataformas de analytics de e-commerce (análise de funil de conversão, atribuição de canais, análise de margem por produto e canal). O lojista digital médio usa de 5 a 12 ferramentas SaaS — criando um ecossistema altamente fragmentado com oportunidade de consolidação."),
        ("Integrações com Marketplace: O Produto de Maior Demanda",
         "Vender em múltiplos marketplaces simultaneamente (Mercado Livre, Shopee, Amazon, Americanas, Magalu, Casas Bahia, Carrefour) é a estratégia de crescimento dominante do e-commerce brasileiro médio. O problema: cada marketplace tem seu próprio sistema de cadastro de produtos, gestão de pedidos, estoque e comunicação com o comprador. Atualizar manualmente o estoque em 6 marketplaces e gerenciar os pedidos em 6 plataformas diferentes é inviável acima de 50 pedidos por dia. Integradores de marketplace resolvem isso: centralizam o catálogo, sincronizam o estoque em tempo real (uma venda no Mercado Livre debita o estoque de todos os canais imediatamente), centralizam os pedidos em um único painel, e automatizam a emissão de NF-e e a comunicação de rastreio. O integrador que não atualiza o estoque em tempo real gera overselling — que resulta em cancelamentos, punições do marketplace e perda de reputação."),
        ("VTEX e Shopify: Os Dois Extremos do Mercado",
         "O mercado de plataformas de e-commerce brasileiro é polarizado: VTEX domina o enterprise (Ambev, Carrefour, Motorola, Decathlon — com contratos de R$50 mil a R$500 mil/ano, implementação de 3 a 12 meses, equipe de desenvolvimento dedicada) e Shopify e Nuvemshop dominam o SMB (lojistas com faturamento de R$10 mil a R$5 milhões/mês — com custo de entrada de R$100 a R$2.000/mês e auto-implementação em dias). O gap entre os dois extremos — plataformas para mid-market com faturamento de R$5 a R$50 milhões/mês — é o espaço de maior oportunidade e disputa: VTEX tem custo alto demais, Shopify tem limitações para operações complexas (multimarca, B2B, customização de checkout). Plataformas como Vnda, Wake Commerce e Linx Commerce atendem esse segmento."),
        ("Logística e Fulfillment: O Gargalo do E-commerce",
         "A logística é o maior gargalo operacional do e-commerce: o prazo e o custo de entrega são os principais fatores de conversão e de avaliação do lojista pelo comprador. Plataformas de gestão de fulfillment (WMS para e-commerce) automatizam: recebimento de mercadoria no armazém, armazenagem com picking otimizado, separação e conferência do pedido, emissão de etiqueta de transportadora, e gestão de devoluções (logística reversa). O fulfillment terceirizado (3PL — Third Party Logistics) é a alternativa ao armazém próprio: o lojista manda o estoque para um 3PL (como Mandaê, Olist Store, Mercado Envios Full, Amazon FBA) que realiza toda a operação de armazém e entrega. Plataformas SaaS que integram nativamente com os principais 3PLs e transportadoras têm vantagem competitiva em um mercado onde a logística é frequentemente o motivo de churn."),
        ("Métricas de Saúde do E-commerce SaaS",
         "As métricas de produto incluem: GMV (Gross Merchandise Value) gerenciado pela plataforma — a métrica de escala do e-commerce SaaS, que cresce com o volume de vendas do cliente, pedidos processados por mês, e NPS do lojista. As métricas de negócio incluem: MRR com componente de take rate sobre GMV (muitas plataformas combinam mensalidade fixa com % do GMV — alinhando o sucesso da plataforma com o sucesso do cliente), churn por sazonalidade (lojistas que abriram no Natal e fecham depois — churn sazonal relevante no SMB), NRR (lojistas que crescem em GMV pagam mais via take rate — NRR acima de 120% é possível nesse modelo), e CAC (parcerias com agências de e-commerce e integradores contábeis têm CAC baixo — o lojista confia na indicação do parceiro que já gerencia o negócio).")
    ],
    faq_list=[
        ("VTEX ou Shopify: qual plataforma escolher para minha loja?",
         "A escolha depende do estágio e da complexidade da operação. Shopify é ideal para quem está começando ou tem operação relativamente simples: catálogo de até alguns milhares de produtos, operação monomarca, sem necessidade de customização profunda de checkout ou de regras fiscais complexas. O custo de entrada é baixo e a auto-implementação é possível. VTEX é indicada para operações mais complexas: multimarca, B2B e B2C no mesmo ambiente, customização de checkout, integração com ERP legado, operações com regras fiscais específicas (substituição tributária, DIFAL). Plataformas nacionais como Nuvemshop e Tray oferecem o melhor custo-benefício para o mid-market brasileiro — com suporte em português, integrações com transportadoras e marketplaces nacionais, e preço mais acessível que Shopify para volumes médios."),
        ("O que é taxa de conversão em e-commerce e como melhorá-la?",
         "Taxa de conversão é o percentual de visitantes da loja que efetivamente realizam uma compra. A média do e-commerce brasileiro gira entre 1% e 3% — o que significa que 97 a 99% dos visitantes saem sem comprar. As principais alavancas para aumentar a conversão incluem: velocidade de carregamento da página (cada segundo a mais reduz a conversão em 7% — PageSpeed acima de 80 é obrigatório), qualidade das fotos e descrições de produto (o comprador não pode tocar o produto — a foto substitui a experiência física), clareza no frete e prazo de entrega (mostrar o frete já na página do produto reduz a taxa de abandono de carrinho), checkout simplificado (menos campos, menos etapas, pagamento por Pix com um clique), e prova social (avaliações e fotos de clientes reais aumentam a confiança). Ferramentas de heatmap (Hotjar, Microsoft Clarity) e testes A/B (VWO, Optimizely) permitem identificar onde os compradores abandonam e validar melhorias."),
        ("Como funciona o modelo de marketplace e quando vale criar o próprio?",
         "Um marketplace é uma plataforma onde múltiplos vendedores independentes oferecem produtos ao comprador final — a plataforma não tem estoque próprio, cobra comissão (take rate) sobre as vendas realizadas. Exemplos: Mercado Livre, Shopee, Amazon, Elo7 (artesanato), GetNinjas (serviços). Criar um marketplace próprio faz sentido quando: a empresa tem base de clientes compradores (demand side) e quer expandir o catálogo sem comprar estoque, ou quando a empresa tem base de vendedores (supply side) e quer conectá-los aos compradores. Os desafios de criar um marketplace são o problema do galinheiro (precisa de compradores para atrair vendedores e vice-versa), a gestão de qualidade dos vendedores (reputação do marketplace depende da qualidade de todos os sellers), e a complexidade operacional (conciliação de pagamentos com múltiplos sellers, gestão de devoluções multi-seller, tributação específica de marketplace).")
    ]
)

# Article 4720 — Clinic: Neurology and headache management
art(
    slug="gestao-de-clinicas-de-neurologia-e-cefaleia",
    title="Gestão de Clínicas de Neurologia e Cefaleia",
    desc="Guia de gestão para clínicas de neurologia e cefaleia: fluxo de atendimento, exames diagnósticos, manejo de enxaqueca e epilepsia, e indicadores de qualidade clínica.",
    h1="Gestão de Clínicas de Neurologia e Cefaleia",
    lead="A neurologia é uma especialidade de altíssima demanda e baixa oferta no Brasil — o país tem apenas 1 neurologista para cada 20.000 habitantes. Clínicas de neurologia com serviço de cefaleia especializado atendem uma epidemia silenciosa: a enxaqueca afeta 15% da população brasileira, sendo a principal causa de incapacidade em adultos jovens.",
    sections=[
        ("O Escopo da Neurologia Clínica",
         "A neurologia clínica abrange condições altamente prevalentes e de alto impacto funcional: cefaleias primárias (enxaqueca, cefaleia tensional, cefaleia em salvas — as mais prevalentes e subdiagnosticadas), epilepsia (diagnóstico e ajuste de medicação antiepiléptica, monitoramento de crises), doenças neurodegenerativas (Alzheimer, Parkinson, esclerose lateral amiotrófica — doenças de alta cronicidade e impacto familiar), doenças cerebrovasculares (AVC isquêmico e hemorrágico — avaliação de sequelas e prevenção de recidiva), doenças desmielinizantes (esclerose múltipla — diagnóstico, tratamento com imunomoduladores, monitoramento de recaídas), e neuropatias periféricas (diabetes, alcoolismo, neuropatia inflamatória — diagnóstico eletroneuromiográfico). A cefaleia — em especial a enxaqueca — é o subespecialidade de maior volume ambulatorial e de maior impacto econômico na produtividade."),
        ("Centro de Cefaleia: Modelo de Alta Especialização",
         "Centros especializados em cefaleia oferecem abordagem multidisciplinar que vai além da consulta neurológica isolada: neurologista com subespecialidade em cefaleia (membro da SBCe — Sociedade Brasileira de Cefaleia), psicólogo para abordagem cognitivo-comportamental da dor (fundamental para enxaqueca crônica), fisioterapeuta especializado em cefaleia cervicogênica e disfunção temporomandibular, e nutricionista para identificação de gatilhos alimentares. O tratamento da enxaqueca crônica (mais de 15 dias de dor por mês) com anticorpos anti-CGRP (erenumabe, fremanezumabe, galcanezumabe — aprovados pela ANVISA) exige acompanhamento neurologista especializado e documentação detalhada para autorização pelos planos de saúde. A aplicação de toxina botulínica para profilaxia de enxaqueca crônica é outro procedimento de alto valor realizado por centros especializados."),
        ("Eletroneuromiografia e Exames Diagnósticos em Neurologia",
         "A eletroneuromiografia (ENMG) é o principal exame diagnóstico de neurologia ambulatorial: avalia a condução nervosa (velocidade e amplitude — identifica neuropatias, síndrome do túnel do carpo, radiculopatias) e a atividade elétrica muscular (EMG de agulha — diferencia neuropatia de miopatia). Clínicas de neurologia que têm eletroneuromiografia própria aumentam significativamente o ticket por paciente e a conveniência (o paciente faz a consulta e o exame no mesmo local, com laudo imediato). Outros exames relevantes: EEG (eletroencefalograma — diagnóstico e monitoramento de epilepsia, avaliação de encefalopatias), Doppler transcraniano (avaliação de circulação cerebral — em parceria com vascular ou como serviço próprio), e polissonografia em parceria (diagnóstico de apneia do sono — que tem overlap neurológico relevante)."),
        ("Epilepsia: Alta Cronicidade e Complexidade de Manejo",
         "A epilepsia afeta 3 milhões de brasileiros — é a doença neurológica crônica de maior prevalência depois da enxaqueca. O manejo inclui: diagnóstico preciso do tipo de epilepsia e síndrome epiléptica (que define o antiepiléptico de escolha), ajuste de medicação até o controle das crises (70% dos pacientes entram em remissão com medicação), monitoramento de efeitos adversos dos antiepilépticos (hepatotoxicidade do valproato, hiponatremia da oxcarbazepina, efeito cognitivo de certas drogas), avaliação de epilepsia refratária (pacientes que não controlam as crises com 2 drogas em dose adequada — candidatos a cirurgia de epilepsia ou dispositivos de neuroestimulação), e orientação ao paciente e família (restrições de dirigir, atividades aquáticas, gravidez na mulher com epilepsia). O neurologista de epilepsia precisa de EEG disponível e de acesso a ressonância magnética de protocolo para epilepsia."),
        ("Indicadores de Qualidade em Neurologia",
         "As métricas clínicas incluem: taxa de controle de crises em pacientes com epilepsia (percentual com remissão — abaixo de 1 crise por mês), redução de dias de enxaqueca por mês nos pacientes tratados com profilaxia (resposta ao tratamento — redução de ≥50% é o critério de resposta padrão), e NPS. As métricas de negócio incluem: tempo de espera para primeira consulta (a demanda por neurologia é muito maior que a oferta — tempo longo de espera indica capacidade insuficiente e oportunidade de expansão), receita por ENMG realizado (exame de alto valor com equipamento de custo moderado — boa margem), taxa de retorno de crônicos no intervalo correto (epilepsia e enxaqueca crônica retornam a cada 3-6 meses — receita recorrente previsível), e mix de consultas (particulares vs. convênio — neurologistas têm alta proporção de atendimento particular dado o tempo de consulta mais longo).")
    ],
    faq_list=[
        ("Quando devo procurar um neurologista para dor de cabeça?",
         "Procure um neurologista para cefaleia quando: as dores de cabeça são frequentes (mais de 4 episódios por mês), limitam suas atividades diárias ou de trabalho, não respondem aos analgésicos comuns, vêm acompanhadas de outros sintomas neurológicos (visão turva, formigamento, fraqueza — aura da enxaqueca ou sinal de cefaleia secundária), são progressivamente piores ao longo das semanas (nova cefaleia progressiva é sinal de alerta), ocorrem ao acordar ou acordam do sono, ou têm características de 'pior dor de cabeça da vida' de início súbito (trovoada — emergência neurológica que pode indicar hemorragia subaracnoide). O clínico geral pode iniciar o tratamento de enxaqueca episódica simples, mas cefaleia frequente, crônica ou com características atípicas requer avaliação neurológica especializada."),
        ("O que são anticorpos anti-CGRP para enxaqueca e têm cobertura pelo plano?",
         "Anticorpos monoclonais anti-CGRP (erenumabe/Aimovig, fremanezumabe/Ajovy, galcanezumabe/Emgality) são uma revolução no tratamento preventivo da enxaqueca: são aplicados por injeção subcutânea mensal ou trimestral e reduzem em 50% ou mais os dias de enxaqueca em 50-60% dos pacientes — com perfil de efeitos adversos muito favorável em comparação com os preventivos orais tradicionais. A cobertura pelos planos de saúde é obrigatória para enxaqueca crônica (≥15 dias de dor por mês, com ≥8 dias de enxaqueca) quando o paciente documentou falha de pelo menos 2 preventivos orais adequados. A autorização exige laudos detalhados com histórico de crises, diário de cefaleia, e documentação de tratamentos anteriores. O custo sem plano é de R$1.500 a R$3.500 por aplicação — tornando a aprovação pelo convênio crucial para a adesão ao tratamento."),
        ("Epilepsia impede de dirigir?",
         "No Brasil, a legislação de trânsito (CTB e Resolução CONTRAN) proíbe a concessão ou renovação de habilitação para pessoas com epilepsia ativa (crises nos últimos 2 anos). Após 2 anos sem crises documentadas com tratamento adequado, o neurologista pode emitir laudo favorando a concessão da CNH — que é avaliado pela junta médica do DETRAN. A legislação considera epilepsia controlada (sem crises há pelo menos 2 anos com tratamento) como condição compatível com direção, sujeita a avaliação periódica. O paciente deve informar ao neurologista caso dirija — pois a orientação clínica sobre os riscos e o controle das crises é parte do cuidado responsável. Países como EUA e Europa têm variações na legislação — geralmente com período de 3 a 12 meses sem crises como requisito, com variação por estado/país.")
    ]
)

# Article 4721 — SaaS sales: Media and digital entertainment
art(
    slug="vendas-para-o-setor-de-saas-de-midia-e-entretenimento-digital",
    title="Vendas para o Setor de SaaS de Mídia e Entretenimento Digital",
    desc="Estratégias de vendas B2B para plataformas SaaS de mídia e entretenimento digital: como abordar estúdios, criadores de conteúdo, streamings e veículos de comunicação.",
    h1="Vendas para o Setor de SaaS de Mídia e Entretenimento Digital",
    lead="A economia criativa digital movimenta R$200 bilhões no Brasil — com mais de 50 milhões de criadores de conteúdo, centenas de streamings e veículos digitais, e uma indústria de mídia em profunda transformação. Plataformas SaaS para esse setor cobrem desde distribuição de conteúdo e monetização até gestão de direitos e produção criativa.",
    sections=[
        ("O Ecossistema de Media Tech SaaS",
         "O mercado de SaaS para mídia e entretenimento digital inclui: plataformas de distribuição de vídeo OTT (infraestrutura para streamings — encoding, CDN, DRM, player, analytics de audiência), gestão de direitos autorais e licenciamento (CMS de direitos — tracking de royalties, contratos de licença, janelas de distribuição), plataformas de podcast e áudio (hospedagem, distribuição, monetização, analytics), ferramentas para criadores de conteúdo (gestão de redes sociais, planejamento de conteúdo, análise de métricas, colaboração com marcas — creator management platforms), gestão de publicidade digital (ad server, demand-side platform, sell-side platform — para veículos que monetizam por publicidade), e plataformas de gamificação e engajamento de audiência. O segmento de creator economy — ferramentas para os 50 milhões de criadores brasileiros que monetizam conteúdo — é o de maior crescimento no período recente."),
        ("O Decisor em Mídia e Entretenimento",
         "O perfil do decisor varia radicalmente por segmento: grandes veículos de mídia (Globo, Record, SBT, Band) têm CTO e diretor de tecnologia como decisores — ciclo de venda longo, enterprise, processo formal de procurement; streamings independentes e produtoras têm CEO ou head de tecnologia — processo mais ágil, abertura para trial; agências de conteúdo e studios têm head de produção ou sócio-fundador — decisão rápida, critério de escolha é produtividade imediata; e criadores de conteúdo individuais (YouTubers, influenciadores) são consumidores diretos — modelo PLG (Product-Led Growth), trial gratuito, conversão orgânica. A multiplicidade de perfis exige estratégias de GTM completamente diferentes — uma única abordagem de vendas não serve para todos."),
        ("Monetização de Conteúdo: Os Modelos que Impulsionam Demanda",
         "Os modelos de monetização de conteúdo digital que criam demanda por SaaS especializado incluem: SVOD (Subscription Video on Demand — assinatura mensal, modelo Netflix), AVOD (Advertising Video on Demand — gratuito, monetizado por publicidade, modelo YouTube), TVOD (Transactional Video on Demand — pay-per-view, modelo de aluguel de filme), modelos híbridos (freemium com anúncios no plano gratuito e sem anúncios no pago), e creator subscriptions (Patreon, Substack, plataformas de conteúdo exclusivo para assinantes). Cada modelo de monetização demanda ferramentas específicas: SVOD precisa de sistema de assinatura com gestão de cobrança recorrente e controle de acesso; AVOD precisa de ad server e métricas de viewability; e creator subscriptions precisam de plataformas de gestão de comunidade e conteúdo exclusivo. Plataformas SaaS que entendem a cadeia de monetização do cliente têm argumento de ROI mais concreto."),
        ("Creator Economy: O Segmento de Maior Crescimento",
         "A creator economy brasileira — com mais de 50 milhões de criadores de conteúdo, dos quais 5 milhões monetizam profissionalmente — criou um mercado inteiro de ferramentas especializadas. As necessidades dos criadores profissionais incluem: gestão de múltiplas redes sociais com agendamento e analytics centralizado (Mlabs, Later, Buffer), plataformas de link na bio com analytics (Linktree, Beacons), ferramentas de edição de vídeo e podcast (CapCut, Descript, Riverside.fm), plataformas de gestão de parcerias e campanhas com marcas (a principal fonte de receita dos grandes criadores — contratos de R$5 mil a R$500 mil por campanha), e plataformas de comunidade e conteúdo exclusivo (Hotmart Club, Telegram premium, Discord com monetização). A venda para criadores é fundamentalmente PLG — o produto precisa ser descoberto organicamente, ter UX excelente, e ter um tier gratuito útil que converte para pago quando o criador cresce."),
        ("Métricas de Saúde em Media Tech SaaS",
         "As métricas de produto incluem: horas de conteúdo gerenciado na plataforma (volume que cresce com a produção do cliente), audiência alcançada pelos conteúdos do cliente via plataforma (indicador de valor entregue — mais audiência = mais receita para o cliente), e NPS. As métricas de negócio incluem: MRR segmentado por tipo de cliente (enterprise de mídia vs. studio vs. criador individual — tickets muito diferentes), expansão por volume de conteúdo ou audiência (modelos de pricing que escalam com o uso têm NRR alto se o cliente crescer), churn por mudança de plataforma de distribuição (criadores que mudam de YouTube para TikTok ou vice-versa podem mudar de ferramenta — o produto agnóstico de plataforma tem vantagem), e CAC por canal (creators marketing — um criador influente que usa e recomenda a ferramenta organicamente tem impacto viral no segmento de criadores).")
    ],
    faq_list=[
        ("O que é OTT e como funciona tecnicamente?",
         "OTT (Over-The-Top) é a distribuição de conteúdo de vídeo via internet, sem passar pela infraestrutura de TV a cabo ou satélite — 'por cima' das operadoras de telecomunicação. Tecnicamente, uma plataforma OTT inclui: ingestão de conteúdo (upload ou captura ao vivo), transcodificação (conversão do vídeo para múltiplos formatos e resoluções — H.264, H.265, AV1 — para adaptação a diferentes velocidades de conexão), armazenamento na nuvem (AWS S3, Google Cloud Storage), CDN (Content Delivery Network — distribuição do conteúdo de servidores geograficamente próximos ao usuário para reduzir latência), DRM (Digital Rights Management — proteção de conteúdo contra download não autorizado — Widevine para Android/Chrome, FairPlay para Apple), player de vídeo (web e apps — com controle de qualidade adaptativo, legendas, analytics), e painel de analytics de audiência. Plataformas como Brightcove, JW Player e Brid.TV oferecem essa infraestrutura como SaaS para streamings que não querem construir do zero."),
        ("Como criadores de conteúdo monetizam no Brasil?",
         "Os criadores brasileiros têm múltiplas fontes de receita: publicidade nas plataformas (AdSense do YouTube, TikTok Creator Fund — geralmente a menor porção da receita total para quem já tem audiência consolidada), parcerias com marcas (publipost, branded content — a principal fonte de receita para grandes criadores, com cachês proporcionais ao nicho e ao engajamento da audiência), afiliação (comissão sobre vendas geradas via link de afiliado — especialmente comum em nichos como finanças, beleza e tecnologia), produtos próprios (infoprodutos como cursos e ebooks, produtos físicos da marca, serviços de consultoria), assinaturas de conteúdo exclusivo (Patreon, Hotmart Club, plataformas de membership), e licenciamento de conteúdo (reuso do conteúdo em outras plataformas ou veículos). Um criador profissional com 500 mil seguidores engajados pode faturar de R$30 mil a R$300 mil por mês combinando todas essas fontes."),
        ("Direitos autorais no Brasil: o que o criador de conteúdo precisa saber?",
         "A Lei de Direitos Autorais (Lei 9.610/1998) protege automaticamente toda criação original de um autor — sem necessidade de registro, a partir do momento da criação. Para criadores de conteúdo, os direitos autorais cobrem: vídeos, músicas compostas, roteiros, fotos autorais, textos. Os pontos práticos mais relevantes incluem: uso de músicas de terceiros em conteúdo (o YouTube e o TikTok têm sistemas de Content ID que identificam músicas protegidas — use músicas com licença Creative Commons ou pagas pela plataforma para evitar remoção e demonetização), contratos com marcas (transfira apenas os direitos que o contrato especifica — direito de veiculação da campanha por X meses, não cessão definitiva de tudo), e conteúdo gerado com IA (área ainda em discussão jurídica — a autoria de conteúdo 100% gerado por IA é questão aberta nas legislações brasileira e internacional).")
    ]
)

# Article 4722 — Consulting: Innovation management and R&D
art(
    slug="consultoria-de-gestao-da-inovacao-e-pesquisa-e-desenvolvimento",
    title="Consultoria de Gestão da Inovação e Pesquisa e Desenvolvimento",
    desc="Como funciona a consultoria de gestão da inovação e P&D: metodologias de inovação, gestão de portfólio de projetos inovadores, cultura de inovação e acesso a incentivos fiscais.",
    h1="Consultoria de Gestão da Inovação e Pesquisa e Desenvolvimento",
    lead="Inovação sistemática — não o insight acidental — é o que diferencia empresas que crescem continuamente das que ficam presas no presente. Consultoria de gestão da inovação ajuda organizações a construir a capacidade de inovar de forma intencional: com processos, métricas, portfólio e cultura que transformam criatividade em resultados de negócio.",
    sections=[
        ("O que é Consultoria de Gestão da Inovação",
         "A consultoria de inovação atua em: estratégia de inovação (definir onde e como inovar alinhado à estratégia competitiva), estrutura e governança de inovação (laboratório interno de inovação, corporate venture capital, programa de intraempreendedorismo, parceria com startups — como estruturar para não ser rejeitado pelo anticorpo organizacional), processos de inovação (funil de ideias — geração, triagem, desenvolvimento, escala — com gates de decisão claros), portfólio de inovação (balancear inovações incrementais de curto prazo vs. transformacionais de longo prazo — o modelo horizons de McKinsey), e acesso a incentivos fiscais (Lei do Bem — dedução de P&D do IRPJ — e outras linhas de financiamento para inovação). A maior alavanca de retorno em consultoria de inovação é frequentemente não a geração de ideias, mas a criação de processos para transformar ideias em projetos financiados e projetos em produtos lançados."),
        ("Design Thinking, Lean Startup e Agile: As Metodologias de Inovação",
         "As metodologias de inovação modernas formam um ecossistema complementar: Design Thinking (centrado no usuário — entender profundamente o problema antes de gerar soluções, por meio de empatia, síntese, ideação, prototipagem e teste) é ideal para inovação de produto e experiência do cliente. Lean Startup (Eric Ries — MVP, Build-Measure-Learn — ciclo rápido de hipótese, experimento e aprendizado) é ideal para novas iniciativas de negócio onde a demanda não está validada. Agile/Scrum é ideal para o desenvolvimento iterativo de produto após a validação da demanda — com sprints de 2 semanas, backlog priorizado e entrega incremental. Jobs to Be Done (JTBD — entender o 'trabalho' que o cliente contrata um produto para fazer) é o framework de descoberta mais eficaz para inovação de produto. A consultoria de inovação seleciona as metodologias mais adequadas ao tipo de inovação e ao estágio do projeto — sem dogmatismo metodológico."),
        ("Lei do Bem: Incentivo Fiscal para P&D no Brasil",
         "A Lei do Bem (Lei 11.196/2005) é o principal incentivo fiscal para P&D no Brasil: empresas de Lucro Real que realizam pesquisa e desenvolvimento tecnológico podem deduzir 60% a 80% das despesas de P&D do IRPJ e CSLL — além das deduções normais como despesa. Isso significa que R$1 investido em P&D qualificado pode resultar em R$1,80 de benefício líquido considerando a dedução fiscal. O benefício se aplica a: remuneração de pesquisadores e técnicos envolvidos em P&D, aquisição de instrumentos e equipamentos para pesquisa, serviços de P&D contratados de terceiros (incluindo ICTs — institutos de pesquisa), e royalties de licenciamento de tecnologia. A consultoria de inovação que ajuda a empresa a qualificar e documentar seus projetos de P&D para a Lei do Bem entrega ROI financeiro imediato — que financia o honorário da consultoria e ainda gera caixa adicional para reinvestimento em P&D."),
        ("Corporate Venture e Open Innovation: Conectando Startups à Grande Empresa",
         "Corporate Venture Capital (CVC) é a prática de grandes empresas investirem em startups early stage — não apenas por retorno financeiro, mas por acesso antecipado a tecnologias disruptivas, insights de mercado e potencial de aquisição. Open Innovation é a prática de buscar ideias e soluções fora dos muros da empresa: programas de aceleração corporativa, challenges e hackathons, parcerias com universidades e institutos de pesquisa, co-desenvolvimento com fornecedores e clientes. Os erros mais comuns em programas de open innovation incluem: startup como cobaias (empresa quer validar hipóteses sem comprometimento real com compra ou parceria — startups aprendem a evitar), burocracia corporativa que mata o piloto (o piloto com a startup levou 12 meses para acontecer — a startup quase morreu esperando), e falta de sponsor executivo (sem um C-level comprometido com o programa, o middle management bloqueia a parceria). A consultoria de inovação que tem experiência com CVC e open innovation ajuda a empresa a evitar esses erros."),
        ("Métricas de Inovação: Como Medir o que Importa",
         "As métricas de inovação são divididas em: métricas de input (quanto a empresa está investindo em inovação — % da receita em P&D, número de ideias no funil, recursos dedicados), métricas de processo (velocidade do funil de inovação — tempo médio de ideia ao MVP, taxa de conversão de etapa para etapa do funil), métricas de output (projetos concluídos, produtos lançados, patentes depositadas), e métricas de outcome (receita gerada por inovações dos últimos 3 anos, NPS de produtos novos vs. legado, market share conquistado por novos produtos). A métrica mais poderosa é a participação da receita de inovações recentes no total — empresas que lideraram em inovação historicamente têm de 20% a 40% da receita vindo de produtos com menos de 3 anos. Essa métrica conecta o investimento em inovação ao resultado de negócio de forma que o CFO e o CEO entendem.")
    ],
    faq_list=[
        ("Inovação incremental vs. disruptiva: onde focar?",
         "A resposta é: ambas, em proporções diferentes. Clayton Christensen demonstrou que empresas que focam exclusivamente em inovação incremental (melhorar o produto atual para os clientes atuais) ficam vulneráveis à disrupção por entrantes que atacam o mercado de baixo com solução mais simples e barata. Mas empresas que negligenciam o core em favor de apostas transformacionais ficam sem o caixa para financiar a inovação de longo prazo. O modelo de horizons de McKinsey propõe: 70% do investimento em inovação no core atual (H1 — incremental, ROI curto), 20% em adjacências (H2 — novos produtos ou mercados relacionados, ROI médio), e 10% em transformacionais (H3 — apostas de longo prazo, ROI incerto mas potencialmente enorme). A proporção ideal varia por setor e estágio da empresa — mercados em disrupção acelerada (como mídia, varejo, serviços financeiros) exigem maior peso em H2 e H3."),
        ("Como criar uma cultura de inovação na empresa?",
         "Cultura de inovação não se cria com hackathon anual — é construída por sistemas e comportamentos cotidianos. Os habilitadores mais importantes incluem: tolerância ao erro calculado (líderes que punem publicamente falhas de experimentos matam a inovação — o que se pune é a falta de aprendizado, não a falha em si), tempo dedicado à exploração (o modelo '20% time' do Google é o exemplo extremo — mas mesmo alocar 10% do tempo dos melhores talentos para projetos inovativos cria sinal de seriedade), recursos acessíveis sem burocracia excessiva (um pequeno orçamento disponível rapidamente para testar ideias — R$5 mil a R$20 mil sem aprovação de 5 níveis), reconhecimento de intraempreendedores (celebrar quem trouxe ideias que viraram produto, mesmo que em versão menor do que o planejado), e liderança que exemplifica curiosidade (CEO que faz perguntas, que visita clientes, que testa produtos concorrentes — modelo o comportamento inovativo para toda a organização)."),
        ("Patente vale a pena para startups brasileiras?",
         "Patente protege a invenção (produto, processo, uso) por 20 anos no Brasil — exclusividade de exploração comercial em troca da divulgação pública da invenção. Para startups, a decisão de patentear envolve trade-offs: o processo no INPI leva de 3 a 10 anos (lento para o ritmo de uma startup), custa de R$5 mil a R$50 mil entre taxas e honorários de advogado especialista, e a proteção é por país (uma patente brasileira não protege na China ou nos EUA — extensão internacional via PCT custa bem mais). Os cenários em que a patente faz sentido para startups: tecnologia deep tech com barreira técnica real que levaria anos para um concorrente replicar, produto que vai ser licenciado para grandes empresas (a patente é ativo negociável no processo de licenciamento), e startup que vai buscar investimento de fundos tech ou fazer M&A (patentes são ativos de IP que aumentam a avaliação). Para a maioria das startups de software, a velocidade de execução e o network effect protegem melhor do que uma patente.")
    ]
)

# Article 4723 — B2B SaaS: Condominium management
art(
    slug="gestao-de-negocios-de-empresa-de-b2b-saas-de-gestao-de-condominios",
    title="Gestão de Negócios de Empresa de B2B SaaS de Gestão de Condomínios",
    desc="Como estruturar e escalar uma empresa de B2B SaaS para gestão de condomínios: modelo de negócio, funcionalidades, go-to-market junto a síndicos e administradoras, e métricas.",
    h1="Gestão de Negócios de Empresa de B2B SaaS de Gestão de Condomínios",
    lead="O Brasil tem mais de 500 mil condomínios residenciais e comerciais, gerenciando mais de R$130 bilhões em receitas de condomínio por ano. Plataformas de gestão condominial — cobrindo comunicação, financeiro, manutenção e controle de acesso — têm oportunidade enorme num mercado dominado por processos manuais e planilhas.",
    sections=[
        ("O Mercado de CondoTech SaaS",
         "O mercado de SaaS para condomínios é segmentado por cliente: síndico profissional (pessoa física que administra dezenas de condomínios — precisa de plataforma para centralizar gestão de múltiplos clientes), administradora de condomínios (empresa que presta serviço de administração — as maiores têm centenas de condomínios na carteira), e síndico morador (condômino eleito para gerir o próprio condomínio — precisa de ferramenta simples e acessível). O produto cobre: comunicação (avisos, assembleias, enquetes, chat com moradores), financeiro (boletos de cota condominial, prestação de contas, orçamento anual, relatório de inadimplência), manutenção (ordem de serviço, agendamento de prestadores, histórico de manutenções), reserva de espaços comuns (salão de festas, churrasqueira, quadra — calendário de reservas), e controle de acesso (visitantes, entregas, prestadores). O ticket médio varia de R$150 a R$600/condomínio/mês dependendo do número de unidades e dos módulos."),
        ("Comunicação Condomínio-Morador: O Módulo de Maior Impacto",
         "A comunicação entre a gestão e os moradores é o principal problema que os síndicos relatam: informações importantes que não chegam a todos, assembleias com baixa participação, reclamações que ficam sem resposta. Apps de condomínio com notificações push, avisos segmentados por bloco/andar, votações online em assembleia, e canal de comunicação do síndico com moradores transformam esse processo. A assembleia virtual (votação online com validade jurídica — permitida pelo Código Civil após a pandemia) é funcionalidade de alto valor: elimina a dificuldade de reunir os moradores presencialmente, aumenta a participação e agiliza decisões. Moradores que conseguem reservar o salão de festas, registrar ocorrências e pagar a cota no app são moradores satisfeitos — o que se reflete na avaliação do síndico e da administradora."),
        ("Financeiro Condominial: Complexidade e Recorrência",
         "A gestão financeira de condomínio tem especificidades: cotas rateadas por fração ideal ou por unidade (dependendo do regulamento do condomínio), boletos emitidos mensalmente para centenas ou milhares de unidades, prestação de contas mensal para o conselho e anual em assembleia, orçamento anual aprovado em assembleia que serve de teto para as despesas, e fundo de reserva (reserva para obras extraordinárias — controle de saldo e aplicação). A inadimplência condominial — que traz multa, juros e eventual ação judicial — deve ser gerenciada ativamente: a plataforma que gera automaticamente o boleto com multa e juros no vencimento, envia cobranças por WhatsApp e notifica o conselho sobre inadimplentes acima de X meses é uma das funcionalidades de maior valor percebido pela administradora. Integração com bancos para split de pagamento (a cota paga pelo morador é dividida automaticamente entre a conta do condomínio e o fee da administradora) é diferencial de eficiência operacional."),
        ("Go-to-Market em CondoTech SaaS",
         "Os canais de venda para gestão de condomínios incluem: administradoras de condomínios (as grandes administradoras — como Lello, Hubert, Apsa — são canais de distribuição que levam a plataforma para centenas de condomínios clientes), síndicos profissionais (organizam-se em associações — ABRASIND, ANASSIND — e em grupos de WhatsApp onde trocam indicações de ferramentas), porteiros e zeladores digitalizados (há um movimento de capacitação digital de porteiros — plataformas que têm app simples para porteiro gerir visitantes têm acesso pelo lado da operação), e construtoras (que ao entregar um condomínio novo recomendam a plataforma de gestão para a comissão de obras — o momento de start do condomínio é o melhor para adoção). O marketing digital com SEO para 'aplicativo para condomínio' e 'sistema de gestão condominial' captura alta demanda inbound — síndicos e síndicos profissionais pesquisam ativamente essas soluções no Google."),
        ("Métricas de Saúde do CondoTech SaaS",
         "As métricas de produto incluem: unidades ativas gerenciadas (o número de apartamentos/casas que usam a plataforma — a métrica de escala), moradores ativos no app (percentual de condôminos que acessaram o app pelo menos uma vez no mês — indica adoção real), e NPS do síndico. As métricas de negócio incluem: MRR por condomínio (com expansão ao adicionar módulos — controle de acesso, boleto bancário integrado), churn (condomínios raramente trocam de administradora ou de sistema — churn baixo quando bem adotado), NRR (administradora que cresce sua carteira de condomínios expande naturalmente o número de condomínios na plataforma), e CAC por administradora parceira vs. direto (a parceria com administradora tem CAC unitário muito mais baixo — o canal vende por você).")
    ],
    faq_list=[
        ("Assembleia virtual de condomínio tem validade jurídica?",
         "Sim — a assembleia virtual (online) de condomínio tem validade jurídica no Brasil. A Lei 14.010/2020 (aprovada durante a pandemia) estabeleceu a possibilidade de assembleias remotas em condomínios, e o Código Civil foi posteriormente interpretado pelos tribunais como compatível com assembleias online desde que a convocação siga as formalidades exigidas (prazo de antecedência, pauta clara, meios de comunicação adequados) e que todos os condôminos tenham acesso à participação. Plataformas de gestão condominial que oferecem funcionalidade de assembleia virtual com registro de quórum, identificação dos participantes, gravação da sessão e ata digital têm o documento necessário para validade jurídica. A assembleia híbrida (parte presencial, parte online) é a alternativa mais adotada para maximizar a participação."),
        ("Como reduzir inadimplência em condomínio?",
         "A inadimplência condominial varia de 5% a 20% dependendo do perfil socioeconômico e da eficiência da gestão. As melhores práticas para reduzir incluem: boleto com código de barras e Pix gerados automaticamente (reduz o esquecimento), régua de cobrança automatizada (WhatsApp no dia do vencimento, ligação em D+5, notificação ao conselho em D+15), negociação de parcelamento formalizada (acordo assinado digitalmente — o inadimplente que tem plano de pagamento honra mais do que o que não tem), e ação judicial ágil para inadimplentes crônicos (a notificação extrajudicial ou o ajuizamento de cobrança após 3 meses de inadimplência sinaliza para a comunidade que a inadimplência tem consequências). A transparência nas contas (moradores que entendem para onde vai o dinheiro da cota tendem a pagar mais regularmente) é alavanca de compliance subestimada."),
        ("Síndico profissional vs. síndico morador: qual a diferença?",
         "Síndico morador é um condômino eleito pela assembleia para gerir o próprio condomínio — sem remuneração obrigatória (ou com taxa de isenção de cota), geralmente sem formação específica em administração condominial. É o modelo tradicional e ainda dominante em condomínios de pequeno e médio porte. Síndico profissional é uma pessoa física (CPF) ou empresa (CNPJ) especializada em gestão condominial, contratada pela assembleia — com remuneração mensal (geralmente de R$1.500 a R$8.000/mês dependendo do porte do condomínio), capacitação técnica, e responsabilidade profissional pelo cumprimento das obrigações legais e financeiras. A tendência dos últimos anos é de crescimento do síndico profissional — especialmente em condomínios maiores, onde a complexidade de gestão supera o que um morador sem formação consegue administrar. Plataformas condominiais que atendem o síndico profissional com funcionalidades de gestão multicondomínio têm vantagem nesse segmento.")
    ]
)

# Article 4724 — Clinic: Gynecology and women's health
art(
    slug="gestao-de-clinicas-de-ginecologia-e-saude-da-mulher",
    title="Gestão de Clínicas de Ginecologia e Saúde da Mulher",
    desc="Guia de gestão para clínicas de ginecologia e saúde da mulher: fluxo de atendimento, preventivo, obstetrícia, menopausa, e indicadores de qualidade assistencial.",
    h1="Gestão de Clínicas de Ginecologia e Saúde da Mulher",
    lead="A ginecologia e obstetrícia é uma das especialidades médicas de maior demanda no Brasil — toda mulher a partir da adolescência necessita de acompanhamento ginecológico regular. Clínicas de saúde da mulher cobrem desde o preventivo rotineiro até a alta complexidade obstétrica e o manejo da menopausa, com oportunidade crescente em medicina preventiva feminina.",
    sections=[
        ("O Escopo da Ginecologia e Saúde da Mulher",
         "A ginecologia e obstetrícia abrange: ginecologia preventiva (consulta anual, colpocitologia oncótica — papanicolau, rastreamento de ISTs, orientação contraceptiva), patologia cervical (colposcopia, biópsia de colo uterino, tratamento de lesões precursoras do câncer de colo), reprodução humana assistida (investigação de infertilidade, indução de ovulação, FIV — fertilização in vitro), endocrinologia ginecológica (síndrome dos ovários policísticos, amenorreia, disfunção tireoidiana com impacto reprodutivo), menopausa e climatério (terapia hormonal, manejo de sintomas vasomotores, osteoporose), uroginecologia (incontinência urinária, prolapso pélvico), e obstetrícia (pré-natal de baixo e alto risco, parto, puerpério). O preventivo anual é o ponto de entrada de toda mulher na clínica de ginecologia — e é a âncora da relação de longo prazo entre a paciente e o ginecologista."),
        ("Preventivo e Rastreamento: O Fluxo de Alta Frequência",
         "A consulta ginecológica preventiva anual é o procedimento de maior volume e de maior impacto em saúde pública: colpocitologia oncótica (papanicolau) para rastreamento de câncer de colo uterino a partir dos 25 anos, exame das mamas (e mamografia a partir dos 40-50 anos dependendo do risco), rastreamento de ISTs (HIV, sífilis, hepatites B e C — especialmente importante em jovens sexualmente ativas), orientação contraceptiva (escolha do método mais adequado ao perfil e momento de vida da paciente), e vacinação HPV e hepatite B. Clínicas de ginecologia que têm colposcopia própria — para seguimento imediato das pacientes com papanicolau alterado — evitam a perda de seguimento que é uma das principais causas de progressão de lesões precursoras tratáveis para câncer instalado."),
        ("Reprodução Assistida: Medicina de Alto Valor e Alta Emoção",
         "As clínicas de reprodução humana assistida (RHA) são um nicho de alta complexidade técnica e alto envolvimento emocional da paciente: o desejo de ter filhos é um dos mais intensos que existem, e casais que enfrentam infertilidade vivenciam um processo de alta carga emocional. As clínicas de RHA oferecem: investigação do casal (dosagens hormonais, histerossalpingografia, espermograma), indução de ovulação (com monitoramento ultrassonográfico), inseminação intrauterina (IUI), fertilização in vitro (FIV) com transferência de embrião fresco ou congelado, e diagnóstico genético pré-implantacional (PGT — avaliação de cromossomos do embrião antes da transferência). O investimento por ciclo de FIV no Brasil varia de R$15 mil a R$40 mil — sendo um dos procedimentos médicos de maior ticket do mercado privado. A comunicação empática e o suporte emocional às pacientes são tão importantes quanto a excelência técnica nesse segmento."),
        ("Menopausa e Climatério: Mercado em Expansão",
         "O envelhecimento da população brasileira e a maior consciência de saúde das mulheres a partir dos 40 anos criou um mercado relevante em medicina da menopausa e longevidade feminina. A consulta de menopausa aborda: sintomas vasomotores (fogachos, suores noturnos — que afetam 70% das mulheres), alterações de humor e sono, secura vaginal e sintomas genitourinários (síndrome genitourinária da menopausa — GSM), saúde óssea (rastreamento de osteopenia/osteoporose com densitometria, prevenção de fraturas), risco cardiovascular na pós-menopausa, e terapia hormonal da menopausa (TH — que alivia sintomas e tem benefícios cardiovasculares e ósseos quando iniciada no momento adequado). O segmento de medicina de longevidade feminina — que integra ginecologia, nutrologia e medicina do estilo de vida — é o de maior crescimento premium nesse mercado."),
        ("Indicadores de Qualidade em Ginecologia",
         "As métricas clínicas incluem: taxa de cobertura de papanicolau na carteira de pacientes (percentual de mulheres elegíveis com exame em dia — indicador de qualidade preventiva), taxa de seguimento de pacientes com papanicolau alterado (a paciente com lesão identificada voltou para a colposcopia?), taxa de sucesso de FIV por transferência (taxa de gravidez clínica — padrão nacional é de 35-45% para mulheres abaixo de 35 anos), e NPS. As métricas de negócio incluem: receita por procedimento (colposcopia + biópsia, FIV, inserção de DIU — os procedimentos são a maior fonte de receita além das consultas), taxa de retorno para o preventivo anual (paciente que voltou todo ano tem LTV muito alto — o ginecologista pode acompanhar por décadas), e taxa de conversão de consulta de pré-natal para parto na clínica ou com o médico (quando há obstetrícia).")
    ],
    faq_list=[
        ("Com que frequência devo ir ao ginecologista?",
         "A frequência recomendada pela FEBRASGO (Federação Brasileira das Associações de Ginecologia e Obstetrícia) e pelo INCA (Instituto Nacional de Câncer) inclui: consulta anual a partir da primeira relação sexual ou dos 21 anos para mulheres assintomáticas, colpocitologia oncótica (papanicolau) a cada 3 anos após 2 exames anuais normais (ou a cada 1-3 anos dependendo do histórico), mamografia anual a partir dos 40 anos (FEBRASGO) ou dos 50 anos (algumas diretrizes internacionais — mas no Brasil, 40 anos é o consenso da maioria das sociedades), e densitometria óssea na menopausa (ou antes se há fatores de risco para osteoporose). Mulheres com fatores de risco (histórico familiar de câncer ginecológico, HIV positivo, imunossupressão, histórico de papanicolau alterado) têm intervalo de seguimento reduzido — definido individualmente pelo ginecologista."),
        ("DIU hormonal (Mirena) vs. DIU de cobre: qual a diferença?",
         "O DIU (Dispositivo Intrauterino) tem dois tipos com mecanismos completamente diferentes. DIU de cobre (não hormonal): o cobre tem ação espermicida e impede a fertilização, além de alterar o endométrio dificultando a implantação. Dura de 5 a 10 anos. Pode aumentar o fluxo menstrual e a cólica nos primeiros meses. É a única contracepção de emergência não hormonal (quando inserido em até 5 dias após relação desprotegida). DIU hormonal (levonorgestrel — Mirena, Kyleena, Liletta): libera progestogênio localmente, tornando o muco cervical espesso (barreira para espermatozoide), atrofiando o endométrio e suprimindo parcialmente a ovulação. Reduz drasticamente o fluxo menstrual (muitas mulheres entram em amenorreia — ausência de menstruação) e as cólicas. Dura de 3 a 5 anos dependendo do modelo. É excelente para tratamento de endometriose, miomas e menorragia além da contracepção."),
        ("Síndrome dos ovários policísticos (SOP) tem cura?",
         "A SOP não tem cura — é uma condição crônica que persiste ao longo da vida reprodutiva e se modifica após a menopausa. No entanto, seus sintomas são muito bem manejáveis com tratamento adequado. A SOP é a causa mais comum de irregularidade menstrual e infertilidade ovulatória em mulheres em idade reprodutiva — afetando 5-10% das mulheres. Os pilares do tratamento incluem: mudança de estilo de vida (a perda de 5-10% do peso em mulheres com sobrepeso regulariza a ovulação em muitos casos), contracepção hormonal para regularizar o ciclo e reduzir o hiperandrogenismo (acne, hirsutismo), metformina para resistência insulínica associada, indução de ovulação para mulheres que desejam gravidez (citrato de clomifeno, letrozol, gonadotrofinas), e tratamento da acne e hirsutismo. O acompanhamento de longo prazo é importante pois a SOP está associada a maior risco de diabetes tipo 2 e síndrome metabólica ao longo da vida.")
    ]
)

# Article 4725 — SaaS sales: Insurance and brokerages
art(
    slug="vendas-para-o-setor-de-saas-de-seguros-e-corretoras",
    title="Vendas para o Setor de SaaS de Seguros e Corretoras",
    desc="Estratégias de vendas B2B para plataformas SaaS de seguros e corretoras: como abordar corretoras de seguros, seguradoras e insurtechs para fechar contratos de gestão.",
    h1="Vendas para o Setor de SaaS de Seguros e Corretoras",
    lead="O mercado segurador brasileiro faturou R$380 bilhões em prêmios em 2024, com mais de 100 mil corretores de seguros ativos. Plataformas SaaS para corretoras e seguradoras cobrem desde gestão de apólices e cotações até automação de sinistros — um mercado altamente regulado com demanda crescente por digitalização.",
    sections=[
        ("O Ecossistema de InsurTech SaaS",
         "O mercado de SaaS para seguros inclui: plataformas de gestão para corretoras de seguros (portfólio de apólices, renovações, comissões, CRM de clientes segurados), sistemas de cotação e comparação (multi-seguradora em tempo real — o corretor coteia nas principais seguradoras com um clique), gestão de sinistros (abertura, acompanhamento, regulação — para seguradoras e corretoras que gerenciam o sinistro pelo cliente), plataformas de compliance regulatório (SUSEP, BACEN — relatórios obrigatórios, controle de solvência), ferramentas de subscrição (pricing de risco, análise de exposição de carteira), e plataformas de seguro embarcado (embedded insurance — integração de seguro em produtos não-financeiros). A SUSEP (Superintendência de Seguros Privados) regulamenta o setor — e as plataformas SaaS devem estar em conformidade com as normas SUSEP para operar com dados de apólices."),
        ("O Corretor de Seguros: Perfil e Dores",
         "O corretor de seguros brasileiro é um empreendedor independente — a maioria opera como pessoa física (PF) ou micro/pequena empresa, com carteira de clientes construída ao longo de anos por relacionamento pessoal. Suas principais dores operacionais incluem: gestão manual de renovações (a apólice que vence em 30 dias e o corretor não sabe — perda de receita de comissão e risco de deixar o cliente desprotegido), cotação em múltiplas seguradoras para o mesmo cliente (processo manual que consome horas), controle de comissões (receber da seguradora conforme o prometido, sem erros), e CRM de clientes (o relacionamento com o segurado é a maior vantagem competitiva do corretor — um sistema que ajuda a manter contato no aniversário, no vencimento da apólice e em momentos de vida é diferencial). O corretor que resolve essas dores com tecnologia consegue atender mais clientes com a mesma equipe — o que é a proposta de valor central do SaaS para corretoras."),
        ("Cotação Multi-Seguradora: O Módulo de Maior Produtividade",
         "A cotação de seguro em múltiplas seguradoras simultaneamente é o módulo de maior produtividade imediata para o corretor: em vez de entrar em 5 sistemas diferentes (Porto Seguro, Bradesco Seguros, SulAmérica, Mapfre, Tokio Marine) e preencher os mesmos dados 5 vezes, o corretor preenche uma vez na plataforma e recebe as cotações comparadas. Para seguro auto, o processo que levava 30 minutos passa a levar 3 minutos. Para seguro de vida e planos empresariais, a cotação simultânea permite mostrar ao cliente uma análise comparativa que demonstra o valor do corretor — ele não é apenas um canal de vendas, é um consultor que garante a melhor relação custo-benefício. Plataformas como Minuto Seguros, Youse (B2B para corretores), e sistemas proprietários de corretoras médias e grandes são os principais players nesse módulo."),
        ("Renovação Automática: Evitando Lapso de Cobertura",
         "O lapso de cobertura — quando a apólice vence e o segurado fica sem seguro por alguns dias ou semanas até a renovação — é risco operacional para o corretor (que perde a comissão e pode perder o cliente) e risco real para o segurado (que pode ter um sinistro sem cobertura). Plataformas de gestão de corretora que automatizam a régua de renovação — aviso ao segurado 60, 30 e 15 dias antes do vencimento, cotação automática de renovação na mesma seguradora e em alternativas, proposta enviada por WhatsApp com link de aprovação — reduzem dramaticamente o lapso de cobertura e o churn de carteira. A renovação automatizada é o módulo com ROI mais imediato para o corretor: um corretor que perde 10% de renovações por falta de seguimento deixa de faturar dezenas de milhares de reais em comissão por ano."),
        ("Métricas de Saúde em InsurTech SaaS",
         "As métricas de produto incluem: apólices ativas gerenciadas (a métrica de escala — quanto mais apólices, mais switching cost), renovações processadas com sucesso (taxa de retenção da carteira do corretor), e NPS do corretor. As métricas de negócio incluem: MRR por corretor ou corretora (ticket de R$100 a R$1.500/mês dependendo do volume de apólices), churn (corretores raramente trocam de sistema quando adotaram bem — switching cost alto pelo volume de apólices e histórico de clientes), NRR via expansão de carteira (corretor que cresce a carteira paga mais em planos baseados em volume), e CAC por canal (SUSEP credenciamentos, sindicatos de corretores de seguros como Sincor, e parceria com seguradoras que indicam sistemas para seus corretores credenciados são canais eficientes).")
    ],
    faq_list=[
        ("O que é SUSEP e como ela regula o mercado de seguros?",
         "SUSEP (Superintendência de Seguros Privados) é a autarquia federal vinculada ao Ministério da Fazenda que regula e fiscaliza o mercado de seguros, previdência privada aberta, capitalização e resseguros no Brasil. Suas funções incluem: licenciamento de seguradoras (para operar no Brasil, a seguradora precisa de autorização da SUSEP), credenciamento de corretores (o corretor de seguros deve ser habilitado pela SUSEP — a prova de habilitação é obrigatória), aprovação de produtos (todo produto de seguro deve ser submetido à SUSEP antes de ser comercializado), e fiscalização de solvência (a seguradora deve manter capital suficiente para honrar os sinistros — a SUSEP monitora os indicadores de solvência). Para plataformas SaaS que operam no mercado de seguros, a conformidade com as normas SUSEP — especialmente quanto ao armazenamento e uso de dados de apólices e sinistros — é obrigatória."),
        ("Como funciona a comissão do corretor de seguros?",
         "A comissão do corretor de seguros é paga pela seguradora — não pelo segurado — como percentual do prêmio (valor que o segurado paga pelo seguro). A taxa de comissão varia por ramo de seguro: seguro auto (3% a 15% do prêmio), seguro de vida (5% a 30%), seguro saúde (3% a 8%), seguro de pessoas em grupo (2% a 5%), e seguro empresarial (5% a 15%). Para seguros de vida inteira e previdência privada, a comissão pode incluir comissão de angariação (sobre o primeiro prêmio) e comissão de renovação (percentual menor sobre prêmios subsequentes). A SUSEP limita a comissão em alguns ramos. O modelo de corretagem de seguros cria receita recorrente natural — enquanto o cliente mantém o seguro ativo, o corretor recebe a comissão de renovação. Uma carteira de seguros bem gerenciada é um ativo de renda previsível de longo prazo para o corretor."),
        ("Seguro de vida é obrigatório para quem?",
         "Não há seguro de vida obrigatório por lei para pessoas físicas no Brasil. No entanto, algumas situações criam obrigação prática: financiamento habitacional (o MIP — Morte e Invalidez Permanente — é obrigatório nos contratos de financiamento imobiliário pelo SFH/SBPE), financiamento de veículos por algumas linhas, e convenções coletivas de trabalho em alguns setores (que obrigam o empregador a manter seguro de vida em grupo para funcionários). Para pessoas jurídicas, o seguro de vida em grupo é contratado voluntariamente pelo empregador como benefício — mas é altamente recomendado por convenções coletivas e acordos sindicais. O seguro de vida pessoal (não vinculado ao financiamento) é amplamente subcontratado no Brasil comparado a países desenvolvidos — o mercado de conscientização e venda ativa de vida individual é uma das maiores oportunidades do setor de seguros brasileiro.")
    ]
)

# Article 4726 — Consulting: Project management and PMO
art(
    slug="consultoria-de-gestao-de-projetos-e-pmo",
    title="Consultoria de Gestão de Projetos e PMO",
    desc="Como funciona a consultoria de gestão de projetos e PMO: metodologias ágeis e preditivas, estrutura de PMO, indicadores de desempenho de projetos e certificações.",
    h1="Consultoria de Gestão de Projetos e PMO",
    lead="Projetos mal gerenciados custam às organizações brasileiras bilhões de reais por ano em retrabalho, atrasos e escopo entregue errado. Consultoria de gestão de projetos e PMO ajuda empresas a entregar projetos no prazo, no orçamento e com o escopo correto — transformando caos em método sem perder a velocidade.",
    sections=[
        ("O que é PMO e Por que Criar Um",
         "PMO (Project Management Office) é o escritório que padroniza, governa e apoia a execução de projetos na organização. Pode ter três modelos principais: PMO de suporte (biblioteca de metodologias, templates e ferramentas — serve os gerentes de projeto sem exercer autoridade direta), PMO de controle (define padrões obrigatórios e monitora conformidade — pode exigir uso de metodologia específica e auditar projetos), e PMO diretivo (responsável direto pela gestão dos projetos — os gerentes de projeto reportam ao PMO). A consultoria de PMO ajuda a empresa a: diagnosticar a maturidade atual em gestão de projetos (frameworks como OPM3 e PMMM), desenhar a estrutura ideal de PMO para o contexto, implementar processos e ferramentas, e capacitar a equipe de gerenciamento de projetos. Criar um PMO sem diagnóstico preciso resulta em estrutura burocrática que atrasa mais do que ajuda."),
        ("Metodologias de Gestão de Projetos: Preditivo, Ágil e Híbrido",
         "O debate metodológico em gestão de projetos evoluiu: não é mais 'Cascata vs. Ágil', mas sim qual abordagem é mais adequada para cada tipo de projeto. Projetos preditivos (Waterfall, PMBOK/PMI) são adequados quando os requisitos são estáveis, o escopo é bem definido desde o início, e os stakeholders querem previsibilidade de prazo e custo — projetos de engenharia, construção, implantação de ERP. Projetos ágeis (Scrum, Kanban, SAFe) são adequados para desenvolvimento de software, produtos digitais, inovação — onde os requisitos evoluem com o aprendizado e a entrega incremental é preferível. Projetos híbridos combinam as duas abordagens: o PMO garante governança, orçamento e comunicação com stakeholders pelo método preditivo, enquanto as equipes de execução usam sprints ágeis. A consultoria de PMO que só sabe uma metodologia entrega menos valor do que a que sabe quando aplicar cada abordagem."),
        ("Indicadores de Desempenho de Projetos: EVM e Além",
         "O Earned Value Management (EVM) é o framework mais rigoroso para medir desempenho de projetos: combina escopo, prazo e custo em métricas integradas. Os indicadores principais incluem: CPI (Cost Performance Index — valor ganho dividido pelo custo real — acima de 1 está abaixo do orçamento), SPI (Schedule Performance Index — valor ganho dividido pelo valor planejado — acima de 1 está adiantado no cronograma), EAC (Estimate at Completion — projeção do custo total do projeto com base no desempenho atual), e VAC (Variance at Completion — projeção do desvio de custo no final). Além do EVM, métricas de agilidade incluem velocity (pontos de story entregues por sprint), burn-down (progresso do backlog), e cycle time (tempo médio de ideia à entrega). O dashboard de portfólio de projetos — que o CEO e o board consultam — precisa mostrar saúde de todos os projetos em uma visão consolidada sem precisar ler dezenas de relatórios individuais."),
        ("Gestão de Riscos em Projetos: Proatividade vs. Reatividade",
         "A gestão de riscos é a diferença entre projetos que entregam e projetos que surpreendem negativamente a liderança. O processo de gestão de riscos inclui: identificação (quais eventos podem impactar prazo, custo ou escopo?), análise qualitativa (probabilidade × impacto — priorizar os riscos de maior exposição), análise quantitativa (Monte Carlo para simular distribuição de resultados do projeto, especialmente custo e prazo), planejamento de resposta (evitar, transferir, mitigar, aceitar), e monitoramento e controle (verificar se os riscos se materializaram, se novas ameaças surgiram, se as respostas funcionaram). O risco mais frequentemente subestimado em projetos é o risco de stakeholder (patrocinador que muda, usuários que resistem à mudança, outros projetos que disputam os mesmos recursos). A consultoria de PMO que inclui gestão de stakeholders como disciplina central — não apenas gestão técnica do projeto — entrega projetos com mais sucesso."),
        ("Certificações em Gestão de Projetos: PMP e Além",
         "As certificações de gestão de projetos mais reconhecidas incluem: PMP (Project Management Professional — PMI — a mais reconhecida globalmente, exige 36 meses de experiência liderando projetos, 35 horas de educação em GP, e aprovação em exame de 180 questões), CAPM (Certified Associate in Project Management — PMI — nível entrada, sem exigência de experiência), PSM/CSM (Professional Scrum Master / Certified ScrumMaster — foco em Scrum e agilidade), SAFe (Scaled Agile Framework — para gerentes de produto e RTE em grandes organizações ágeis), e PRINCE2 (mais usado na Europa e em projetos governamentais). No Brasil, o PMP é a certificação de maior prestígio e valorização salarial em gestão de projetos — gerentes de projeto PMP certificados têm salário 25% maior em média do que não certificados, segundo pesquisa do PMI. A consultoria que oferece capacitação e preparatório PMP como serviço complementar agrega valor ao cliente além do projeto de implantação do PMO.")
    ],
    faq_list=[
        ("Qual a diferença entre projeto e processo?",
         "Projeto é um esforço temporário empreendido para criar um produto, serviço ou resultado único — tem início e fim definidos, equipe alocada, orçamento específico e entrega clara. Processo é uma atividade contínua e repetitiva que ocorre regularmente para manter a operação — não tem fim definido, faz parte da operação corrente. Exemplos: implementar um novo ERP é um projeto (temporário, único, tem prazo de entrega); rodar a folha de pagamento mensal é um processo (repetitivo, contínuo). A confusão entre projeto e processo leva a erros de governança: gerenciar uma operação contínua com metodologia de projeto cria burocracia desnecessária; gerenciar uma iniciativa transformacional sem metodologia de projeto leva ao caos de escopo e prazo. O PMO cuida dos projetos; o gestor de operações e melhoria contínua cuida dos processos."),
        ("Scrum pode ser usado para projetos fora de desenvolvimento de software?",
         "Sim — o Scrum foi criado para desenvolvimento de software mas seus princípios se aplicam a qualquer trabalho complexo onde os requisitos evoluem. Casos de uso bem-sucedidos de Scrum fora de TI incluem: projetos de marketing (squads de conteúdo com sprints de 2 semanas e backlog priorizado), transformação organizacional (iniciativas de RH e culture change com ciclos iterativos), projetos de pesquisa e desenvolvimento não-software (com as adaptações necessárias para o ciclo físico de desenvolvimento), e projetos de consultoria (entregas incrementais revisadas pelo cliente a cada sprint em vez de entrega final única). A condição de sucesso é que o trabalho seja divisível em partes que entregam valor incremental, que o cliente possa dar feedback a cada sprint, e que a equipe tenha autonomia para organizar como vai fazer o trabalho dentro do sprint."),
        ("O que é o Triângulo de Ferro em gestão de projetos?",
         "O Triângulo de Ferro (ou Triângulo de Projeto) é o modelo clássico que representa as três restrições fundamentais de qualquer projeto: Escopo (o que será entregue), Prazo (quando será entregue) e Custo (quanto custará). O princípio central é que essas três variáveis são interdependentes: se você aumenta o escopo sem aumentar o prazo ou o custo, a qualidade inevitavelmente cai. Se você reduz o prazo sem reduzir o escopo ou aumentar o custo (mais recursos), algo tem que ceder. O gerente de projeto e o PMO existem para equilibrar essas três restrições de acordo com as prioridades do patrocinador. A versão moderna inclui uma quarta dimensão — Qualidade — no centro do triângulo: as três restrições externas definem o limite dentro do qual a qualidade pode ser maximizada. Quando o patrocinador pede 'mais barato, mais rápido e mais funcionalidades ao mesmo tempo', o gerente de projeto tem o dever de apresentar o Triângulo de Ferro e forçar uma conversa sobre o que será sacrificado.")
    ]
)

# ── Sitemap & trilha update ──────────────────────────────────────────────────
sitemap_path = pathlib.Path(__file__).parent / "sitemap.xml"
trilha_path  = pathlib.Path(__file__).parent / "trilha.html"

new_slugs = [
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-ecommerce-e-marketplace",
     "Gestão de Negócios de Empresa de B2B SaaS de E-commerce e Marketplace"),
    ("gestao-de-clinicas-de-neurologia-e-cefaleia",
     "Gestão de Clínicas de Neurologia e Cefaleia"),
    ("vendas-para-o-setor-de-saas-de-midia-e-entretenimento-digital",
     "Vendas para o Setor de SaaS de Mídia e Entretenimento Digital"),
    ("consultoria-de-gestao-da-inovacao-e-pesquisa-e-desenvolvimento",
     "Consultoria de Gestão da Inovação e Pesquisa e Desenvolvimento"),
    ("gestao-de-negocios-de-empresa-de-b2b-saas-de-gestao-de-condominios",
     "Gestão de Negócios de Empresa de B2B SaaS de Gestão de Condomínios"),
    ("gestao-de-clinicas-de-ginecologia-e-saude-da-mulher",
     "Gestão de Clínicas de Ginecologia e Saúde da Mulher"),
    ("vendas-para-o-setor-de-saas-de-seguros-e-corretoras",
     "Vendas para o Setor de SaaS de Seguros e Corretoras"),
    ("consultoria-de-gestao-de-projetos-e-pmo",
     "Consultoria de Gestão de Projetos e PMO"),
]

sm = sitemap_path.read_text(encoding="utf-8")
new_urls = "".join(
    f"  <url><loc>https://produtovivo.com.br/blog/{s}/</loc></url>\n"
    for s, _ in new_slugs
)
sitemap_path.write_text(sm.replace("</urlset>", new_urls + "</urlset>"), encoding="utf-8")

tr = trilha_path.read_text(encoding="utf-8")
new_items = "".join(
    f'  <li><a href="/blog/{s}/">{t}</a></li>\n'
    for s, t in new_slugs
)
trilha_path.write_text(tr.replace("</ul>", new_items + "\n</ul>", 1), encoding="utf-8")

print("Done — batch 1618")
